import json
f = 'C:/Dev/devlearner/devlearner/learning-system/src/main/resources/seeds/B18-exception-handling.json'
with open(f, encoding='utf-8') as fh: data = json.load(fh)

improvements = {
    1: {"description": "Implement `safeParseInt(String s)` that returns an `Optional<Integer>` — returns the parsed value or `Optional.empty()` if the string is not a valid integer.\n\n**Example 1:**\nsafeParseInt(\"42\") => Optional[42]\nsafeParseInt(\"-7\") => Optional[-7]\nsafeParseInt(\"abc\") => Optional.empty()\nsafeParseInt(\"\") => Optional.empty()", "sampleInput": "safeParseInt(\"abc\")", "sampleOutput": "Optional.empty()"},
    2: {"description": "Create a custom `ValidationException extends RuntimeException` with a list of error messages. Throw it when multiple fields are invalid.\n\n**Example:**\nvalidateUser(\"\", \"not-email\", -5)\n=> throws ValidationException with errors:\n   [\"Name required\", \"Invalid email\", \"Age must be positive\"]\n\nvalidationException.getErrors() => [\"Name required\", \"Invalid email\", \"Age must be positive\"]", "sampleInput": "validateUser(\"\", \"not-email\", -5)", "sampleOutput": "ValidationException: [Name required, Invalid email, Age must be positive]"},
    3: {"description": "Implement a `Stack<T>` that throws custom `EmptyStackException` on `pop()` and `peek()` when empty.\n\n**Example:**\nStack<Integer> s = new Stack<>();\ns.push(1); s.pop() => 1;\ns.pop() => throws EmptyStackException(\"Stack is empty\")\ns.peek() => throws EmptyStackException(\"Stack is empty\")\n\n**Key insight:** Custom exceptions communicate domain intent better than generic `RuntimeException`.", "sampleInput": "pop() on empty stack", "sampleOutput": "throws EmptyStackException(\"Stack is empty\")"},
    4: {"description": "Predict the output — `finally` always runs, even after `return`:\n\n```java\nstatic String test() {\n    try { return \"try\"; }\n    finally { System.out.println(\"finally\"); }\n}\nSystem.out.println(test());\n```\n\n**Output:**\nfinally\ntry\n\n**Key insight:** `finally` executes before the return value is delivered. If `finally` has its own `return`, it overrides the `try` return.", "sampleInput": "test() with return in try, println in finally", "sampleOutput": "\"finally\"\n\"try\""},
    5: {"description": "Demonstrate a resource leak: opening a file without try-with-resources may leave it open on exception. Refactor to use try-with-resources.\n\n**Before (leaky):**\nFileReader r = new FileReader(\"file.txt\");\nthrowsException(); // r never closed\n\n**After (safe):**\ntry (FileReader r = new FileReader(\"file.txt\")) {\n    throwsException();\n} // r.close() called even on exception\n\nImplement `safeRead(String path)` using try-with-resources.", "sampleInput": "safeRead(\"missing.txt\")", "sampleOutput": "throws FileNotFoundException (resource still closed)"},
    6: {"description": "Implement `nullSafeChain(User user)` that safely navigates `user.getAddress().getCity().toUpperCase()` without NPE using `Optional` chaining.\n\n**Example 1:**\nnullSafeChain(User{address: Address{city: \"london\"}}) => \"LONDON\"\n\n**Example 2:**\nnullSafeChain(User{address: null}) => \"UNKNOWN\"\n\n**Example 3:**\nnullSafeChain(null) => \"UNKNOWN\"", "sampleInput": "nullSafeChain(User{address=null})", "sampleOutput": "\"UNKNOWN\""},
    7: {"description": "Implement `retryWithBackoff(Supplier<T> operation, int maxAttempts)` that retries on exception with exponential backoff (100ms, 200ms, 400ms...).\n\n**Example:**\nretryWithBackoff(() -> callFlakyAPI(), 3)\n=> attempt 1: fails\n=> waits 100ms, attempt 2: fails\n=> waits 200ms, attempt 3: succeeds => returns result\n\nIf all attempts fail, throws the last exception.\n\n**Key insight:** Exponential backoff prevents thundering herd — each retry waits 2x longer.", "sampleInput": "flaky API, maxAttempts=3, succeeds on 3rd", "sampleOutput": "returns result after 2 retries"},
    8: {"description": "Implement `validateAll(User user)` that collects **all** validation errors instead of failing on the first:\n\n**Example:**\nvalidateAll(User{name=\"\", email=\"bad\", age=-1})\n=> ValidationException{\n     errors: [\"Name required\", \"Invalid email\", \"Age must be positive\"]\n   }\n\n**Key insight:** Don't throw on first error — accumulate all errors in a list and throw once at the end. Much better UX.", "sampleInput": "validateAll(User{name=\"\", email=\"bad\", age=-1})", "sampleOutput": "3 errors collected in one exception"},
    9: {"description": "Lambdas can't throw checked exceptions. Implement `CheckedSupplier<T>` and a wrapper `wrap(CheckedSupplier<T>)` that converts checked exceptions to unchecked:\n\n**Example:**\nSupplier<String> safe = wrap(() -> Files.readString(Path.of(\"file.txt\")));\nsafe.get() // throws RuntimeException wrapping IOException if file missing\n\n**Key insight:** This pattern is common in Stream pipelines where lambdas must not throw checked exceptions.", "sampleInput": "wrap(() -> Files.readString(missingFile)).get()", "sampleOutput": "throws RuntimeException wrapping IOException"},
    10: {"description": "Implement `transfer(Account from, Account to, double amount)` that is transactionally safe: if `to.deposit()` fails after `from.withdraw()`, the withdrawal must be rolled back.\n\n**Example 1:**\nfrom.balance=500, transfer(from, to, 100) succeeds\n=> from.balance=400, to.balance+=100\n\n**Example 2:**\nto.deposit() throws exception\n=> from.balance restored to 500 (rollback)\n\n**Key insight:** Catch the exception, restore original state, then re-throw.", "sampleInput": "transfer fails on deposit", "sampleOutput": "from.balance restored (rollback)"},
    11: {"description": "Implement an **exception translation layer**: catch low-level `SQLException` and re-throw as domain-specific `DataAccessException` with a user-friendly message.\n\n**Example:**\ntry { jdbcCall(); }\ncatch (SQLException e) {\n    throw new DataAccessException(\"Failed to load user\", e);\n}\n\nDataAccessException.getCause() => original SQLException\nDataAccessException.getMessage() => \"Failed to load user\"\n\n**Key insight:** Preserve the cause chain (`super(message, cause)`) — never swallow exceptions.", "sampleInput": "jdbcCall() throws SQLException", "sampleOutput": "throws DataAccessException(cause=SQLException)"},
    12: {"description": "Implement a simple **circuit breaker**: after `N` consecutive failures, the circuit opens and all calls fail-fast without executing. Resets after a timeout.\n\n**States:** CLOSED (normal) -> OPEN (failing fast) -> HALF_OPEN (testing recovery)\n\n**Example:**\ncb = CircuitBreaker(failureThreshold=3, resetTimeoutMs=1000)\nfailure x3 => circuit OPEN\ncb.call(() -> api()) => throws CircuitOpenException (no call made)\nafter 1s => HALF_OPEN, next call attempted", "sampleInput": "3 failures then call()", "sampleOutput": "throws CircuitOpenException"},
    13: {"description": "Build a tree of validation errors with nested causes:\n\n```\nValidationException: Form invalid\n  FieldError: name -> \"Name required\"\n  FieldError: address.city -> \"City too short\"\n  FieldError: address.zip -> \"Invalid zip format\"\n```\n\nImplement `ErrorTree` with nested `FieldError` children. `printTree(0)` renders indented output.\n\n**Example:**\nerrorTree.printTree(0)\n=> \"Form invalid\"\n=> \"  name: Name required\"\n=> \"  address.city: City too short\"", "sampleInput": "errorTree.printTree(0)", "sampleOutput": "Form invalid / name: Name required / ..."},
    14: {"description": "Demonstrate that exceptions from `CompletableFuture` are wrapped in `ExecutionException`. Use `.exceptionally()` to recover gracefully.\n\n**Example:**\nCompletableFuture.supplyAsync(() -> { throw new RuntimeException(\"fail\"); })\n    .exceptionally(e -> \"default\")\n    .get() => \"default\"\n\n**Key insight:** `.exceptionally(fn)` catches the wrapped exception and returns a fallback — equivalent of catch for async pipelines.", "sampleInput": "supplyAsync(throw) .exceptionally(e->\"default\") .get()", "sampleOutput": "\"default\""},
    15: {"description": "Implement a builder where `build()` is deferred and validation only runs at build time — not at each setter call.\n\n**Example 1:**\nnew OrderBuilder().item(\"book\",10).shipping(\"123 Main\").build() => Order (valid)\n\n**Example 2:**\nnew OrderBuilder().shipping(\"123 Main\").build()\n=> throws IllegalStateException(\"At least one item required\")\n\n**Key insight:** Deferred validation collects all errors in `build()` — avoids premature failure on partially-constructed objects.", "sampleInput": "OrderBuilder.shipping(\"123 Main\").build() (no items)", "sampleOutput": "throws IllegalStateException(\"At least one item required\")"},
    16: {"description": "Implement a multi-step transaction where each step can fail and prior steps must roll back:\n\nSteps: deductInventory -> chargePayment -> sendConfirmation\n\n**Example:**\nchargeFails => deductInventory rolled back\nsendConfirmationFails => both deductInventory and chargePayment rolled back\n\nImplement using a `Deque<Runnable>` rollback stack — push compensating action after each successful step.", "sampleInput": "step 2 fails", "sampleOutput": "step 1 rolled back; exception rethrown"},
    17: {"description": "Create a REST API exception hierarchy:\n- `ApiException(int statusCode, String message)` — base\n- `NotFoundException extends ApiException` — 404\n- `BadRequestException extends ApiException` — 400\n- `UnauthorizedException extends ApiException` — 401\n\n**Example:**\nthrow new NotFoundException(\"User 42 not found\")\n=> exception.getStatusCode() = 404\n=> exception.getMessage() = \"User 42 not found\"", "sampleInput": "new NotFoundException(\"User 42 not found\")", "sampleOutput": "statusCode=404, message=\"User 42 not found\""},
    18: {"description": "Implement `filterStackTrace(Throwable t, String... packagePrefixes)` that returns a new exception with only stack frames matching the given packages — removes framework noise.\n\n**Example:**\ne = new RuntimeException()\ne.getStackTrace() has 20 frames (Spring, JDK, etc.)\nfilterStackTrace(e, \"com.myapp\") => exception with only myapp frames\n\n**Key insight:** `t.setStackTrace(filtered)` replaces the trace — useful for cleaner logs in production.", "sampleInput": "filterStackTrace(e, \"com.myapp\")", "sampleOutput": "stack frames with only com.myapp prefix"},
    19: {"description": "Implement `SerializableException` that can be serialized to JSON and reconstructed:\n\n**Example:**\nSerializableException e = new SerializableException(\"Not found\", 404);\nString json = e.toJson();\n// => {\"message\":\"Not found\",\"code\":404,\"type\":\"SerializableException\"}\nSerializableException restored = SerializableException.fromJson(json);\nrestored.getMessage() => \"Not found\"\nrestored.getCode() => 404", "sampleInput": "toJson() then fromJson()", "sampleOutput": "{\"message\":\"Not found\",\"code\":404}"},
    20: {"description": "Implement a global `ExceptionHandlerRegistry` that maps exception types to handlers:\n\n**Example:**\nregistry.register(NotFoundException.class, e -> log(\"404: \" + e.getMessage()));\nregistry.register(RuntimeException.class, e -> log(\"Runtime: \" + e.getMessage()));\nregistry.handle(new NotFoundException(\"missing\")) => calls NotFoundException handler\nregistry.handle(new IllegalArgumentException(\"bad\")) => falls back to RuntimeException handler\n\n**Key insight:** Walk the class hierarchy to find the most specific registered handler.", "sampleInput": "handle(new NotFoundException(\"missing\"))", "sampleOutput": "\"404: missing\""},
}

updated = 0
for topic in data['topics']:
    for p in topic.get('problems', []):
        o = p['displayOrder']
        if o in improvements:
            p['description'] = improvements[o]['description']
            p['sampleInput'] = improvements[o]['sampleInput']
            p['sampleOutput'] = improvements[o]['sampleOutput']
            updated += 1
with open(f, 'w', encoding='utf-8') as fh: json.dump(data, fh, indent=2, ensure_ascii=False)
print(f"B18 updated: {updated} problems")
