import json
f = 'C:/Dev/devlearner/devlearner/learning-system/src/main/resources/seeds/B04-java-operators.json'
with open(f, encoding='utf-8') as fh: data = json.load(fh)

improvements = {
    1: {"description": "Return `true` if `n` is a power of two using bit manipulation.\n\n**Example 1:**\nisPowerOfTwo(16) => true (10000 in binary — exactly one bit set)\nisPowerOfTwo(18) => false (10010 — two bits)\nisPowerOfTwo(1) => true\nisPowerOfTwo(0) => false\n\n**Key insight:** A power of two has exactly one set bit. `n & (n-1) == 0` clears the lowest set bit — if result is 0, only one bit was set.", "sampleInput": "isPowerOfTwo(16)", "sampleOutput": "true"},
    2: {"description": "Count the number of set bits (1s) in an integer's binary representation.\n\n**Example 1:**\ncountBits(7) => 3 (111 in binary)\ncountBits(0) => 0\ncountBits(255) => 8\ncountBits(Integer.MAX_VALUE) => 31\n\n**Key insight:** `n & (n-1)` clears the lowest set bit. Loop until n==0, counting iterations. Or use `Integer.bitCount(n)`.", "sampleInput": "countBits(7)", "sampleOutput": "3"},
    3: {"description": "Swap two integers without a temporary variable using XOR.\n\n**Example:**\nint a = 5, b = 10;\na ^= b; b ^= a; a ^= b;\na => 10, b => 5\n\n**Warning:** `a ^= b ^= a ^= b;` — undefined behaviour in C/C++, but safe in Java (left-to-right evaluation).\n\n**Key insight:** XOR is its own inverse: `(a^b)^b == a`. Three XOR swaps exchange values without extra memory.", "sampleInput": "a=5, b=10; XOR swap", "sampleOutput": "a=10, b=5"},
    4: {"description": "Use a ternary chain to classify a score as A/B/C/D/F:\n\n**Example:**\ngetGrade(95) => 'A'\ngetGrade(82) => 'B'\ngetGrade(73) => 'C'\ngetGrade(61) => 'D'\ngetGrade(55) => 'F'\n\nImplement using nested ternary: `score>=90 ? 'A' : score>=80 ? 'B' : ...`\n\n**Key insight:** Ternary is right-associative — each else clause can itself be a ternary expression.", "sampleInput": "getGrade(82)", "sampleOutput": "'B'"},
    5: {"description": "Demonstrate Java's short-circuit evaluation with `&&` and `||`:\n\n```java\nboolean result = (x != 0) && (10 / x > 1); // safe: RHS not evaluated if x==0\nboolean any = isEmpty() || checkDefault(); // checkDefault() not called if already empty\n```\n\nImplement `shortCircuitDemo()` with a `sideEffect()` method that logs when called, then verify it's not called when short-circuited.", "sampleInput": "(false && sideEffect())", "sampleOutput": "sideEffect() NOT called"},
    6: {"description": "Implement a permission system using bit flags:\n\n```java\nstatic final int READ    = 1 << 0; // 001\nstatic final int WRITE   = 1 << 1; // 010\nstatic final int EXECUTE = 1 << 2; // 100\n\nint userPerms = READ | WRITE; // 011\nhasPermission(userPerms, READ) => true\nhasPermission(userPerms, EXECUTE) => false\ngrantPermission(userPerms, EXECUTE) => 111\nrevokePermission(userPerms, WRITE) => 001\n```", "sampleInput": "hasPermission(READ|WRITE, EXECUTE)", "sampleOutput": "false"},
    7: {"description": "Evaluate arithmetic expressions respecting operator precedence using a stack-based algorithm.\n\n**Example:**\nevaluate(\"3 + 4 * 2\") => 11\nevaluate(\"(3 + 4) * 2\") => 14\nevaluate(\"10 / 2 + 3 - 1\") => 7\n\n**Key insight:** Shunting-yard algorithm converts infix to postfix. `*` and `/` have higher precedence than `+` and `-`.", "sampleInput": "evaluate(\"3 + 4 * 2\")", "sampleOutput": "11"},
    8: {"description": "Reverse all 32 bits of an integer.\n\n**Example:**\nreverseBits(0b00000010100101000001111010011100) => 0b00111001011110000010100101000000\nreverseBits(43261596) => 964176192\nreverseBits(0) => 0\n\n**Key insight:** Loop 32 times: take the LSB of n (`n & 1`), shift into result from MSB side. `result |= (n & 1); result <<= 1; n >>= 1;`", "sampleInput": "reverseBits(43261596)", "sampleOutput": "964176192"},
    9: {"description": "Find the one number that appears only once in an array where every other number appears exactly twice. Use XOR.\n\n**Example 1:**\nsingleNumber([2,2,1]) => 1\nsingleNumber([4,1,2,1,2]) => 4\n\n**Key insight:** XOR of a number with itself is 0; XOR with 0 is itself. XOR all elements — duplicates cancel out, leaving the unique number.", "sampleInput": "[4,1,2,1,2]", "sampleOutput": "4"},
    10: {"description": "Implement addition without using `+` or `-` operators — use only bitwise operators.\n\n**Example:**\nadd(3, 5) => 8\nadd(-1, 1) => 0\nadd(15, 16) => 31\n\n**Key insight:**\n- `a ^ b` gives sum without carry\n- `(a & b) << 1` gives carry\n- Repeat until no carry: `while(b != 0) { carry = (a & b) << 1; a = a ^ b; b = carry; }`", "sampleInput": "add(3, 5)", "sampleOutput": "8"},
    11: {"description": "Use `BigDecimal` operators (add, subtract, multiply, divide) to simulate exact decimal arithmetic:\n\n**Example:**\nBigDecimal price = new BigDecimal(\"19.99\");\nBigDecimal tax = new BigDecimal(\"0.08\");\nBigDecimal total = price.multiply(BigDecimal.ONE.add(tax)).setScale(2, HALF_UP);\n=> 21.59\n\n**Key insight:** `BigDecimal` has no overloaded operators in Java — use `.add()`, `.multiply()`, etc. Always specify scale for division.", "sampleInput": "19.99 * 1.08", "sampleOutput": "21.59"},
    12: {"description": "Implement a modular arithmetic ring: all operations wrap around modulus N.\n\n**Example:**\nRing ring = new Ring(7);\nring.add(5, 4) => 2 (9 mod 7)\nring.multiply(3, 4) => 5 (12 mod 7)\nring.power(2, 10) => 2 (1024 mod 7)\nring.inverse(3) => 5 (3*5=15=1 mod 7)\n\n**Key insight:** `((a % n) + n) % n` handles negative numbers correctly.", "sampleInput": "Ring(7).add(5, 4)", "sampleOutput": "2"},
    13: {"description": "Validate a Sudoku board using bitmasked row/column/box tracking.\n\n**Example:**\nint[] rowMask = new int[9];\nFor each cell (r,c) with value v:\nif (rowMask[r] & (1<<v)) != 0 => duplicate in row, invalid!\nrowMask[r] |= (1<<v);\n\nisValidSudoku(board) => true / false\n\n**Key insight:** Bit N is set if value N has been seen. `& (1<<v)` checks; `|= (1<<v)` marks. 9 ints replace 9 HashSets.", "sampleInput": "valid 9x9 Sudoku board", "sampleOutput": "true"},
    14: {"description": "Implement integer multiplication using only bit shifts and addition.\n\n**Example:**\nmultiply(6, 7) => 42\nmultiply(3, 0) => 0\nmultiply(-3, 4) => -12\n\n**Key insight:** `a * b = a * (sum of powers of 2 in b)`. For each set bit at position i in b, add `a << i` to result. This is how hardware multipliers work.", "sampleInput": "multiply(6, 7)", "sampleOutput": "42"},
    15: {"description": "Predict the output of tricky operator precedence expressions:\n\n**Examples:**\n`2 + 3 * 4` => 14 (not 20)\n`10 - 3 - 2` => 5 (left-to-right)\n`2 << 1 + 1` => 8 (+ has higher precedence than <<)\n`true || false && false` => true (&& binds tighter than ||)\n\nImplement `evaluateTrap(String expr)` returning the correct result.", "sampleInput": "\"2 << 1 + 1\"", "sampleOutput": "8"},
    16: {"description": "Calculate the Hamming distance between two integers (number of positions where bits differ).\n\n**Example 1:**\nhammingDistance(1, 4) => 2 (1=001, 4=100, differ at 2 positions)\nhammingDistance(3, 1) => 1 (3=011, 1=001, differ at 1 position)\nhammingDistance(0, 0) => 0\n\n**Key insight:** XOR flips bits where they differ. `Integer.bitCount(a ^ b)` counts the differing positions.", "sampleInput": "hammingDistance(1, 4)", "sampleOutput": "2"},
    17: {"description": "Generate the n-bit Gray code sequence where consecutive values differ by exactly one bit.\n\n**Example:**\ngrayCode(2) => [0,1,3,2] (00,01,11,10)\ngrayCode(3) => [0,1,3,2,6,7,5,4] (8 values)\n\n**Key insight:** The Gray code for i is `i ^ (i >> 1)`. No need to generate iteratively — direct formula.", "sampleInput": "grayCode(3)", "sampleOutput": "[0,1,3,2,6,7,5,4]"},
    18: {"description": "Find the pair of numbers in an array whose AND value is maximum.\n\n**Example:**\nmaxANDPair([4,8,6,2]) => 6 (4&6=4, 8&6=0... try all: 4&8=0, 4&6=4, 8&6=0, 6&2=2... max=4)\nActually: findMaxAND([1,2,3,4,5]) => 4 (4&5=4)\n\n**Key insight:** Try all pairs O(n^2), or greedy from MSB: check if keeping bit i gives a valid pair.", "sampleInput": "findMaxAND([1,2,3,4,5])", "sampleOutput": "4"},
    19: {"description": "Solve 'Decode Ways' using bitmask DP: count the number of ways to decode a digit string to letters (1->A, ..., 26->Z).\n\n**Example:**\ndecodeWays(\"12\") => 2 (\"AB\" or \"L\")\ndecodeWays(\"226\") => 3 (\"BBF\", \"BZ\", \"VF\")\ndecodeWays(\"06\") => 0 (invalid leading zero)\n\n**Key insight:** `dp[i] = dp[i-1]` (single digit) + `dp[i-2]` (two-digit, if 10-26). DP with bitmask optimizes space to O(1).", "sampleInput": "decodeWays(\"226\")", "sampleOutput": "3"},
    20: {"description": "In an array of n+2 integers where numbers 1..n each appear once except one number appears twice and one is missing, find both using XOR.\n\n**Example:**\nfindMissingAndDuplicate([1,2,2,4]) => {duplicate:2, missing:3}\nfindMissingAndDuplicate([3,1,3]) => {duplicate:3, missing:2}\n\n**Key insight:** XOR all elements and all 1..n. The result is `missing ^ duplicate`. Separate them using the lowest set bit.", "sampleInput": "[1,2,2,4]", "sampleOutput": "{duplicate:2, missing:3}"},
}

updated = 0
for topic in data['topics']:
    for p in topic.get('problems', []):
        o = p['displayOrder']
        if o in improvements:
            p['description'] = improvements[o]['description']
            p['sampleInput'] = improvements[o]['sampleInput']
            p['sampleOutput'] = improvements[o]['sampleOutput']
            updated += 1
with open(f, 'w', encoding='utf-8') as fh: json.dump(data, fh, indent=2, ensure_ascii=False)
print(f"B04 updated: {updated} problems")
