import json
f = 'C:/Dev/devlearner/devlearner/learning-system/src/main/resources/seeds/B02-compilation-flow.json'
with open(f, encoding='utf-8') as fh: data = json.load(fh)

improvements = {
    1: {"description": "For each code snippet, predict whether it compiles or produces a compile error and why:\n\n1. `int x = 3.14;` => error (double to int)\n2. `final int N = 5; int[] arr = new int[N];` => compiles (compile-time constant)\n3. `String s = null; s.length();` => compiles (runtime NPE, not compile error)\n\nImplement `predictCompilation(String[] snippets)` returning `\"OK\"` or `\"ERROR: reason\"`.", "sampleInput": "[\"int x = 3.14;\", \"final int N=5; int[] arr=new int[N];\"]", "sampleOutput": "[\"ERROR: incompatible types\", \"OK\"]"},
    2: {"description": "Every `.class` file starts with the magic number `0xCAFEBABE`. Read a class file and verify it.\n\n**Example:**\nbyte[] bytes = Files.readAllBytes(Path.of(\"Hello.class\"));\nString magic = String.format(\"%02X%02X%02X%02X\", bytes[0],bytes[1],bytes[2],bytes[3]);\n=> \"CAFEBABE\"\n\nAlso read the major version (bytes 6-7) to determine Java version: 65 = Java 21, 61 = Java 17.", "sampleInput": "read Hello.class first 8 bytes", "sampleOutput": "magic=CAFEBABE, major=65 (Java 21)"},
    3: {"description": "Use `javax.tools.JavaCompiler` to compile Java source code at runtime from a String.\n\n**Example:**\nString src = \"public class Greeter { public String greet() { return \\\"Hello!\\\"; } }\";\nClass<?> cls = compileAndLoad(src, \"Greeter\");\ncls.getMethod(\"greet\").invoke(cls.newInstance()) => \"Hello!\"\n\n**Key insight:** `ToolProvider.getSystemJavaCompiler()` gives access to javac programmatically — used in IDEs, build tools, and live-coding environments.", "sampleInput": "compileAndLoad(Greeter source)", "sampleOutput": "\"Hello!\""},
    4: {"description": "Use `javap -verbose` output or ASM library to count the constant pool size of a compiled class.\n\n**Example:**\nanalyzeClass(\"Hello.class\")\n=> Constant pool size: 42\n=> Methods: 2\n=> Fields: 1\n\nParse the class file bytes: constant pool count is at bytes 8-9 (big-endian short).", "sampleInput": "analyzeClass(\"Hello.class\")", "sampleOutput": "constant pool size: 42, methods: 2"},
    5: {"description": "Demonstrate the difference between `@Retention(SOURCE)`, `CLASS`, and `RUNTIME` annotations:\n\n- SOURCE: only in source, stripped by javac (e.g. `@Override`)\n- CLASS: in .class file but not accessible at runtime\n- RUNTIME: accessible via reflection at runtime\n\n**Example:**\n@MyRuntime // RetentionPolicy.RUNTIME\nclass Foo {}\nFoo.class.isAnnotationPresent(MyRuntime.class) => true\nFoo.class.isAnnotationPresent(MyClass.class) => false", "sampleInput": "isAnnotationPresent(MyRuntime.class)", "sampleOutput": "true (RUNTIME); false (CLASS retention)"},
    6: {"description": "Show that `javac` eliminates dead code — unreachable branches are not compiled into bytecode:\n\n```java\nfinal boolean DEBUG = false;\nif (DEBUG) { System.out.println(\"debug\"); } // removed by compiler\n```\n\nVerify using `javap -c` that the `if` block is absent from bytecode.\n\nImplement `hasDeadCode(Class<?> cls, String methodName)` returning false for the optimized version.", "sampleInput": "hasDeadCode(OptimizedClass.class, \"run\")", "sampleOutput": "false (dead code eliminated)"},
    7: {"description": "Implement a simple **lexer (tokenizer)** that splits Java-like source code into tokens: KEYWORD, IDENTIFIER, NUMBER, OPERATOR, STRING, WHITESPACE.\n\n**Example:**\ntokenize(\"int x = 42 + y;\")\n=> [(KEYWORD,\"int\"),(IDENT,\"x\"),(OP,\"=\"),(NUMBER,\"42\"),(OP,\"+\"),(IDENT,\"y\"),(OP,\";\")]", "sampleInput": "\"int x = 42 + y;\"", "sampleOutput": "[(KEYWORD,int),(IDENT,x),(OP,=),(NUMBER,42),(OP,+),(IDENT,y),(OP,;)]"},
    8: {"description": "Build an AST node hierarchy for arithmetic expressions: `BinaryOp(left, op, right)`, `NumberLiteral(int value)`, `VariableRef(String name)`.\n\n**Example:**\n// Represents: (3 + x) * 2\nExpr ast = new BinaryOp(\n    new BinaryOp(new NumberLiteral(3), \"+\", new VariableRef(\"x\")),\n    \"*\",\n    new NumberLiteral(2));\nast.toString() => \"((3 + x) * 2)\"\nast.evaluate(Map.of(\"x\", 4)) => 14", "sampleInput": "((3 + x) * 2) with x=4", "sampleOutput": "14"},
    9: {"description": "Build a dependency graph for incremental compilation: only recompile classes that depend on a changed class.\n\n**Example:**\ndeps: A->B, A->C, B->D, C->D\nchanged: D\naffected(D) => [B, C, A] (transitive dependents)\n\nImplement `findAffected(String changedClass, Map<String,Set<String>> deps)` using BFS/DFS.", "sampleInput": "changed=D, deps={A->[B,C], B->[D], C->[D]}", "sampleOutput": "[B, C, A]"},
    10: {"description": "Fix indentation in malformed Java source code: detect the current indentation level based on `{` and `}` tokens.\n\n**Example:**\nInput:\n```\npublic class X {\nint x=1;\nif(true){\nx++;\n}\n}\n```\nOutput:\n```\npublic class X {\n    int x=1;\n    if(true){\n        x++;\n    }\n}\n```", "sampleInput": "unindented Java source", "sampleOutput": "properly indented Java source"},
    11: {"description": "Demonstrate Java **type erasure**: generic type information is removed at compile time.\n\n**Example:**\nList<String> strings = new ArrayList<>();\nList<Integer> ints = new ArrayList<>();\nstrings.getClass() == ints.getClass() => true (both are just ArrayList)\n\nBut with a type token:\nclass TypeToken<T> { Type t = ((ParameterizedType)getClass().getGenericSuperclass()).getActualTypeArguments()[0]; }\nnew TypeToken<String>(){}.t => String.class\n\nImplement `getGenericType(List<?> list)` using reflection.", "sampleInput": "new ArrayList<String>().getClass() == new ArrayList<Integer>().getClass()", "sampleOutput": "true (type erasure)"},
    12: {"description": "Use `javax.tools.DiagnosticCollector` to collect compile errors from source code and return structured error information.\n\n**Example:**\ncompileWithDiagnostics(\"class X { int x = \\\"bad\\\"; }\")\n=> [Diagnostic{kind=ERROR, line=1, message=\"incompatible types: String cannot be converted to int\"}]", "sampleInput": "compile \"class X { int x = \\\"bad\\\"; }\"", "sampleOutput": "ERROR line 1: incompatible types"},
    13: {"description": "Use sealed classes + pattern matching switch to exhaustively handle a shape hierarchy:\n\n```java\nsealed interface Shape permits Circle, Rectangle, Triangle {}\nrecord Circle(double r) implements Shape {}\nrecord Rectangle(double w, double h) implements Shape {}\nrecord Triangle(double b, double height) implements Shape {}\n\ndouble area(Shape s) {\n    return switch(s) {\n        case Circle c -> Math.PI*c.r()*c.r();\n        case Rectangle r -> r.w()*r.h();\n        case Triangle t -> 0.5*t.b()*t.height();\n    };\n}\n```\narea(new Circle(5)) => 78.54", "sampleInput": "area(new Circle(5))", "sampleOutput": "78.54"},
    14: {"description": "Analyze a `.class` file and count the frequency of each bytecode instruction using ASM or raw byte parsing.\n\n**Example:**\nanalyzeInstructions(\"Fibonacci.class\")\n=> {ILOAD:15, ISTORE:8, IADD:3, IRETURN:1, IF_ICMPLT:2, ...}\n\nTop 3 most frequent instructions in typical Java code: `aload_0`, `invokespecial`, `return`.", "sampleInput": "analyzeInstructions(\"Fibonacci.class\")", "sampleOutput": "{ILOAD:15, ISTORE:8, IADD:3, ...}"},
    15: {"description": "Show what the compiler generates for a `record` by implementing an equivalent class manually:\n\n```java\nrecord Point(int x, int y) {}\n// Desugars to:\nfinal class Point {\n    private final int x, y;\n    Point(int x, int y) { this.x=x; this.y=y; }\n    int x() { return x; } int y() { return y; }\n    // equals, hashCode, toString auto-generated\n}\n```\n\nImplement `Point` manually and verify it behaves identically to the record.", "sampleInput": "new Point(3,4).x()", "sampleOutput": "3"},
    16: {"description": "Show what the compiler generates for a lambda — desugar it to an anonymous class:\n\n**Lambda:**\nRunnable r = () -> System.out.println(\"hello\");\n\n**Desugared:**\nRunnable r = new Runnable() { public void run() { System.out.println(\"hello\"); } };\n\n**Example:**\nRunnable lambda = () -> System.out.println(\"lambda\");\nlambda.run() => \"lambda\"\nRunnable anon = new Runnable() { public void run() { System.out.println(\"anon\"); } };\nanon.run() => \"anon\"", "sampleInput": "(() -> print(\"hello\")).run()", "sampleOutput": "\"hello\""},
    17: {"description": "Minify Java source code by removing comments and excess whitespace while preserving semantics.\n\n**Example:**\nInput:\n```java\n// This adds two numbers\npublic int add(int a,   int b) {\n    return a + b; // simple\n}\n```\nOutput: `public int add(int a,int b){return a+b;}`", "sampleInput": "public int add(int a,   int b) { return a + b; }", "sampleOutput": "public int add(int a,int b){return a+b;}"},
    18: {"description": "Parse a Java method signature string into its components: visibility, return type, name, parameter types.\n\n**Example:**\nparseSignature(\"public static List<String> findAll(int limit, String prefix)\")\n=> {visibility:\"public\", modifiers:[\"static\"], returnType:\"List<String>\", name:\"findAll\", params:[(\"int\",\"limit\"),(\"String\",\"prefix\")]}", "sampleInput": "\"public static List<String> findAll(int limit, String prefix)\"", "sampleOutput": "{name:findAll, return:List<String>, params:[(int,limit),(String,prefix)]}"},
    19: {"description": "Build a recursive descent parser for simple arithmetic expressions supporting `+`, `-`, `*`, `/`, parentheses, and integer literals.\n\n**Example:**\nparse(\"3 + 4 * 2\") => 11 (operator precedence: * before +)\nparse(\"(3 + 4) * 2\") => 14\nparse(\"10 / 2 - 1\") => 4\n\n**Key insight:** Recursive descent: `expr` calls `term`, `term` calls `factor`. Precedence is encoded in the grammar.", "sampleInput": "\"3 + 4 * 2\"", "sampleOutput": "11"},
    20: {"description": "Simulate the full compilation pipeline: source string -> tokenize -> parse to AST -> evaluate.\n\n**Example:**\nCompiler c = new Compiler();\nc.compile(\"let x = 5; let y = 3; return x * y + 2;\");\nc.run() => 17\n\nImplement: `Lexer` (tokenize) -> `Parser` (build AST) -> `Interpreter` (evaluate AST).", "sampleInput": "\"let x=5; let y=3; return x*y+2;\"", "sampleOutput": "17"},
}

updated = 0
for topic in data['topics']:
    for p in topic.get('problems', []):
        o = p['displayOrder']
        if o in improvements:
            p['description'] = improvements[o]['description']
            p['sampleInput'] = improvements[o]['sampleInput']
            p['sampleOutput'] = improvements[o]['sampleOutput']
            updated += 1
with open(f, 'w', encoding='utf-8') as fh: json.dump(data, fh, indent=2, ensure_ascii=False)
print(f"B02 updated: {updated} problems")
