import json
f = 'C:/Dev/devlearner/devlearner/learning-system/src/main/resources/seeds/B05-control-flow.json'
with open(f, encoding='utf-8') as fh: data = json.load(fh)

improvements = {
    1: {"description": "Print numbers 1 to n. For multiples of 3 print \"Fizz\", for multiples of 5 print \"Buzz\", for multiples of both print \"FizzBuzz\".\n\n**Example (n=15):**\n1, 2, Fizz, 4, Buzz, Fizz, 7, 8, Fizz, Buzz, 11, Fizz, 13, 14, FizzBuzz\n\nReturn as `List<String>`.", "sampleInput": "fizzBuzz(15)", "sampleOutput": "[\"1\",\"2\",\"Fizz\",\"4\",\"Buzz\",\"Fizz\",\"7\",\"8\",\"Fizz\",\"Buzz\",\"11\",\"Fizz\",\"13\",\"14\",\"FizzBuzz\"]"},
    2: {"description": "Count the number of digits in a non-negative integer `n` without converting to a String.\n\n**Example 1:**\ncountDigits(0) => 1\ncountDigits(9) => 1\ncountDigits(12345) => 5\ncountDigits(1000000) => 7\n\n**Key insight:** Divide by 10 until n == 0, counting iterations. Handle n=0 as a special case (has 1 digit).", "sampleInput": "countDigits(12345)", "sampleOutput": "5"},
    3: {"description": "Repeatedly sum the digits of a number until a single digit remains.\n\n**Example 1:**\ndigitalRoot(493) => 7 (4+9+3=16 -> 1+6=7)\ndigitalRoot(9999) => 9\ndigitalRoot(0) => 0\n\n**Key insight:** Mathematical shortcut: `digitalRoot(n) = 1 + (n-1) % 9` for n>0. Or iterate: keep summing digits until single digit.", "sampleInput": "digitalRoot(493)", "sampleOutput": "7"},
    4: {"description": "Reverse the digits of an integer, handling negative numbers and trailing zeros.\n\n**Example 1:**\nreverse(123) => 321\nreverse(-456) => -654\nreverse(120) => 21 (trailing zero dropped)\nreverse(1534236469) => 0 (overflow: result > Integer.MAX_VALUE)\n\n**Key insight:** Extract digits with `% 10` and `/ 10`. Check for overflow before final multiplication.", "sampleInput": "reverse(123)", "sampleOutput": "321"},
    5: {"description": "Print a right triangle pattern of `*` with n rows using nested loops:\n\n**Example (n=4):**\n```\n*\n**\n***\n****\n```\n\nReturn as `List<String>`, one string per row.", "sampleInput": "rightTriangle(4)", "sampleOutput": "[\"*\",\"**\",\"***\",\"****\"]"},
    6: {"description": "Find the first non-repeating character in a string and return its index. Return -1 if none.\n\n**Example 1:**\nfirstUnique(\"leetcode\") => 0 ('l' appears once)\nfirstUnique(\"loveleetcode\") => 2 ('v')\nfirstUnique(\"aabb\") => -1\n\n**Key insight:** Two passes: first build frequency map, then scan left-to-right for first char with count=1.", "sampleInput": "firstUnique(\"leetcode\")", "sampleOutput": "0"},
    7: {"description": "Count how many steps the **Collatz sequence** takes to reach 1 starting from n:\n- If n is even: n = n/2\n- If n is odd: n = 3n + 1\n\n**Example:**\ncollatzSteps(6) => 8 (6->3->10->5->16->8->4->2->1)\ncollatzSteps(1) => 0\ncollatzSteps(27) => 111\n\n**Key insight:** Collatz conjecture — always reaches 1 (unproven for all n, but true for all tested n).", "sampleInput": "collatzSteps(6)", "sampleOutput": "8"},
    8: {"description": "Given an array of non-negative integers where each element represents the max jump length at that position, determine if you can reach the last index.\n\n**Example 1:**\ncanJump([2,3,1,1,4]) => true\ncanJump([3,2,1,0,4]) => false (stuck at index 3)\n\n**Key insight:** Track `maxReach` — the farthest index reachable. If current index > maxReach at any point, return false.", "sampleInput": "[3,2,1,0,4]", "sampleOutput": "false"},
    9: {"description": "Return elements of an `m x n` matrix in **spiral order** (right -> down -> left -> up, repeat).\n\n**Example:**\nInput: [[1,2,3],[4,5,6],[7,8,9]]\nOutput: [1,2,3,6,9,8,7,4,5]\n\n**Key insight:** Maintain four boundaries (top, bottom, left, right). After each direction pass, shrink the corresponding boundary.", "sampleInput": "[[1,2,3],[4,5,6],[7,8,9]]", "sampleOutput": "[1,2,3,6,9,8,7,4,5]"},
    10: {"description": "Find the length of the longest consecutive sequence in an unsorted array.\n\n**Example 1:**\nlongestConsecutive([100,4,200,1,3,2]) => 4 ([1,2,3,4])\nlongestConsecutive([0,3,7,2,5,8,4,6,0,1]) => 9\n\n**Key insight:** Add all to a `HashSet`. For each n where `n-1` is NOT in the set (start of sequence), count how far the sequence extends. O(n) overall.", "sampleInput": "[100,4,200,1,3,2]", "sampleOutput": "4"},
    11: {"description": "Use Java's `switch` expression (Java 14+) to convert Roman numerals to integers.\n\n**Example:**\nromanToInt(\"III\") => 3\nromanToInt(\"IV\") => 4\nromanToInt(\"IX\") => 9\nromanToInt(\"LVIII\") => 58\nromanToInt(\"MCMXCIV\") => 1994\n\n**Key insight:** If current symbol < next symbol, subtract it (IV=4); otherwise add it. Use `switch` expression for clean symbol-to-value mapping.", "sampleInput": "romanToInt(\"MCMXCIV\")", "sampleOutput": "1994"},
    12: {"description": "Print all prime numbers up to n using the Sieve of Eratosthenes.\n\n**Example:**\nprimesUpTo(20) => [2,3,5,7,11,13,17,19]\nprimesUpTo(10) => [2,3,5,7]\n\n**Key insight:** Mark composites by crossing off multiples of each prime p starting from p^2. O(n log log n) time.", "sampleInput": "primesUpTo(20)", "sampleOutput": "[2,3,5,7,11,13,17,19]"},
    13: {"description": "Search for a word in a 2D character grid where the word can go in any of 4 or 8 directions. Use labeled break to exit nested loops on find.\n\n**Example:**\ngrid = [[A,B,C],[D,E,F],[G,H,I]]\nwordSearch(grid, \"BEH\") => true (B->E->H, going down)\nwordSearch(grid, \"CEG\") => false\n\n**Key insight:** Labeled `break outer;` exits multiple nested loops at once — cleaner than a flag variable.", "sampleInput": "wordSearch([[A,B,C],[D,E,F],[G,H,I]], \"BEH\")", "sampleOutput": "true"},
    14: {"description": "Implement a `RangeIterator(int start, int end, int step)` that implements `Iterator<Integer>`.\n\n**Example:**\nIterator<Integer> it = new RangeIterator(1, 10, 2);\nwhile(it.hasNext()) System.out.print(it.next() + \" \");\n=> 1 3 5 7 9\n\nRangeIterator(0, 5, 1) => 0 1 2 3 4\n\n**Key insight:** `hasNext()` checks if current < end; `next()` returns current then advances by step.", "sampleInput": "RangeIterator(1, 10, 2)", "sampleOutput": "[1,3,5,7,9]"},
    15: {"description": "Validate balanced brackets using a `switch` statement to classify each character.\n\n**Example:**\nisBalanced(\"()[]{}\") => true\nisBalanced(\"([)]\") => false\nisBalanced(\"{[()]}\") => true\nisBalanced(\"(\") => false\n\n**Key insight:** Push opening brackets onto a stack; on closing bracket, pop and check match using `switch`.", "sampleInput": "isBalanced(\"{[()]}\")", "sampleOutput": "true"},
    16: {"description": "Detect a cycle in a linked list using **Floyd's Cycle Detection** (fast and slow pointers).\n\n**Example:**\nhasCycle(1->2->3->4->2 cycle) => true\nhasCycle(1->2->3->null) => false\n\n**Key insight:** Slow pointer moves 1 step; fast pointer moves 2 steps. If they meet, there's a cycle. If fast reaches null, no cycle.", "sampleInput": "hasCycle(1->2->3->4->2 cycle)", "sampleOutput": "true"},
    17: {"description": "Implement a recursive descent parser that evaluates simple math expressions with `+`, `-`, `*`, `/`, and parentheses.\n\n**Grammar:**\nexpr = term (('+' | '-') term)*\nterm = factor (('*' | '/') factor)*\nfactor = number | '(' expr ')'\n\n**Example:**\nevaluate(\"2*(3+4)\") => 14\nevaluate(\"10-2*3\") => 4\nevaluate(\"(1+2)*(3+4)\") => 21", "sampleInput": "evaluate(\"2*(3+4)\")", "sampleOutput": "14"},
    18: {"description": "Count the number of solutions to the **N-Queens problem** using backtracking with pruning.\n\n**Example:**\nnQueens(4) => 2\nnQueens(8) => 92\nnQueens(1) => 1\n\n**Key insight:** For each row, try each column. Use three sets (columns, diagonals, anti-diagonals) to check validity in O(1). Prune early if any set conflicts.", "sampleInput": "nQueens(4)", "sampleOutput": "2"},
    19: {"description": "Implement a traffic light state machine that cycles STOP -> GO -> SLOW -> STOP using enums and switch.\n\n**Example:**\nTrafficLight light = new TrafficLight();\nlight.getState() => STOP\nlight.next() => GO\nlight.next() => SLOW\nlight.next() => STOP (back to start)\n\n**Key insight:** `switch(currentState)` returns the next state — clean state transitions without if/else chains.", "sampleInput": "STOP.next().next().next()", "sampleOutput": "STOP"},
    20: {"description": "Find the minimum path sum from top-left to bottom-right of a grid, moving only right or down. Use dynamic programming.\n\n**Example 1:**\nminPathSum([[1,3,1],[1,5,1],[4,2,1]]) => 7 (1->3->1->1->1)\n\n**Example 2:**\nminPathSum([[1,2,3],[4,5,6]]) => 12 (1->2->3->6)\n\n**Key insight:** `dp[i][j] = grid[i][j] + min(dp[i-1][j], dp[i][j-1])`. First row and column have only one direction.", "sampleInput": "[[1,3,1],[1,5,1],[4,2,1]]", "sampleOutput": "7"},
}

updated = 0
for topic in data['topics']:
    for p in topic.get('problems', []):
        o = p['displayOrder']
        if o in improvements:
            p['description'] = improvements[o]['description']
            p['sampleInput'] = improvements[o]['sampleInput']
            p['sampleOutput'] = improvements[o]['sampleOutput']
            updated += 1
with open(f, 'w', encoding='utf-8') as fh: json.dump(data, fh, indent=2, ensure_ascii=False)
print(f"B05 updated: {updated} problems")
