import json
f = 'C:/Dev/devlearner/devlearner/learning-system/src/main/resources/seeds/B21-concurrency-threads.json'
with open(f, encoding='utf-8') as fh: data = json.load(fh)

improvements = {
    1: {"description": "Implement a thread-safe counter using `AtomicInteger` or `synchronized`.\n\n**Example:**\nCounter c = new AtomicCounter();\n10 threads each call increment() 1000 times concurrently.\nc.get() => 10000 (no lost updates)\n\n**Key insight:** `count++` is not atomic — read, increment, write can interleave. `AtomicInteger.incrementAndGet()` is a single atomic CAS operation.", "sampleInput": "10 threads * increment(1000x) each", "sampleOutput": "10000"},
    2: {"description": "Implement producer-consumer using `BlockingQueue<Integer>`. Producer puts items; consumer polls and processes them.\n\n**Example:**\nBlockingQueue<Integer> queue = new LinkedBlockingQueue<>(10);\nproducer puts 1..5\nconsumer takes: [1,2,3,4,5]\n\n**Key insight:** `put()` blocks when queue is full; `take()` blocks when empty — no manual `wait()`/`notify()` needed. `BlockingQueue` handles all coordination.", "sampleInput": "producer puts 1-5, consumer takes all", "sampleOutput": "consumer receives [1,2,3,4,5]"},
    3: {"description": "Demonstrate a deadlock: two threads lock resources in opposite order. Then fix it by enforcing a consistent lock ordering.\n\n**Deadlock:**\nThread1: lock(A) then lock(B)\nThread2: lock(B) then lock(A)\n=> both block forever\n\n**Fix:**\nBoth threads: lock(A) then lock(B) (same order)\n=> no deadlock\n\n**Key insight:** Deadlocks require four conditions (mutual exclusion, hold-and-wait, no-preemption, circular wait). Removing any one prevents deadlock.", "sampleInput": "two threads, opposite lock order", "sampleOutput": "deadlock detected; fix: consistent lock order"},
    4: {"description": "Implement parallel merge sort using `RecursiveTask<int[]>` from `ForkJoinPool`.\n\n**Example:**\nint[] arr = {38,27,43,3,9,82,10};\nnew ForkJoinPool().invoke(new MergeSortTask(arr))\n=> [3,9,10,27,38,43,82]\n\n**Key insight:** Split array in half, fork both halves, join results, merge. ForkJoin uses work-stealing — idle threads steal tasks from busy threads.", "sampleInput": "[38,27,43,3,9,82,10]", "sampleOutput": "[3,9,10,27,38,43,82]"},
    5: {"description": "Chain async operations with `CompletableFuture`: fetch user -> fetch user's orders -> compute total.\n\n**Example:**\nCompletableFuture.supplyAsync(() -> fetchUser(1))\n    .thenApply(user -> fetchOrders(user.id))\n    .thenApply(orders -> orders.stream().mapToDouble(Order::total).sum())\n    .get()\n=> 350.0\n\n**Key insight:** `thenApply` chains synchronous transforms. `thenCompose` chains async futures. `.get()` blocks for the final result.", "sampleInput": "fetchUser(1) -> fetchOrders -> sum totals", "sampleOutput": "350.0"},
    6: {"description": "Implement a token bucket rate limiter: allows up to N requests per second. Tokens refill at a fixed rate; requests consume tokens.\n\n**Example:**\nlimiter = RateLimiter(tokensPerSecond=5)\nlimiter.tryAcquire() x5 => all true (tokens available)\nlimiter.tryAcquire() => false (bucket empty)\nwait 200ms\nlimiter.tryAcquire() => true (1 token refilled)\n\n**Key insight:** Track `lastRefillTime` and compute tokens earned since then. Use `synchronized` or `AtomicLong` for thread safety.", "sampleInput": "5 rapid requests then 6th", "sampleOutput": "first 5: true; 6th: false"},
    7: {"description": "Implement the dining philosophers problem with 5 philosophers, 5 forks. Avoid deadlock using a resource hierarchy or a waiter (arbiter) approach.\n\n**Solution (resource hierarchy):**\nEach philosopher picks up the lower-numbered fork first.\nPhilosopher 4 (last): picks fork 4 then fork 0 — breaks the cycle.\n\n**Example:**\nAll 5 philosophers eat without deadlock for 5 seconds.\n\n**Key insight:** Circular wait is broken by never holding a higher-numbered fork while waiting for a lower-numbered one.", "sampleInput": "5 philosophers, 5 forks, run for 5 seconds", "sampleOutput": "all eat without deadlock"},
    8: {"description": "Implement a non-blocking queue using CAS (compare-and-swap) via `AtomicReference`.\n\n**Example:**\nNBQueue<Integer> q = new NBQueue<>();\nq.enqueue(1); q.enqueue(2); q.enqueue(3);\nq.dequeue() => 1\nq.dequeue() => 2\n\n**Key insight:** Michael-Scott non-blocking queue: `tail.next` CAS to enqueue, `head.next` CAS to dequeue. No locks — threads retry on CAS failure.", "sampleInput": "enqueue(1,2,3), dequeue twice", "sampleOutput": "[1, 2]"},
    9: {"description": "Compute Fibonacci(40) using `ForkJoinPool` with memoization to avoid redundant work.\n\n**Example:**\nnew ForkJoinPool().invoke(new FibTask(10)) => 55\nnew ForkJoinPool().invoke(new FibTask(40)) => 102334155\n\n**Key insight:** Without memoization, ForkJoin Fibonacci has exponential tasks. `ConcurrentHashMap` memoization prunes the tree — same result, far fewer forks.", "sampleInput": "FibTask(10)", "sampleOutput": "55"},
    10: {"description": "Implement a thread-safe LRU cache using `ReentrantReadWriteLock` — concurrent reads, exclusive writes.\n\n**Example:**\ncache = ThreadSafeLRU(capacity=3);\n// concurrent gets from 10 threads — all use read lock\ncache.get(\"key\") => \"value\"\n// puts use write lock\ncache.put(\"newKey\", \"newValue\") => evicts LRU if full\n\n**Key insight:** Read-write lock allows multiple simultaneous readers but exclusive writers — higher throughput for read-heavy caches.", "sampleInput": "get(key) from 10 concurrent threads", "sampleOutput": "all return correct value, no data corruption"},
    11: {"description": "Use `CountDownLatch` to wait for N services to initialize before starting the main application.\n\n**Example:**\nCountDownLatch latch = new CountDownLatch(3);\nnew Thread(() -> { initDB(); latch.countDown(); }).start();\nnew Thread(() -> { initCache(); latch.countDown(); }).start();\nnew Thread(() -> { initQueue(); latch.countDown(); }).start();\nlatch.await(); // blocks until all 3 count down\nSystem.out.println(\"All services ready\");\n\n**Key insight:** `await()` blocks until count reaches zero. One-time use — cannot reset.", "sampleInput": "3 init threads, await() in main", "sampleOutput": "\"All services ready\" after all 3 complete"},
    12: {"description": "Implement a database connection pool using `Semaphore(maxConnections)`.\n\n**Example:**\npool = ConnectionPool(maxConnections=3)\nThread1: acquire => connection1\nThread2: acquire => connection2\nThread3: acquire => connection3\nThread4: acquire => blocks until one is released\nThread1 releases => Thread4 unblocks\n\n**Key insight:** `semaphore.acquire()` decrements the permit count; `semaphore.release()` increments it. Threads block when permits reach zero.", "sampleInput": "4 threads, pool size 3", "sampleOutput": "thread 4 blocks until release"},
    13: {"description": "Implement a cache with `ReadWriteLock` — many concurrent readers, exclusive writer on cache miss.\n\n**Example:**\n100 threads reading cached data — all hold read lock simultaneously\n1 thread writes on miss — acquires write lock, all readers block\n\n**Key insight:** `ReentrantReadWriteLock` — `readLock().lock()` allows concurrency; `writeLock().lock()` is exclusive. Dramatically better than `synchronized` for read-heavy workloads.", "sampleInput": "100 concurrent readers, 1 writer on miss", "sampleOutput": "readers all proceed; writer blocks readers during update"},
    14: {"description": "Implement a bounded thread pool with a custom rejection policy when the queue is full.\n\n**Example:**\npool = new ThreadPoolExecutor(2, 4, 60s, new ArrayBlockingQueue<>(5), new CallerRunsPolicy());\nsubmit 20 tasks rapidly\n=> pool runs up to 4 threads\n=> queue holds up to 5\n=> remaining tasks run on caller thread (CallerRunsPolicy)\n\n**Key insight:** Rejection policies: AbortPolicy (throw), CallerRunsPolicy (run on caller), DiscardPolicy (silently drop), DiscardOldestPolicy (drop oldest queued).", "sampleInput": "submit 20 tasks to pool(2,4) with queue(5)", "sampleOutput": "excess tasks run on caller thread (CallerRunsPolicy)"},
    15: {"description": "Use `Phaser` for a multi-phase parallel computation where all threads must complete phase N before any starts phase N+1.\n\n**Example:**\nPhaser phaser = new Phaser(3); // 3 parties\nThreads: each runs phase1(), then phaser.arriveAndAwaitAdvance(), then phase2()\n=> all finish phase1 before any starts phase2\n\n**Key insight:** `Phaser` is like a reusable `CountDownLatch`. `arriveAndAwaitAdvance()` is the barrier — thread blocks until all parties arrive.", "sampleInput": "3 threads, 2-phase computation with barrier", "sampleOutput": "all complete phase1 before any starts phase2"},
    16: {"description": "Count word frequency in a large text using parallel streams and `ConcurrentHashMap`.\n\n**Example:**\nconcurrentWordCount(bigText)\n=> {\"the\":1000, \"java\":500, ...}\n\n**Key insight:** `ConcurrentHashMap.merge(word, 1L, Long::sum)` is atomic. Using `groupingByConcurrent` in a parallel stream is equivalent and cleaner.", "sampleInput": "parallel word count on \"the cat the cat java\"", "sampleOutput": "{the=2, cat=2, java=1}"},
    17: {"description": "Use `Exchanger<T>` for two threads to swap data at a synchronization point.\n\n**Example:**\nExchanger<String> exchanger = new Exchanger<>();\nThread1: produces \"data from T1\", calls exchange() => receives \"data from T2\"\nThread2: produces \"data from T2\", calls exchange() => receives \"data from T1\"\n\n**Key insight:** Both threads block at `exchanger.exchange()` until the other arrives — then they swap values atomically.", "sampleInput": "T1 sends \"A\", T2 sends \"B\", both call exchange()", "sampleOutput": "T1 receives \"B\", T2 receives \"A\""},
    18: {"description": "Add timeout and cancellation to a `CompletableFuture`.\n\n**Example:**\nCompletableFuture.supplyAsync(() -> slowAPI())\n    .orTimeout(500, TimeUnit.MILLISECONDS)\n    .exceptionally(e -> \"timeout fallback\")\n    .get()\n=> if slowAPI takes > 500ms: \"timeout fallback\"\n=> if fast: actual result\n\n**Key insight:** `.orTimeout()` (Java 9+) completes the future exceptionally with `TimeoutException` after the delay.", "sampleInput": "slowAPI() takes 1s, timeout=500ms", "sampleOutput": "\"timeout fallback\""},
    19: {"description": "Demonstrate the difference between `volatile` (visibility) and `synchronized` (atomicity + visibility):\n\n**Volatile:**\nvolatile boolean running = true;\nThread1 sets running=false\nThread2 sees the update (visibility guaranteed)\nBut: volatile int count; count++ is NOT atomic\n\n**Synchronized:**\nsynchronized void increment() { count++; } // atomic + visible\n\n**Example:**\nShow count loss with volatile, correct count with synchronized.", "sampleInput": "10 threads increment volatile int 1000x each", "sampleOutput": "< 10000 (lost updates with volatile)"},
    20: {"description": "Implement a simple task executor using Java 21 **virtual threads** (`Thread.ofVirtual()`) to handle thousands of concurrent I/O tasks.\n\n**Example:**\ntry (var exec = Executors.newVirtualThreadPerTaskExecutor()) {\n    for (int i = 0; i < 10000; i++) {\n        int id = i;\n        exec.submit(() -> simulateIO(id));\n    }\n} // all 10000 tasks complete\n\n**Key insight:** Virtual threads are cheap (KB vs MB) — 10000 virtual threads vs 10000 platform threads would OOM. Virtual threads block without consuming OS threads.", "sampleInput": "10000 tasks with newVirtualThreadPerTaskExecutor()", "sampleOutput": "all 10000 complete without OOM"},
}

updated = 0
for topic in data['topics']:
    for p in topic.get('problems', []):
        o = p['displayOrder']
        if o in improvements:
            p['description'] = improvements[o]['description']
            p['sampleInput'] = improvements[o]['sampleInput']
            p['sampleOutput'] = improvements[o]['sampleOutput']
            updated += 1
with open(f, 'w', encoding='utf-8') as fh: json.dump(data, fh, indent=2, ensure_ascii=False)
print(f"B21 updated: {updated} problems")
