import json
f = 'C:/Dev/devlearner/devlearner/learning-system/src/main/resources/seeds/B20-io-nio.json'
with open(f, encoding='utf-8') as fh: data = json.load(fh)

improvements = {
    1: {"description": "Read a text file and return its lines as a `List<String>` using `Files.readAllLines()` or `Files.lines()`.\n\n**Example:**\nreadLines(\"data.txt\") where file contains:\n```\nhello\nworld\njava\n```\n=> [\"hello\", \"world\", \"java\"]\n\n**Key insight:** `Files.readAllLines(path, UTF_8)` loads all at once. `Files.lines(path)` returns a lazy `Stream<String>` — better for large files.", "sampleInput": "file: \"hello\\nworld\\njava\"", "sampleOutput": "[\"hello\", \"world\", \"java\"]"},
    2: {"description": "Write a `List<String>` to a file, one item per line, using `Files.write()` or `BufferedWriter`.\n\n**Example:**\nwriteLines(\"output.txt\", [\"line1\", \"line2\", \"line3\"])\n=> file contains:\nline1\nline2\nline3\n\n**Key insight:** `Files.write(path, lines, UTF_8)` is the simplest option. For large lists, `BufferedWriter` streams line by line without loading all into memory.", "sampleInput": "[\"line1\",\"line2\",\"line3\"] to output.txt", "sampleOutput": "file written with 3 lines"},
    3: {"description": "Count the number of lines and words in a file.\n\n**Example:**\nFile contents: \"hello world\\njava is great\\n\"\ncountLinesAndWords(\"file.txt\")\n=> lines=2, words=5\n\n**Key insight:** Stream each line, count lines with `count()`, split each line on whitespace and sum word counts.", "sampleInput": "\"hello world\\njava is great\"", "sampleOutput": "lines=2, words=5"},
    4: {"description": "Copy a file from source to destination using `Files.copy()` or buffered streams.\n\n**Example:**\ncopyFile(\"source.txt\", \"dest.txt\")\n=> dest.txt created with identical content\n\n**Key insight:** `Files.copy(src, dest, REPLACE_EXISTING)` handles buffering internally. For large binary files, use a 8KB buffer with manual read/write for explicit control.", "sampleInput": "copyFile(\"source.txt\", \"dest.txt\")", "sampleOutput": "dest.txt = source.txt content"},
    5: {"description": "Check if a file exists, get its size in bytes, and last modified time.\n\n**Example:**\nPath p = Path.of(\"data.txt\");\nFiles.exists(p) => true\nFiles.size(p) => 1024\nFiles.getLastModifiedTime(p) => 2024-01-15T10:30:00Z\n\n**Key insight:** `Files.exists()` vs `new File().exists()` — prefer `java.nio.file.Files` API. `Files.size()` returns bytes, not KB.", "sampleInput": "fileInfo(\"data.txt\")", "sampleOutput": "exists=true, size=1024, modified=2024-01-15"},
    6: {"description": "Parse the first row of a CSV file into a `String[]` of field values, handling quoted fields with commas.\n\n**Example 1:**\nparseCsvRow(\"Alice,30,Engineer\") => [\"Alice\", \"30\", \"Engineer\"]\n\n**Example 2:**\nparseCsvRow(\"\\\"Smith, John\\\",25,\\\"New York\\\"\") => [\"Smith, John\", \"25\", \"New York\"]\n\n**Key insight:** Simple `split(\",\")` breaks on commas inside quotes. A state-machine parser handles quoted fields correctly.", "sampleInput": "\"\\\"Smith, John\\\",25,\\\"New York\\\"\"", "sampleOutput": "[\"Smith, John\", \"25\", \"New York\"]"},
    7: {"description": "Recursively walk a directory and return all `.java` files using `Files.walk()` or `Files.walkFileTree()`.\n\n**Example:**\nfindJavaFiles(\"/src\")\n=> [\"/src/Main.java\", \"/src/util/Helper.java\", \"/src/model/User.java\"]\n\n**Key insight:** `Files.walk(path).filter(p -> p.toString().endsWith(\".java\")).collect(toList())` — lazy stream over the directory tree.", "sampleInput": "findJavaFiles(\"/src\")", "sampleOutput": "[\"/src/Main.java\", \"/src/util/Helper.java\"]"},
    8: {"description": "Watch a directory for file creation/modification events using `WatchService`.\n\n**Example:**\nwatcher = new FileWatcher(\"/logs\");\nwatcher.start(); // blocks, polling\n// when \"app.log\" is modified:\n=> \"MODIFIED: app.log\"\n// when \"new.log\" is created:\n=> \"CREATED: new.log\"\n\n**Key insight:** `WatchService` is OS-level (inotify on Linux) — far more efficient than polling `Files.getLastModifiedTime()` in a loop.", "sampleInput": "watch /logs, then modify app.log", "sampleOutput": "\"MODIFIED: app.log\""},
    9: {"description": "Parse a CSV file with quoted fields that may contain commas, newlines, or escaped quotes.\n\n**Example:**\nInput CSV row: `\"Jane \\\"Doe\\\"\",\"123 Main St, Apt 4\",30`\nparseFull(row) => [\"Jane \\\"Doe\\\"\", \"123 Main St, Apt 4\", \"30\"]\n\n**Key insight:** State machine: track if currently inside quotes. On `\"\"` inside quotes = escaped quote. On `\"` = toggle quote mode.", "sampleInput": "\"\\\"Jane \\\"\\\"Doe\\\"\\\"\",\"123 Main St, Apt 4\",30", "sampleOutput": "[\"Jane \\\"Doe\\\"\", \"123 Main St, Apt 4\", \"30\"]"},
    10: {"description": "Merge N sorted files into one sorted output file using a min-heap.\n\n**Example:**\nfile1.txt: 1 3 5\nfile2.txt: 2 4 6\nfile3.txt: 0 7 8\nmergeSorted([f1,f2,f3], \"out.txt\") => out.txt: 0 1 2 3 4 5 6 7 8\n\n**Key insight:** K-way merge with a `PriorityQueue<(value, fileIndex)>` — always extract the minimum across all file heads.", "sampleInput": "merge sorted [1,3,5], [2,4,6], [0,7,8]", "sampleOutput": "0 1 2 3 4 5 6 7 8"},
    11: {"description": "Implement a file-backed LRU cache. On miss, read from disk and cache in memory (up to capacity). On eviction, optionally write back if dirty.\n\n**Example:**\ncache = FileLRUCache(capacity=3, cacheDir=\"/tmp\")\ncache.get(\"key1\") => reads from key1.dat, caches it\ncache.get(\"key1\") => returns from memory (cache hit)\ncache.put(\"key4\", data) => evicts LRU entry\n\n**Key insight:** Combines an in-memory LRU map with file I/O fallback — common pattern for disk-backed caches.", "sampleInput": "get(key1) miss -> read disk, get(key1) hit", "sampleOutput": "2nd get: from memory (no disk read)"},
    12: {"description": "Count word frequency in a large file using `BufferedReader` for memory efficiency.\n\n**Example:**\nFile: 100MB text\ncountWords(\"bigfile.txt\") => {\"the\":50000, \"a\":30000, ...}\n\n**Key insight:** `BufferedReader` reads line by line — never loads the whole file. 8KB default buffer means only one OS read per 8KB chunk.", "sampleInput": "large file, count word frequencies", "sampleOutput": "Map<word, count> without OOM"},
    13: {"description": "Implement `tailFile(String path, int n)` that returns the last N lines of a file, like Unix `tail`.\n\n**Example:**\nFile has 1000 lines.\ntailFile(\"log.txt\", 5) => last 5 lines\n\n**Key insight:** Efficient approach: `RandomAccessFile` seeking from the end backward, counting newlines. Simple approach: maintain a circular buffer of N lines while reading forward.", "sampleInput": "tailFile(\"log.txt\", 3) on 10-line file", "sampleOutput": "lines 8, 9, 10"},
    14: {"description": "Compare two binary files byte-by-byte and report the first differing byte offset.\n\n**Example 1:**\nfile1.bin = [0x01, 0x02, 0x03]\nfile2.bin = [0x01, 0x02, 0x04]\ndiff(f1,f2) => \"Differ at offset 2: 0x03 vs 0x04\"\n\n**Example 2:**\ndiff(identical files) => \"Files are identical\"\n\n**Key insight:** Use buffered streams and compare arrays in 8KB chunks — never load both full files into memory.", "sampleInput": "diff file1=[1,2,3] vs file2=[1,2,4]", "sampleOutput": "\"Differ at offset 2: 0x03 vs 0x04\""},
    15: {"description": "Search a large file for a string using memory-mapped I/O (`MappedByteBuffer`).\n\n**Example:**\nsearchFile(\"huge.log\", \"ERROR\") => [line 42, line 108, line 5023]\n\n**Key insight:** `FileChannel.map()` maps the file into virtual memory — the OS pages in only what's accessed. Faster than `BufferedReader` for random access or multi-pass scans.", "sampleInput": "search \"ERROR\" in large log file", "sampleOutput": "[42, 108, 5023] (line numbers with ERROR)"},
    16: {"description": "Process files in a directory concurrently using `ExecutorService` and `Future<Long>` to count lines in each file.\n\n**Example:**\nfiles: [a.txt(10 lines), b.txt(20 lines), c.txt(5 lines)]\nprocessConcurrently(files) => {a.txt=10, b.txt=20, c.txt=5}\n\n**Key insight:** Submit each file as a `Callable<Long>` to a thread pool. Collect results from futures. Speeds up I/O-bound work by overlapping disk reads.", "sampleInput": "3 files processed concurrently", "sampleOutput": "{a.txt=10, b.txt=20, c.txt=5}"},
    17: {"description": "Implement custom serialization with version checking. Add a `serialVersionUID` and handle old vs new format in `readObject()`.\n\n**Example:**\nv1 object serialized: {name, age}\ndeserialize with v2 class: {name, age, email}\n=> email defaults to \"\" (new field)\n=> no InvalidClassException (same serialVersionUID)\n\n**Key insight:** Set `serialVersionUID` explicitly. In `readObject()`, use `defaultReadObject()` then handle missing fields.", "sampleInput": "v1 serialized data, v2 class deserialization", "sampleOutput": "email = \"\" (default for new field)"},
    18: {"description": "Implement an append-only log file: records are appended with a timestamp and never modified.\n\n**Example:**\nlog = new AppendOnlyLog(\"events.log\");\nlog.append(\"user_login\", \"alice\");\nlog.append(\"order_placed\", \"O-123\");\nlog.readAll() => [\n  \"2024-01-15T10:00:00 user_login alice\",\n  \"2024-01-15T10:01:00 order_placed O-123\"\n]\n\n**Key insight:** Open with `StandardOpenOption.APPEND` — each write goes to the end. Never open with TRUNCATE.", "sampleInput": "append(user_login,alice) then readAll()", "sampleOutput": "[\"2024-01-15T10:00:00 user_login alice\"]"},
    19: {"description": "Read entries from a ZIP file and write modified entries to a new ZIP using `ZipInputStream` / `ZipOutputStream`.\n\n**Example:**\nInput: archive.zip contains [readme.txt, data.csv]\nreadZip(\"archive.zip\") => [\"readme.txt\", \"data.csv\"]\nwriteZip(\"out.zip\", Map.of(\"hello.txt\",\"Hello World\")) => creates zip with hello.txt\n\n**Key insight:** `ZipInputStream` iterates entries via `getNextEntry()`. Each entry is a stream — read/write without extracting to disk.", "sampleInput": "readZip(\"archive.zip\")", "sampleOutput": "[\"readme.txt\", \"data.csv\"]"},
    20: {"description": "Implement a non-blocking file server skeleton using NIO `Selector` and `ServerSocketChannel`. Accept connections and echo file contents without blocking threads.\n\n**Key concepts:**\n- `Selector.open()` — monitors multiple channels\n- `SelectionKey.OP_ACCEPT` / `OP_READ` — event types\n- Non-blocking: a single thread handles many connections\n\n**Example:**\nserver starts on port 8888\nclient connects, requests \"file.txt\"\nserver sends file contents asynchronously\n\n**Key insight:** One selector thread handles thousands of connections — far more scalable than one-thread-per-connection.", "sampleInput": "NIO server, client requests file.txt", "sampleOutput": "file contents sent non-blocking"},
}

updated = 0
for topic in data['topics']:
    for p in topic.get('problems', []):
        o = p['displayOrder']
        if o in improvements:
            p['description'] = improvements[o]['description']
            p['sampleInput'] = improvements[o]['sampleInput']
            p['sampleOutput'] = improvements[o]['sampleOutput']
            updated += 1
with open(f, 'w', encoding='utf-8') as fh: json.dump(data, fh, indent=2, ensure_ascii=False)
print(f"B20 updated: {updated} problems")
