import json
f = 'C:/Dev/devlearner/devlearner/learning-system/src/main/resources/seeds/B16-generics.json'
with open(f, encoding='utf-8') as fh: data = json.load(fh)

improvements = {
    1: {"description": "Implement `<T extends Comparable<T>> T min(T[] arr)` and `max(T[] arr)` that work for any Comparable type.\n\n**Example 1:**\nmin(new Integer[]{3,1,4,1,5}) => 1\nmax(new Integer[]{3,1,4,1,5}) => 5\n\n**Example 2:**\nmin(new String[]{\"banana\",\"apple\",\"cherry\"}) => \"apple\"\nmax(new String[]{\"banana\",\"apple\",\"cherry\"}) => \"cherry\"", "sampleInput": "min(new Integer[]{3,1,4,1,5})", "sampleOutput": "1"},
    2: {"description": "Implement generic `<T> void swap(T[] arr, int i, int j)` and `<T> void reverse(T[] arr)`.\n\n**Example 1:**\nInteger[] arr = {1,2,3,4,5}; swap(arr,0,4); => {5,2,3,4,1}\n\n**Example 2:**\nString[] s = {\"a\",\"b\",\"c\"}; reverse(s); => {\"c\",\"b\",\"a\"}\n\n**Key insight:** Generic methods write the logic once for all reference types — no casting, compile-time safety.", "sampleInput": "reverse(new String[]{\"a\",\"b\",\"c\"})", "sampleOutput": "[\"c\",\"b\",\"a\"]"},
    3: {"description": "Implement generic `Triple<A,B,C>` with three typed fields, a constructor, getters, `equals()`, `hashCode()`, `toString()`, and static factory `of(A,B,C)`.\n\n**Example:**\nTriple<String,Integer,Boolean> t = Triple.of(\"hello\", 42, true);\nt.getFirst() => \"hello\"\nt.getSecond() => 42\nt.getThird() => true\nt.toString() => \"(hello, 42, true)\"", "sampleInput": "Triple.of(\"hello\", 42, true).toString()", "sampleOutput": "\"(hello, 42, true)\""},
    4: {"description": "Implement `<T> Map<T,Long> frequency(List<T> items)` that counts occurrences of each element.\n\n**Example 1:**\nfrequency(List.of(\"a\",\"b\",\"a\",\"c\",\"b\",\"a\")) => {a=3, b=2, c=1}\n\n**Example 2:**\nfrequency(List.of(1,2,1,3,2,1)) => {1=3, 2=2, 3=1}\n\n**Key insight:** Generic frequency counter works for String, Integer, or any type — one implementation, infinite reuse.", "sampleInput": "frequency([\"a\",\"b\",\"a\",\"c\",\"b\",\"a\"])", "sampleOutput": "{a=3, b=2, c=1}"},
    5: {"description": "Implement a generic `BST<T extends Comparable<T>>` with `insert(T)`, `contains(T)`, and `inOrder()` returning a sorted list.\n\n**Example:**\nBST<Integer> tree = new BST<>();\ntree.insert(5); tree.insert(3); tree.insert(7); tree.insert(1);\ntree.contains(3) => true\ntree.inOrder() => [1,3,5,7]\n\n**Key insight:** The `Comparable` bound lets you use `compareTo()` without knowing the concrete type.", "sampleInput": "insert 5,3,7,1 then inOrder()", "sampleOutput": "[1,3,5,7]"},
    6: {"description": "Use wildcards to write `double sumList(List<? extends Number> list)` that sums any list of numbers (Integer, Double, Long, etc.).\n\n**Example 1:**\nsumList(List.of(1,2,3)) => 6.0\nsumList(List.of(1.5, 2.5, 3.0)) => 7.0\n\n**Key insight:** `? extends Number` (upper bounded wildcard) allows reading from the list as `Number` — works for any subtype. Cannot add to it.", "sampleInput": "sumList(List.of(1,2,3))", "sampleOutput": "6.0"},
    7: {"description": "Implement `Cache<K,V>` with a TTL (time-to-live). `put(K key, V value, long ttlMs)` stores with expiry; `get(K key)` returns `Optional.empty()` if expired.\n\n**Example:**\ncache.put(\"token\", \"abc123\", 1000); // expires in 1 second\ncache.get(\"token\") => Optional.of(\"abc123\")\nThread.sleep(1100);\ncache.get(\"token\") => Optional.empty()", "sampleInput": "put with 1000ms TTL, get before and after expiry", "sampleOutput": "before: Optional[abc123]; after: Optional.empty"},
    8: {"description": "Implement `Graph<T>` using `Map<T, List<T>>` adjacency map. Supports `addVertex(T)`, `addEdge(T from, T to)`, `neighbors(T)`, and `BFS(T start)`.\n\n**Example:**\nGraph<String> g = new Graph<>();\ng.addEdge(\"A\",\"B\"); g.addEdge(\"A\",\"C\"); g.addEdge(\"B\",\"D\");\ng.bfs(\"A\") => [\"A\",\"B\",\"C\",\"D\"]\ng.neighbors(\"A\") => [\"B\",\"C\"]", "sampleInput": "bfs(\"A\") on A->B, A->C, B->D", "sampleOutput": "[\"A\",\"B\",\"C\",\"D\"]"},
    9: {"description": "Implement `Statistics<T extends Number>` with `mean()`, `max()`, `min()`, `variance()` over a list of numbers.\n\n**Example:**\nStatistics<Integer> s = new Statistics<>(List.of(2,4,4,4,5,5,7,9));\ns.mean() => 5.0\ns.variance() => 4.0\ns.max() => 9\ns.min() => 2", "sampleInput": "Statistics([2,4,4,4,5,5,7,9]).mean()", "sampleOutput": "5.0"},
    10: {"description": "Implement `Pipeline<T>` with `pipe(Function<T,T>)` and `execute(T input)`. Stages are stored as `List<Function<T,T>>` and applied in order.\n\n**Example:**\nnew Pipeline<String>()\n    .pipe(String::trim)\n    .pipe(String::toUpperCase)\n    .pipe(s -> \"[\" + s + \"]\")\n    .execute(\"  hello  \")\n=> \"[HELLO]\"", "sampleInput": "trim -> toUpperCase -> bracket on \"  hello  \"", "sampleOutput": "\"[HELLO]\""},
    11: {"description": "Implement a type-safe `EventBus<E>` where listeners are registered per event type using `Class<E>` as key.\n\n**Example:**\nEventBus bus = new EventBus();\nbus.subscribe(UserCreated.class, e -> System.out.println(\"User: \" + e.name()));\nbus.publish(new UserCreated(\"Alice\")) => prints \"User: Alice\"\nbus.publish(new OrderPlaced(\"O1\")) => no output (no subscriber)\n\n**Key insight:** `Class<E>` token is the key — dispatches only to listeners registered for that exact event type.", "sampleInput": "publish(new UserCreated(\"Alice\"))", "sampleOutput": "\"User: Alice\""},
    12: {"description": "Implement generic merge sort `<T extends Comparable<T>> List<T> mergeSort(List<T> list)` that works for any Comparable type.\n\n**Example 1:**\nmergeSort(List.of(3,1,4,1,5)) => [1,1,3,4,5]\n\n**Example 2:**\nmergeSort(List.of(\"banana\",\"apple\",\"cherry\")) => [\"apple\",\"banana\",\"cherry\"]\n\n**Key insight:** Generic merge sort uses `compareTo()` from the bound — one algorithm sorts integers, strings, or any Comparable.", "sampleInput": "mergeSort([\"banana\",\"apple\",\"cherry\"])", "sampleOutput": "[\"apple\",\"banana\",\"cherry\"]"},
    13: {"description": "Implement generic `LRUCache<K,V>` with capacity limit using `LinkedHashMap` (access-order) or doubly-linked list + HashMap.\n\n**Example:**\nLRUCache<Integer,String> cache = new LRUCache<>(2);\ncache.put(1,\"a\"); cache.put(2,\"b\");\ncache.get(1) => \"a\" (1 is now most-recent)\ncache.put(3,\"c\"); // evicts key 2 (LRU)\ncache.get(2) => null", "sampleInput": "put(1,a),put(2,b),get(1),put(3,c),get(2)", "sampleOutput": "null"},
    14: {"description": "Implement `Observable<T>` with `addObserver(Consumer<T>)` and `setValue(T)` — setting a value notifies all observers.\n\n**Example:**\nObservable<String> obs = new Observable<>();\nobs.addObserver(v -> System.out.println(\"A: \" + v));\nobs.addObserver(v -> System.out.println(\"B: \" + v));\nobs.setValue(\"hello\");\n=> \"A: hello\"\n=> \"B: hello\"", "sampleInput": "setValue(\"hello\") with 2 observers", "sampleOutput": "\"A: hello\" / \"B: hello\""},
    15: {"description": "Implement a `TypeRegistry` that maps `Class<T>` to `T` instances, providing type-safe retrieval without casting:\n\n**Example:**\nTypeRegistry r = new TypeRegistry();\nr.register(String.class, \"hello\");\nr.register(Integer.class, 42);\nr.get(String.class) => \"hello\" (no cast)\nr.get(Integer.class) => 42 (no cast)\nr.get(Double.class) => null\n\n**Key insight:** The token pattern — `Class<T>` key ensures the value retrieved matches the type `T`.", "sampleInput": "r.get(String.class)", "sampleOutput": "\"hello\" (no cast needed)"},
    16: {"description": "Implement `Lazy<T>` that defers computation until first access:\n\n**Example:**\nLazy<String> lazy = new Lazy<>(() -> { System.out.println(\"computed\"); return \"hello\"; });\n// nothing printed yet\nSystem.out.println(lazy.get()); // => \"computed\" then \"hello\"\nSystem.out.println(lazy.get()); // => \"hello\" (no recomputation)\n\n**Key insight:** The supplier runs only once — subsequent `get()` returns the cached value.", "sampleInput": "Lazy(() -> computeExpensiveValue()).get() x2", "sampleOutput": "computed once, cached on subsequent calls"},
    17: {"description": "Implement `ImmutableList<T>` backed by an array. Supports `get(int)`, `size()`, `add(T)` (returns new list), and `toList()`. No mutation of existing instance.\n\n**Example:**\nImmutableList<Integer> l1 = ImmutableList.of(1,2,3);\nImmutableList<Integer> l2 = l1.add(4);\nl1.size() => 3 (unchanged)\nl2.size() => 4\nl2.get(3) => 4", "sampleInput": "ImmutableList.of(1,2,3).add(4)", "sampleOutput": "new list size=4; original size=3"},
    18: {"description": "Implement `NaryTree<T>` where each node has a value and a `List<NaryTree<T>>` children. Methods: `add(T value)`, `findBFS(T target)`, `height()`.\n\n**Example:**\nNaryTree<String> root = new NaryTree<>(\"root\");\nroot.add(\"child1\"); root.add(\"child2\");\nroot.getChildren().get(0).add(\"grandchild\");\nroot.height() => 2\nroot.findBFS(\"grandchild\") => Optional[NaryTree{grandchild}]", "sampleInput": "root + 2 children + 1 grandchild: height()", "sampleOutput": "2"},
    19: {"description": "Implement `Maybe<T>` (like `Optional`) as a generic monad with `of(T)`, `empty()`, `map(Function)`, `flatMap(Function)`, `orElse(T)`.\n\n**Example:**\nMaybe.of(\"hello\")\n    .map(String::toUpperCase)\n    .map(s -> s + \"!\")\n    .orElse(\"nothing\")\n=> \"HELLO!\"\n\nMaybe.empty()\n    .map(String::toUpperCase)\n    .orElse(\"nothing\")\n=> \"nothing\"", "sampleInput": "Maybe.of(\"hello\").map(toUpperCase).map(+!).orElse(\"nothing\")", "sampleOutput": "\"HELLO!\""},
    20: {"description": "Implement a persistent (copy-on-write) `PersistentMap<K,V>` where `put(K,V)` returns a new map without modifying the original:\n\n**Example:**\nPersistentMap<String,Integer> m1 = PersistentMap.empty();\nPersistentMap<String,Integer> m2 = m1.put(\"a\", 1);\nPersistentMap<String,Integer> m3 = m2.put(\"b\", 2);\nm1.size() => 0\nm2.size() => 1\nm3.get(\"a\") => 1\nm3.get(\"b\") => 2", "sampleInput": "empty().put(\"a\",1).put(\"b\",2).get(\"a\")", "sampleOutput": "1"},
}

updated = 0
for topic in data['topics']:
    for p in topic.get('problems', []):
        o = p['displayOrder']
        if o in improvements:
            p['description'] = improvements[o]['description']
            p['sampleInput'] = improvements[o]['sampleInput']
            p['sampleOutput'] = improvements[o]['sampleOutput']
            updated += 1
with open(f, 'w', encoding='utf-8') as fh: json.dump(data, fh, indent=2, ensure_ascii=False)
print(f"B16 updated: {updated} problems")
