import json
f = 'C:/Dev/devlearner/devlearner/learning-system/src/main/resources/seeds/B22-design-patterns.json'
with open(f, encoding='utf-8') as fh: data = json.load(fh)

improvements = {
    1: {"description": "Implement a thread-safe `Singleton` using the initialization-on-demand holder idiom.\n\n**Example:**\nConfig a = Config.getInstance();\nConfig b = Config.getInstance();\na == b => true\n\n```java\nclass Config {\n    private Config() {}\n    private static class Holder { static final Config INSTANCE = new Config(); }\n    public static Config getInstance() { return Holder.INSTANCE; }\n}\n```\n\n**Key insight:** Class loading is thread-safe by the JVM — `Holder` is only initialized when `getInstance()` is first called.", "sampleInput": "Config.getInstance() from 2 threads", "sampleOutput": "same instance (==)"},
    2: {"description": "Implement a `PluginRegistry` (Factory pattern): register `Class<? extends Plugin>` under a string key, create instances by name.\n\n**Example:**\nregistry.register(\"csv\", CsvPlugin.class);\nregistry.register(\"json\", JsonPlugin.class);\nregistry.create(\"csv\") instanceof CsvPlugin => true\nregistry.create(\"xml\") => throws IllegalArgumentException\n\n**Key insight:** Factory decouples creation from usage — callers don't import concrete classes. New plugins just need registration.", "sampleInput": "registry.create(\"csv\")", "sampleOutput": "instanceof CsvPlugin => true"},
    3: {"description": "Build a `SearchRequest` using a Builder with optional fields: `query`, `page`, `pageSize`, `sortBy`, `filters`.\n\n**Example:**\nSearchRequest req = new SearchRequest.Builder(\"java\")\n    .page(2)\n    .pageSize(20)\n    .sortBy(\"date\")\n    .filter(\"category\", \"tutorials\")\n    .build();\nreq.getQuery() => \"java\"\nreq.getPage() => 2", "sampleInput": "Builder(\"java\").page(2).pageSize(20).sortBy(\"date\").build()", "sampleOutput": "SearchRequest{query=java, page=2, pageSize=20}"},
    4: {"description": "Implement a Decorator chain combining logging and caching:\n\n**Example:**\nUserService base = new UserServiceImpl();\nUserService cached = new CachingDecorator(base);\nUserService logged = new LoggingDecorator(cached);\n\nlogged.findById(1):\n=> \"[LOG] findById(1) called\"\n=> checks cache: miss\n=> calls base.findById(1) => User{Alice}\n=> \"[LOG] findById(1) returned User{Alice}\"\nlogged.findById(1) again:\n=> cache hit — base not called", "sampleInput": "findById(1) twice through LoggingDecorator -> CachingDecorator -> Base", "sampleOutput": "2nd call: cache hit, base not invoked"},
    5: {"description": "Implement a **Proxy** for lazy loading — create the expensive real object only on first use.\n\n**Example:**\nImage img = new LazyImageProxy(\"large-photo.jpg\");\n// real image NOT loaded yet\nimg.display();\n=> \"Loading large-photo.jpg from disk...\" (real object created)\n=> \"Displaying large-photo.jpg\"\nimg.display();\n=> \"Displaying large-photo.jpg\" (no reload)\n\n**Key insight:** Proxy implements the same interface as the real object — callers don't know they're talking to a proxy.", "sampleInput": "img.display() twice via proxy", "sampleOutput": "1st: load + display; 2nd: display only"},
    6: {"description": "Implement Abstract Factory for a UI theme system: `LightTheme` and `DarkTheme` each produce matching `Button` and `Checkbox` widgets.\n\n**Example:**\nUIFactory f = new DarkTheme();\nf.createButton().render() => \"Dark Button\"\nf.createCheckbox().render() => \"Dark Checkbox\"\n\nUIFactory f2 = new LightTheme();\nf2.createButton().render() => \"Light Button\"\n\n**Key insight:** Abstract Factory ensures product families are consistent — a Dark button always pairs with a Dark checkbox.", "sampleInput": "new DarkTheme().createButton().render()", "sampleOutput": "\"Dark Button\""},
    7: {"description": "Implement an `EventBus` Observer: `subscribe(EventType, Listener)`, `publish(Event)` notifies all matching listeners.\n\n**Example:**\nbus.subscribe(\"USER_CREATED\", e -> System.out.println(\"Email: \" + e.data()));\nbus.subscribe(\"USER_CREATED\", e -> System.out.println(\"Log: \" + e.data()));\nbus.publish(new Event(\"USER_CREATED\", \"alice@example.com\"));\n=> \"Email: alice@example.com\"\n=> \"Log: alice@example.com\"", "sampleInput": "publish USER_CREATED with 2 subscribers", "sampleOutput": "\"Email: alice@example.com\" / \"Log: alice@example.com\""},
    8: {"description": "Implement **Strategy** for a payment system: `PaymentContext` accepts a `PaymentStrategy` at runtime.\n\n**Example:**\nctx.setStrategy(new CreditCardStrategy(\"4111...\"));\nctx.pay(100.0) => \"Paid $100.00 with Credit Card ending 1111\"\n\nctx.setStrategy(new PayPalStrategy(\"user@paypal.com\"));\nctx.pay(50.0) => \"Paid $50.00 via PayPal (user@paypal.com)\"\n\n**Key insight:** Context delegates to strategy — swapping strategies at runtime without `if/else` chains.", "sampleInput": "ctx.setStrategy(new PayPalStrategy()).pay(50.0)", "sampleOutput": "\"Paid $50.00 via PayPal (user@paypal.com)\""},
    9: {"description": "Implement **Command** pattern for a text editor with undo/redo:\n\n**Example:**\neditor.execute(new InsertCommand(\"Hello\"));\neditor.execute(new InsertCommand(\" World\"));\neditor.getText() => \"Hello World\"\neditor.undo();\neditor.getText() => \"Hello\"\neditor.redo();\neditor.getText() => \"Hello World\"\n\n**Key insight:** Each command stores enough state to undo itself. Undo stack: push on execute, pop on undo. Redo stack: push on undo, pop on redo.", "sampleInput": "insert Hello, insert World, undo", "sampleOutput": "text = \"Hello\""},
    10: {"description": "Implement **Template Method** for a data export pipeline: `abstract readData()`, `abstract transformData()`, `abstract writeOutput()`. `CsvExporter` and `JsonExporter` fill in the steps.\n\n**Example:**\nnew CsvExporter(data).export();\n=> \"[CSV] Reading 5 records\"\n=> \"[CSV] Transforming to CSV format\"\n=> \"[CSV] Writing output.csv\"\n\n**Key insight:** Parent defines WHEN; subclasses define HOW. The algorithm skeleton in the parent cannot be changed — only the steps.", "sampleInput": "new CsvExporter(data).export()", "sampleOutput": "\"Reading\" -> \"Transforming\" -> \"Writing\" in CSV format"},
    11: {"description": "Implement **Chain of Responsibility** as HTTP middleware: `AuthFilter -> RateLimitFilter -> LoggingFilter -> Handler`.\n\n**Example:**\nchain.handle(request{authenticated=true, rateOk=true})\n=> \"Auth: OK\"\n=> \"RateLimit: OK\"\n=> \"Logging request\"\n=> \"Handled: /api/users\"\n\nchain.handle(request{authenticated=false})\n=> \"Auth: DENIED\" (chain stops)", "sampleInput": "unauthenticated request through chain", "sampleOutput": "\"Auth: DENIED\" (chain stops)"},
    12: {"description": "Implement **State Machine** for order lifecycle: PENDING -> CONFIRMED -> SHIPPED -> DELIVERED (or CANCELLED from any state).\n\n**Example:**\nOrder order = new Order();\norder.getState() => PENDING\norder.confirm() => CONFIRMED\norder.ship() => SHIPPED\norder.confirm() => throws InvalidStateTransitionException\n\n**Key insight:** Each state handles only its valid transitions — invalid operations throw exceptions. State pattern eliminates giant `switch` statements.", "sampleInput": "PENDING -> confirm() -> ship() -> confirm()", "sampleOutput": "final confirm() throws InvalidStateTransitionException"},
    13: {"description": "Implement **Composite** for a file system tree where both `File` and `Directory` implement `FileSystemNode`.\n\n**Example:**\nDirectory root = new Directory(\"root\");\nroot.add(new File(\"a.txt\", 100));\nDirectory sub = new Directory(\"sub\");\nsub.add(new File(\"b.txt\", 200));\nroot.add(sub);\nroot.size() => 300\nroot.print(0) => \"root/ (300B)\\n  a.txt (100B)\\n  sub/ (200B)\\n    b.txt (200B)\"", "sampleInput": "root with File(100) + Dir(File(200))", "sampleOutput": "root.size() = 300"},
    14: {"description": "Implement **Flyweight** to share color/texture data across thousands of particles, minimizing memory.\n\n**Example:**\nParticleFactory factory = new ParticleFactory();\nParticle p1 = factory.getParticle(\"red\", \"circle\"); // creates flyweight\nParticle p2 = factory.getParticle(\"red\", \"circle\"); // returns cached\np1 == p2 => true (shared flyweight)\nfactory.getCacheSize() => 1 (only one red-circle flyweight)\n\n**Key insight:** Intrinsic state (color, texture) is shared; extrinsic state (position, velocity) is passed at use time.", "sampleInput": "getParticle(\"red\",\"circle\") twice", "sampleOutput": "same instance (==), cache size = 1"},
    15: {"description": "Implement a **Prototype Registry** where pre-configured objects can be cloned on demand.\n\n**Example:**\nregistry.register(\"alert-email\", new EmailNotification(\"ALERT\", \"ops@co.com\"));\nregistry.register(\"info-sms\", new SmsNotification(\"INFO\", \"+1800\"));\n\nEmailNotification n = (EmailNotification) registry.clone(\"alert-email\");\nn.setRecipient(\"dev@co.com\"); // customize the clone\nregistry.clone(\"alert-email\").getRecipient() => \"ops@co.com\" (original unchanged)\n\n**Key insight:** Clone from prototype — avoids re-initializing default config every time.", "sampleInput": "clone(\"alert-email\"), modify, then re-clone", "sampleOutput": "re-clone still has original recipient"},
    16: {"description": "Implement a **Facade** that simplifies calling multiple microservices:\n\n**Example:**\nOrderFacade facade = new OrderFacade(inventoryClient, paymentClient, notificationClient);\nOrderResult result = facade.placeOrder(userId, items);\n// internally:\n// 1. inventoryClient.reserve(items)\n// 2. paymentClient.charge(userId, total)\n// 3. notificationClient.send(userId, \"Order confirmed\")\nresult.isSuccess() => true\n\n**Key insight:** Facade hides complexity — callers don't need to know about 3 services and their coordination.", "sampleInput": "facade.placeOrder(userId, items)", "sampleOutput": "OrderResult{success=true}"},
    17: {"description": "Implement **Abstract Factory** for cross-platform dialog creation: `WindowsDialogFactory` and `MacDialogFactory` produce matching `Alert`, `Confirm`, and `Input` dialogs.\n\n**Example:**\nDialogFactory f = new MacDialogFactory();\nf.createAlert(\"Warning\").show() => \"[Mac Alert] Warning\"\nf.createConfirm(\"Are you sure?\").show() => \"[Mac Confirm] Are you sure?\"\n\n**Key insight:** Abstract Factory guarantees platform consistency — all widgets from one factory look and behave the same.", "sampleInput": "new MacDialogFactory().createAlert(\"Warning\").show()", "sampleOutput": "\"[Mac Alert] Warning\""},
    18: {"description": "Implement **Decorator** for input validation: wrap a `DataProcessor` with `LengthValidator`, `FormatValidator`, `SanitizationDecorator`.\n\n**Example:**\nDataProcessor p = new SanitizationDecorator(\n    new FormatValidator(\n        new LengthValidator(baseProcessor, maxLen=100), pattern),\n    badChars);\np.process(\"<script>alert(1)</script>\")\n=> LengthValidator: OK (< 100 chars)\n=> FormatValidator: FAIL (invalid chars)\n=> throws ValidationException\n\n**Key insight:** Each decorator adds one responsibility — easy to add/remove/reorder validators without touching base or other decorators.", "sampleInput": "process(\"<script>alert(1)</script>\")", "sampleOutput": "throws ValidationException (format check)"},
    19: {"description": "Implement a **Builder** with validation and producing an immutable result object.\n\n**Example:**\nHttpRequest req = new HttpRequest.Builder()\n    .method(\"GET\")\n    .url(\"https://api.example.com/users\")\n    .header(\"Authorization\", \"Bearer token123\")\n    .timeout(5000)\n    .build();\nreq.getMethod() => \"GET\"\nreq.getHeaders().put(\"X-New\",\"v\") => throws UnsupportedOperationException (immutable)\n\n**Key insight:** Builder accumulates mutable state; `build()` validates and creates an immutable value object.", "sampleInput": "Builder().method(GET).url(...).build()", "sampleOutput": "immutable HttpRequest; headers.put throws"},
    20: {"description": "Given a code snippet, identify which design pattern it demonstrates and explain why.\n\n**Example 1:**\n```java\ninterface Strategy { void execute(); }\nclass Context { Strategy s; void run() { s.execute(); } }\n```\n=> **Strategy** — behaviour encapsulated in interchangeable objects\n\n**Example 2:**\n```java\nclass Singleton { private static Singleton inst; static Singleton get() { if(inst==null) inst=new Singleton(); return inst; } }\n```\n=> **Singleton** — single instance, global access point\n\nImplement `identifyPattern(String code)` returning the pattern name.", "sampleInput": "code with Strategy interface", "sampleOutput": "\"Strategy\""},
}

updated = 0
for topic in data['topics']:
    for p in topic.get('problems', []):
        o = p['displayOrder']
        if o in improvements:
            p['description'] = improvements[o]['description']
            p['sampleInput'] = improvements[o]['sampleInput']
            p['sampleOutput'] = improvements[o]['sampleOutput']
            updated += 1
with open(f, 'w', encoding='utf-8') as fh: json.dump(data, fh, indent=2, ensure_ascii=False)
print(f"B22 updated: {updated} problems")
