import json
f = 'C:/Dev/devlearner/devlearner/learning-system/src/main/resources/seeds/B03-data-types.json'
with open(f, encoding='utf-8') as fh: data = json.load(fh)

improvements = {
    1: {"description": "Detect if adding two integers will overflow `Integer.MAX_VALUE` or underflow `Integer.MIN_VALUE` before performing the addition.\n\n**Example:**\nwillOverflow(Integer.MAX_VALUE, 1) => true\nwillOverflow(1000, 2000) => false\nwillUnderflow(Integer.MIN_VALUE, -1) => true\n\n**Key insight:** Check `a > 0 && b > Integer.MAX_VALUE - a` to detect overflow without actually overflowing.", "sampleInput": "willOverflow(Integer.MAX_VALUE, 1)", "sampleOutput": "true"},
    2: {"description": "Validate whether a value fits within a given primitive type range.\n\n**Example:**\nfitsInByte(127) => true\nfitsInByte(128) => false\nfitsInShort(32767) => true\nfitsInShort(32768) => false\nfitsInInt(Long.MAX_VALUE) => false\n\n**Key insight:** Byte: -128 to 127. Short: -32768 to 32767. Int: -2^31 to 2^31-1. Long: -2^63 to 2^63-1.", "sampleInput": "fitsInByte(127), fitsInByte(128)", "sampleOutput": "true, false"},
    3: {"description": "Compare floating-point numbers correctly using an epsilon tolerance instead of `==`.\n\n**Example:**\n0.1 + 0.2 == 0.3 => false (floating point imprecision)\nequalsApprox(0.1 + 0.2, 0.3, 1e-9) => true\n\n**Key insight:** Never compare floats/doubles with `==`. Use `Math.abs(a - b) < epsilon`. For financial calculations, use `BigDecimal`.", "sampleInput": "equalsApprox(0.1 + 0.2, 0.3, 1e-9)", "sampleOutput": "true"},
    4: {"description": "Predict the output of Integer autoboxing cache comparisons:\n\n```java\nInteger a = 127; Integer b = 127;\na == b => true  // cached (-128 to 127)\nInteger c = 128; Integer d = 128;\nc == d => false // new objects outside cache\n```\n\nImplement `predictBoxingEquality(int value)` returning whether `Integer.valueOf(value) == Integer.valueOf(value)`.", "sampleInput": "predictBoxingEquality(127), predictBoxingEquality(128)", "sampleOutput": "true, false"},
    5: {"description": "Convert strings to each primitive type with proper error handling.\n\n**Example:**\nparseInt(\"42\") => 42\nparseDouble(\"3.14\") => 3.14\nparseBoolean(\"true\") => true\nparseInt(\"abc\") => throws NumberFormatException\nparseInt(null) => throws NumberFormatException\n\nImplement `safeParse(String s, Class<?> type)` returning `Optional<?>` wrapping the result.", "sampleInput": "safeParse(\"3.14\", Double.class)", "sampleOutput": "Optional[3.14]"},
    6: {"description": "Analyze a number's binary representation using bitwise operators.\n\n**Example:**\nint n = 42; // binary: 00101010\nbinaryString(n) => \"00101010\"\ncountBits(n) => 8\ncountSetBits(n) => 3 (bits 1,3,5 are set)\nhighestSetBit(n) => 5 (0-indexed from right)\n\n**Key insight:** `Integer.toBinaryString(n)` shows binary. `Integer.bitCount(n)` counts set bits.", "sampleInput": "analyze(42)", "sampleOutput": "binary=101010, setBits=3, highestBit=5"},
    7: {"description": "Benchmark `String` concatenation with `+` vs `StringBuilder` for 10,000 iterations.\n\n**Example:**\nbenchmark(10000):\nconcatWithPlus: ~200ms (creates 10000 String objects)\nconcatWithBuilder: ~2ms (one StringBuilder)\n\nReturn: `Map<String, Long>` with {\"plus_ms\": X, \"builder_ms\": Y}\n\n**Key insight:** `s += part` inside a loop is O(n^2) — each iteration copies the growing string. StringBuilder is O(n).", "sampleInput": "benchmark concat with 10000 iterations", "sampleOutput": "{plus_ms:~200, builder_ms:~2}"},
    8: {"description": "Build a type conversion matrix showing implicit widening and explicit narrowing between all primitive types.\n\n**Example:**\nbyte -> short -> int -> long -> float -> double (widening, implicit)\ndouble -> float -> long -> int -> short -> byte (narrowing, requires cast)\n\ncanImplicitlyConvert(int.class, double.class) => true\ncanImplicitlyConvert(double.class, int.class) => false\nneedsExplicitCast(double.class, int.class) => true", "sampleInput": "canImplicitlyConvert(int.class, double.class)", "sampleOutput": "true"},
    9: {"description": "Calculate monetary amounts using `BigDecimal` to avoid floating-point precision errors.\n\n**Example:**\n// WRONG: double\n0.1 + 0.2 => 0.30000000000000004\n\n// CORRECT: BigDecimal\nnew BigDecimal(\"0.10\").add(new BigDecimal(\"0.20\")) => 0.30\n\nImplement `calculateTotal(String[] prices)` summing price strings as BigDecimal, rounding to 2 decimal places.", "sampleInput": "[\"10.50\", \"3.99\", \"0.01\"]", "sampleOutput": "14.50"},
    10: {"description": "Handle passwords as `char[]` instead of `String` for security — `char[]` can be zeroed out after use; Strings are immutable and may linger in memory/logs.\n\n**Example:**\nchar[] password = getPassword();\ntry { authenticate(password); }\nfinally { Arrays.fill(password, '\\0'); } // zero out\n\nImplement `securePasswordCheck(char[] input, char[] stored)` that zeroes both arrays after comparison.", "sampleInput": "securePasswordCheck({'p','a','s','s'}, {'p','a','s','s'})", "sampleOutput": "true (then both arrays zeroed)"},
    11: {"description": "Analyze code to find where `var` (local type inference) can be used appropriately vs where it harms readability.\n\n**Example:**\nvar list = new ArrayList<String>(); // OK — type obvious from RHS\nvar x = process(); // BAD — return type unclear\nvar entry = map.entrySet().iterator().next(); // OK — verbose type\n\nImplement `canUseVar(String declaration)` returning \"OK\", \"BAD\", or \"BORDERLINE\" with reason.", "sampleInput": "\"var list = new ArrayList<String>()\"", "sampleOutput": "\"OK (type obvious from RHS)\""},
    12: {"description": "Measure memory usage difference between `int[]` and `Integer[]`:\n\n**Example:**\nint[] primitives = new int[1000000];    // ~4MB\nInteger[] boxed = new Integer[1000000]; // ~16MB+ (header per object)\n\nImplement `measureArrayMemory(int size)` returning `{primitive_bytes, boxed_bytes}`.\n\n**Key insight:** Each `Integer` object has ~16 bytes header + 4 bytes value. Primitive `int` is 4 bytes. 4x+ overhead from boxing.", "sampleInput": "measureArrayMemory(1000000)", "sampleOutput": "{primitive: ~4MB, boxed: ~16MB}"},
    13: {"description": "Stress-test the String intern pool by interning thousands of strings and measuring memory:\n\n**Example:**\nString.intern() adds to the pool — repeated interning of the same string reuses the pooled instance.\n\"hello\".intern() == \"hello\" => true (same reference from pool)\n\nImplement `internStressTest(int count)` interning `count` unique strings and return pool size estimate.", "sampleInput": "internStressTest(100000)", "sampleOutput": "pool grows ~100000 entries"},
    14: {"description": "Demonstrate the surprising precision loss when converting `long` to `float`:\n\n**Example:**\nlong big = 1234567890123456789L;\nfloat f = (float) big;\nlong back = (long) f;\nbig == back => false! (precision lost in float's 23-bit mantissa)\n\n**Key insight:** `float` has only 7 significant decimal digits; `long` has 19. Large longs lose precision when cast to float.", "sampleInput": "long big = 1234567890123456789L; (long)(float)big == big", "sampleOutput": "false (precision loss)"},
    15: {"description": "Create a `SafeInt` class that wraps `int` and throws `ArithmeticException` on overflow instead of silently wrapping.\n\n**Example:**\nSafeInt.add(Integer.MAX_VALUE, 1) => throws ArithmeticException(\"Integer overflow\")\nSafeInt.add(100, 200) => 300\nSafeInt.multiply(100000, 100000) => throws ArithmeticException (> MAX_VALUE)", "sampleInput": "SafeInt.add(Integer.MAX_VALUE, 1)", "sampleOutput": "throws ArithmeticException(\"Integer overflow\")"},
    16: {"description": "Implement `NumberAccumulator<T extends Number>` that sums any `Number` subtype using `doubleValue()`.\n\n**Example:**\naccumulator.add(1); accumulator.add(2.5); accumulator.add(3L);\naccumulator.sum() => 6.5\naccumulator.average() => 2.1667\naccumulator.count() => 3\n\n**Key insight:** All `Number` subtypes have `doubleValue()` — use it for universal accumulation.", "sampleInput": "add(1, 2.5, 3L).sum()", "sampleOutput": "6.5"},
    17: {"description": "Implement unsigned integer operations in Java (which has no unsigned int primitive):\n\n**Example:**\nunsignedToLong(-1) => 4294967295L (max unsigned 32-bit)\nunsignedAdd(Integer.MAX_VALUE, 1) => 2147483648L (as unsigned)\nunsignedCompare(-1, 1) => positive (in unsigned, -1 is max value)\n\n**Key insight:** `Integer.toUnsignedLong(n)` converts to unsigned. `Integer.compareUnsigned(a, b)` treats both as unsigned.", "sampleInput": "unsignedToLong(-1)", "sampleOutput": "4294967295"},
    18: {"description": "Detect variable shadowing in nested scopes:\n\n```java\nint x = 10;\n{\n    int x = 20; // compile error: variable x is already defined\n}\n```\n\nBut in lambdas and inner classes:\n```java\nint x = 10;\nRunnable r = () -> { int x = 20; }; // compile error: effectively final captured\n```\n\nImplement `demonstrateShadowing()` showing legal vs illegal shadowing cases.", "sampleInput": "outer int x=10; inner int x=20;", "sampleOutput": "compile error: variable x already defined"},
    19: {"description": "Walk the type hierarchy of a given class using reflection: superclass chain + all implemented interfaces (recursively).\n\n**Example:**\nwalkHierarchy(ArrayList.class)\n=> ArrayList -> AbstractList -> AbstractCollection -> Object\n=> implements: List, RandomAccess, Cloneable, Serializable\n\nImplement `getFullHierarchy(Class<?> cls)` returning a `Map<String, List<String>>` with {superclasses, interfaces}.", "sampleInput": "walkHierarchy(ArrayList.class)", "sampleOutput": "{superclasses:[AbstractList,AbstractCollection,Object], interfaces:[List,RandomAccess,...]}"},
    20: {"description": "Build a quiz engine that presents type system questions and evaluates answers:\n\n**Example questions:**\n1. \"What is the range of byte?\" => \"-128 to 127\"\n2. \"Which is wider: long or float?\" => \"float (can represent larger magnitudes but with less precision)\"\n3. \"What does Integer.MAX_VALUE + 1 equal?\" => Integer.MIN_VALUE (overflow)\n\nImplement `QuizEngine` with `nextQuestion()` and `checkAnswer(String answer)` methods.", "sampleInput": "checkAnswer(\"Integer.MAX_VALUE + 1 = ?\")", "sampleOutput": "Integer.MIN_VALUE (-2147483648)"},
}

updated = 0
for topic in data['topics']:
    for p in topic.get('problems', []):
        o = p['displayOrder']
        if o in improvements:
            p['description'] = improvements[o]['description']
            p['sampleInput'] = improvements[o]['sampleInput']
            p['sampleOutput'] = improvements[o]['sampleOutput']
            updated += 1
with open(f, 'w', encoding='utf-8') as fh: json.dump(data, fh, indent=2, ensure_ascii=False)
print(f"B03 updated: {updated} problems")
