import json
f = 'C:/Dev/devlearner/devlearner/learning-system/src/main/resources/seeds/B12-inheritance.json'
with open(f, encoding='utf-8') as fh: data = json.load(fh)

improvements = {
    1: {"description": "Create a `Shape` base class with `double area()` and `double perimeter()`. Extend it with `Circle(double radius)` and `Rectangle(double width, double height)`.\n\n**Example 1:**\nnew Circle(5).area() => 78.54\nnew Circle(5).perimeter() => 31.42\n\n**Example 2:**\nnew Rectangle(4,6).area() => 24.0\nnew Rectangle(4,6).perimeter() => 20.0", "sampleInput": "new Circle(5)", "sampleOutput": "area=78.54, perimeter=31.42"},
    2: {"description": "Given this class hierarchy, predict the exact console output — constructors call `super()` implicitly:\n\n```java\nclass A { A() { System.out.println(\"A\"); } }\nclass B extends A { B() { System.out.println(\"B\"); } }\nclass C extends B { C() { System.out.println(\"C\"); } }\nnew C();\n```\n\n**Key insight:** Java calls the parent constructor first. `new C()` triggers A -> B -> C in order.", "sampleInput": "new C()", "sampleOutput": "A\nB\nC"},
    3: {"description": "Create `Animal` with `speak()` printing `\"...\"`. Extend with `Dog` overriding `speak()` to print `\"Woof\"` but also calling `super.speak()` first.\n\n**Example:**\nnew Dog().speak()\n=> prints \"...\"\n=> prints \"Woof\"\n\n**Key insight:** `super.method()` calls the parent implementation — useful for extending (not replacing) inherited behavior.", "sampleInput": "new Dog().speak()", "sampleOutput": "\"...\"\n\"Woof\""},
    4: {"description": "Implement `describeAnimal(Animal a)` that uses `instanceof` checks to print a specific description for `Dog`, `Cat`, and `Animal`.\n\n**Example 1:**\ndescribeAnimal(new Dog()) => \"This is a Dog, also an Animal\"\ndescribeAnimal(new Cat()) => \"This is a Cat, also an Animal\"\ndescribeAnimal(new Animal()) => \"Just an Animal\"\n\n**Key insight:** `instanceof` checks IS-A relationships — a Dog is also an Animal. Order matters: check most specific type first.", "sampleInput": "describeAnimal(new Dog())", "sampleOutput": "\"This is a Dog, also an Animal\""},
    5: {"description": "Each class in a hierarchy overrides `toString()` and calls `super.toString()` to build a chain:\n\n```java\nclass Vehicle  { toString() => \"Vehicle\" }\nclass Car extends Vehicle { toString() => super.toString() + \">Car\" }\nclass SportsCar extends Car { toString() => super.toString() + \">SportsCar\" }\n```\n\n**Example:**\nnew SportsCar().toString() => \"Vehicle>Car>SportsCar\"\n\n**Key insight:** Chaining `super.toString()` builds a descriptive breadcrumb of the full inheritance path.", "sampleInput": "new SportsCar().toString()", "sampleOutput": "\"Vehicle>Car>SportsCar\""},
    6: {"description": "Create a `Shape[]` array holding `Circle`, `Rectangle`, and `Triangle` objects. Loop over it calling `area()` on each — demonstrating runtime polymorphism.\n\n**Example:**\nShape[] shapes = { new Circle(3), new Rectangle(4,5), new Triangle(3,4,5) };\nfor (Shape s : shapes) System.out.println(s.area());\n=> 28.27\n=> 20.0\n=> 6.0\n\n**Key insight:** The array holds the supertype; each call dispatches to the correct subtype at runtime.", "sampleInput": "Shape[] {Circle(3), Rectangle(4,5), Triangle(3,4,5)}", "sampleOutput": "[28.27, 20.0, 6.0]"},
    7: {"description": "Create `Employee(String name, double baseSalary)` with `calculatePay()`. Extend with `FullTimeEmployee` (returns baseSalary) and `ContractEmployee(double hourlyRate, int hours)` (returns hourlyRate * hours).\n\n**Example 1:**\nnew FullTimeEmployee(\"Alice\", 5000).calculatePay() => 5000.0\n\n**Example 2:**\nnew ContractEmployee(\"Bob\", 50.0, 80).calculatePay() => 4000.0", "sampleInput": "new ContractEmployee(\"Bob\", 50.0, 80).calculatePay()", "sampleOutput": "4000.0"},
    8: {"description": "Create `abstract class PaymentProcessor` with `abstract void process(double amount)` and a concrete `logTransaction(double amount)`. Extend with `CreditCardProcessor` and `PayPalProcessor`.\n\n**Example:**\nnew CreditCardProcessor().process(99.99)\n=> \"[LOG] Processing $99.99\"\n=> \"Credit card charged: $99.99\"\n\nnew PayPalProcessor().process(50.0)\n=> \"[LOG] Processing $50.00\"\n=> \"PayPal transfer: $50.00\"", "sampleInput": "new CreditCardProcessor().process(99.99)", "sampleOutput": "\"[LOG] Processing $99.99\"\n\"Credit card charged: $99.99\""},
    9: {"description": "Create `Point(int x, int y)` with `equals()`/`hashCode()`. Extend with `Point3D(int x, int y, int z)` overriding both correctly.\n\n**Example:**\nnew Point3D(1,2,3).equals(new Point3D(1,2,3)) => true\nnew Point3D(1,2,3).equals(new Point(1,2)) => false\nnew HashSet<>().contains after add(new Point3D(1,2,3)) => true\n\n**Key insight:** Call `super.equals()` for parent fields, then check subclass fields. `hashCode` must include all fields.", "sampleInput": "new Point3D(1,2,3).equals(new Point3D(1,2,3))", "sampleOutput": "true"},
    10: {"description": "Demonstrate safe and unsafe downcasting:\n\n**Safe:** `Animal a = new Dog(); Dog d = (Dog) a;` — works\n**Unsafe:** `Animal a = new Cat(); Dog d = (Dog) a;` — throws `ClassCastException`\n\nImplement `safeCast(Animal a)` using `instanceof` guard before casting.\n\n**Example:**\nsafeCast(new Dog()) => \"Got a Dog\"\nsafeCast(new Cat()) => \"Not a Dog, skipping\"", "sampleInput": "safeCast(new Cat())", "sampleOutput": "\"Not a Dog, skipping\""},
    11: {"description": "Implement the **Template Method** pattern: `DataExporter` defines the algorithm skeleton (`export()` calls `readData()`, `processData()`, `writeOutput()` in order). `CsvExporter` and `JsonExporter` implement the abstract steps.\n\n**Example:**\nnew CsvExporter().export()\n=> \"Reading data...\"\n=> \"Processing for CSV...\"\n=> \"Writing CSV output\"\n\n**Key insight:** The parent defines WHEN to call each step; subclasses define HOW.", "sampleInput": "new CsvExporter().export()", "sampleOutput": "Reading data... / Processing for CSV... / Writing CSV output"},
    12: {"description": "Verify the Liskov Substitution Principle: a `Square extends Rectangle` violates LSP because `setWidth()` on a Square must also change height, breaking Rectangle's contract.\n\nDemonstrate the violation:\n```java\nRectangle r = new Square();\nr.setWidth(5); r.setHeight(3);\nr.area(); // expected 15, gets 9 — LSP violated\n```\n\nFix: don't extend Rectangle; use a common `Shape` interface instead.", "sampleInput": "Rectangle r = new Square(); r.setWidth(5); r.setHeight(3); r.area()", "sampleOutput": "9 (LSP violation — expected 15)"},
    13: {"description": "Demonstrate **covariant return types**: a subclass overrides a method and returns a more specific type.\n\n```java\nclass Animal { Animal create() { return new Animal(); } }\nclass Dog extends Animal { Dog create() { return new Dog(); } } // covariant\n```\n\n**Example:**\nnew Dog().create() returns a `Dog` (not just `Animal`)\nDog d = new Dog().create(); // no cast needed\n\n**Key insight:** Since Java 5, overriding methods may return a subtype — avoids casting at the call site.", "sampleInput": "new Dog().create().getClass().getSimpleName()", "sampleOutput": "\"Dog\""},
    14: {"description": "Model a `sealed` class hierarchy (Java 17+) where `Shape` permits only `Circle`, `Rectangle`, `Triangle`. Use pattern matching in a `switch` to compute area.\n\n**Example:**\nShape s = new Circle(5);\ndouble area = switch(s) {\n    case Circle c -> Math.PI * c.radius() * c.radius();\n    case Rectangle r -> r.w() * r.h();\n    case Triangle t -> 0.5 * t.base() * t.height();\n}; // => 78.54\n\n**Key insight:** Sealed classes make the `switch` exhaustive — compiler warns if a permitted subtype is missing.", "sampleInput": "new Circle(5) in sealed switch", "sampleOutput": "78.54"},
    15: {"description": "Java supports multiple interface inheritance. Create `Flyable` and `Swimmable` interfaces; implement `Duck` that implements both.\n\n**Example:**\nDuck d = new Duck();\nd.fly() => \"Duck flying\"\nd.swim() => \"Duck swimming\"\n\nFlyable f = new Duck(); f.fly(); // works\nSwimmable s = new Duck(); s.swim(); // works\n\n**Key insight:** A class can implement many interfaces — this is Java's answer to multiple inheritance for behavior mixing.", "sampleInput": "new Duck().fly()", "sampleOutput": "\"Duck flying\""},
    16: {"description": "Demonstrate the **fragile base class** problem: a base class changes a `protected` method, inadvertently breaking a subclass that calls it via `super`.\n\nShow that `private` methods in the base class prevent subclass interference, making the base class less fragile.\n\n**Example:**\nBase uses private helper — subclass override doesn't interfere\nBase uses protected helper — subclass override changes base behavior unexpectedly\n\n**Key insight:** Prefer `private` over `protected`. Expose only what subclasses truly need.", "sampleInput": "protected vs private method in base class", "sampleOutput": "private: safe; protected: fragile"},
    17: {"description": "Implement the **Visitor pattern** to operate on a Shape hierarchy without modifying Shape classes. `ShapeVisitor` has `visit(Circle)`, `visit(Rectangle)`. `AreaVisitor` and `PerimeterVisitor` implement it.\n\n**Example:**\nShapeVisitor area = new AreaVisitor();\nnew Circle(5).accept(area) => 78.54\nnew Rectangle(4,6).accept(area) => 24.0\n\n**Key insight:** Visitor adds new operations without touching existing classes — open/closed principle across a hierarchy.", "sampleInput": "new Circle(5).accept(new AreaVisitor())", "sampleOutput": "78.54"},
    18: {"description": "Demonstrate the difference between **method hiding** (static) and **method overriding** (instance):\n\n```java\nclass A { static void greet() { print(\"A static\"); } void hello() { print(\"A instance\"); } }\nclass B extends A { static void greet() { print(\"B static\"); } void hello() { print(\"B instance\"); } }\nA obj = new B();\nobj.greet(); // A static — HIDING: resolved at compile time\nobj.hello(); // B instance — OVERRIDING: resolved at runtime\n```", "sampleInput": "A obj = new B(); obj.greet(); obj.hello();", "sampleOutput": "\"A static\"\n\"B instance\""},
    19: {"description": "Build a 3-level payroll hierarchy: `Employee` -> `Manager(double bonus)` -> `Director(double stockOptions)`. Each level adds to `calculatePay()` by calling `super.calculatePay()` and adding its extra.\n\n**Example:**\nnew Director(\"Alice\", 5000, 2000, 10000).calculatePay()\n=> 5000 (base) + 2000 (bonus) + 10000 (stock) = 17000.0\n\n**Key insight:** `super.calculatePay()` at each level builds total compensation incrementally.", "sampleInput": "new Director(\"Alice\", 5000, 2000, 10000).calculatePay()", "sampleOutput": "17000.0"},
    20: {"description": "Replace an inheritance hierarchy with **composition**. Instead of `Car extends Engine`, use `Car HAS-A Engine`.\n\n**Before (inheritance):**\nclass ElectricCar extends Engine — wrong: a car IS NOT an engine\n\n**After (composition):**\nclass Car { private Engine engine; }\nnew Car(new ElectricEngine()).start() => \"Electric engine started\"\nnew Car(new PetrolEngine()).start() => \"Petrol engine started\"\n\n**Key insight:** Favour composition — it's more flexible, avoids tight coupling, and models HAS-A correctly.", "sampleInput": "new Car(new ElectricEngine()).start()", "sampleOutput": "\"Electric engine started\""},
}

updated = 0
for topic in data['topics']:
    for p in topic.get('problems', []):
        o = p['displayOrder']
        if o in improvements:
            p['description'] = improvements[o]['description']
            p['sampleInput'] = improvements[o]['sampleInput']
            p['sampleOutput'] = improvements[o]['sampleOutput']
            updated += 1
with open(f, 'w', encoding='utf-8') as fh: json.dump(data, fh, indent=2, ensure_ascii=False)
print(f"B12 updated: {updated} problems")
