import json, os

seed_dir = 'C:/Dev/devlearner/devlearner/learning-system/src/main/resources/seeds/'

batches = {
    'B23-wrapper-enums.json': {
        1: {"description": "Count word frequencies from a list of strings using `HashMap<String, Integer>`.\n\n**Example:**\ncountWords([\"apple\",\"banana\",\"apple\",\"cherry\",\"banana\",\"apple\"])\n=> {apple=3, banana=2, cherry=1}\n\n**Key insight:** `map.merge(word, 1, Integer::sum)` atomically increments count. `getOrDefault` is the alternative.", "sampleInput": "[\"apple\",\"banana\",\"apple\",\"cherry\",\"banana\",\"apple\"]", "sampleOutput": "{apple=3, banana=2, cherry=1}"},
        2: {"description": "Create a `DayType` enum with values MONDAY–SUNDAY. Implement `classify(DayType day)` returning \"Weekend\" or \"Weekday\".\n\n**Example:**\nclassify(DayType.SATURDAY) => \"Weekend\"\nclassify(DayType.MONDAY) => \"Weekday\"\nclassify(DayType.SUNDAY) => \"Weekend\"\n\n**Key insight:** Enums work naturally in `switch` expressions — each case is a compile-time constant.", "sampleInput": "classify(DayType.SATURDAY)", "sampleOutput": "\"Weekend\""},
        3: {"description": "Demonstrate the Integer autoboxing cache: `Integer.valueOf(n)` caches values in the range [-128, 127].\n\n**Example:**\nInteger a = 100; Integer b = 100;\na == b => true (cached)\nInteger c = 200; Integer d = 200;\nc == d => false (outside cache, new objects)\na.equals(b) => true (always)\nc.equals(d) => true (always)\n\n**Key insight:** Never use `==` to compare Integer objects — always use `.equals()` or `intValue()`.", "sampleInput": "Integer a=127; Integer b=127; a==b", "sampleOutput": "true"},
    },
    'B24-datetime-api.json': {
        1: {"description": "Calculate a person's age in years from their birth date to today using `java.time.LocalDate` and `Period`.\n\n**Example:**\ncalculateAge(LocalDate.of(1990, 5, 15)) => 34 (if today is 2024-11-01)\ncalculateAge(LocalDate.of(2000, 12, 31)) => 23\n\n**Key insight:** `Period.between(birthDate, LocalDate.now()).getYears()` — Period handles month/day boundaries correctly.", "sampleInput": "calculateAge(LocalDate.of(1990, 5, 15))", "sampleOutput": "34"},
        2: {"description": "Convert a datetime from IST (India Standard Time, UTC+5:30) to UTC using `ZonedDateTime`.\n\n**Example:**\nconvertToUTC(\"2024-01-15T14:30:00\", \"Asia/Kolkata\")\n=> 2024-01-15T09:00:00Z\n\nconvertToUTC(\"2024-06-01T00:00:00\", \"Asia/Kolkata\")\n=> 2024-05-31T18:30:00Z\n\n**Key insight:** `ZonedDateTime.of(dt, ZoneId.of(\"Asia/Kolkata\")).withZoneSameInstant(ZoneOffset.UTC)`", "sampleInput": "\"2024-01-15T14:30:00\" IST to UTC", "sampleOutput": "2024-01-15T09:00:00Z"},
        3: {"description": "Calculate how many days until a person's next birthday from today.\n\n**Example:**\nIf today is 2024-11-01 and birthday is May 15:\ndaysUntilNextBirthday(MonthDay.of(5, 15)) => 196\n\nIf birthday is today:\ndaysUntilNextBirthday(MonthDay.now()) => 0 (or 365 next year)\n\n**Key insight:** Find next occurrence of the birthday month/day at or after today. Use `MonthDay` to strip the year.", "sampleInput": "daysUntilNextBirthday(MonthDay.of(5,15)) from 2024-11-01", "sampleOutput": "196"},
    },
    'B25-garbage-collection.json': {
        1: {"description": "Identify the memory leak in this code and fix it:\n\n```java\nclass EventBus {\n    static List<Listener> listeners = new ArrayList<>();\n    static void register(Listener l) { listeners.add(l); }\n    // No deregister method!\n}\n```\n\nFix options:\n1. Add `static void deregister(Listener l) { listeners.remove(l); }`\n2. Use `List<WeakReference<Listener>>` — GC can collect listeners when no other references exist\n\nExplain why option 2 is safer for anonymous listeners.", "sampleInput": "register 10000 listeners, no deregister", "sampleOutput": "Fix: WeakReference<Listener> or explicit deregister()"},
        2: {"description": "Demonstrate the four reference types in Java and when each is collected:\n\n- `StrongReference`: never collected while referenced\n- `SoftReference<T>`: collected when JVM needs memory (good for caches)\n- `WeakReference<T>`: collected at next GC regardless of memory\n- `PhantomReference<T>`: collected after finalization\n\n**Example:**\nWeakReference<Object> weak = new WeakReference<>(new Object());\nSystem.gc();\nweak.get() => null (collected)", "sampleInput": "WeakReference<Object> after System.gc()", "sampleOutput": "weak.get() = null"},
        3: {"description": "Demonstrate the `ThreadLocal` memory leak in thread pools and how to fix it:\n\n**Leak:** Thread pool reuses threads. `ThreadLocal` values set during one task remain for the next task if not cleaned up.\n\n```java\nExecutorService pool = Executors.newFixedThreadPool(5);\npool.submit(() -> {\n    local.set(new LargeObject()); // set\n    // forgotten: local.remove(); // MUST clean up!\n});\n```\n\n**Fix:** Always call `local.remove()` in a finally block.\n\nImplement a wrapper `SafeThreadLocalTask` that auto-cleans.", "sampleInput": "ThreadLocal in pool without cleanup", "sampleOutput": "memory leak; Fix: local.remove() in finally"},
    },
    'B26-collections-internals.json': {
        1: {"description": "Group an array of strings by their anagram signature (sorted characters).\n\n**Example:**\ngroupAnagrams([\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"])\n=> [[\"eat\",\"tea\",\"ate\"],[\"tan\",\"nat\"],[\"bat\"]]\n\n**Internals:** HashMap uses `hashCode()` + `equals()` for keys. Sorted string as key: all anagrams have the same sorted form.", "sampleInput": "[\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]", "sampleOutput": "[[\"eat\",\"tea\",\"ate\"],[\"tan\",\"nat\"],[\"bat\"]]"},
        2: {"description": "Return the k most frequent elements using a min-heap of size k.\n\n**Example:**\ntopKFrequent([1,1,1,2,2,3], k=2) => [1,2]\n\n**Internals:** `PriorityQueue` is a binary min-heap. Maintain size k — if heap grows beyond k, poll the minimum. Remaining k elements are the top k.", "sampleInput": "topKFrequent([1,1,1,2,2,3], k=2)", "sampleOutput": "[1,2]"},
        3: {"description": "Sort a list of students by GPA descending, then by name ascending for ties.\n\n**Example:**\nsort([Student(Alice,3.9), Student(Bob,3.7), Student(Charlie,3.9)])\n=> [Alice(3.9), Charlie(3.9), Bob(3.7)]\n\n**Key insight:** `Comparator.comparingDouble(Student::getGpa).reversed().thenComparing(Student::getName)` chains multiple sort keys.", "sampleInput": "[Alice(3.9), Bob(3.7), Charlie(3.9)]", "sampleOutput": "[Alice(3.9), Charlie(3.9), Bob(3.7)]"},
    },
    'B27-reflection-annotations.json': {
        1: {"description": "Use reflection to find all methods annotated with `@Deprecated` in a given class.\n\n**Example:**\nfindDeprecated(OldApi.class)\n=> [\"OldApi.oldMethod1()\", \"OldApi.oldMethod2(String)\"]\n\n```java\nfor (Method m : cls.getDeclaredMethods()) {\n    if (m.isAnnotationPresent(Deprecated.class)) list.add(m.getName());\n}\n```", "sampleInput": "findDeprecated(OldApi.class)", "sampleOutput": "[\"oldMethod1\", \"oldMethod2\"]"},
        2: {"description": "Serialize an object to JSON using reflection — iterate `getDeclaredFields()` and build `{\"key\":\"value\"}` pairs.\n\n**Example:**\nclass Person { String name = \"Alice\"; int age = 30; }\ntoJson(new Person()) => {\"name\":\"Alice\",\"age\":30}\n\n**Key insight:** `field.setAccessible(true)` allows reading private fields. Use `field.get(obj)` to get the value.", "sampleInput": "toJson(new Person{name=Alice, age=30})", "sampleOutput": "{\"name\":\"Alice\",\"age\":30}"},
        3: {"description": "Create a `@Log` annotation and use reflection to automatically time annotated methods.\n\n**Example:**\n@Log\npublic String findUser(int id) { ... }\n\n// Aspect/proxy intercepts:\n\"findUser(42) executed in 15ms\"\n\nUse `java.lang.reflect.Proxy` or a simple `MethodInterceptor` pattern to measure and log execution time.", "sampleInput": "findUser(42) with @Log annotation", "sampleOutput": "\"findUser(42) executed in 15ms\""},
    },
    'B28-serialization.json': {
        1: {"description": "Fix a serialization bug: a class implements `Serializable` but has a non-serializable field that causes `NotSerializableException`.\n\n**Broken:**\n```java\nclass Config implements Serializable {\n    Connection conn; // not Serializable!\n}\n```\n\n**Fix:** Mark `conn` as `transient` — it's excluded from serialization.\n\n**Example:**\nserialize(new Config()) => works (conn is transient)\ndeserialize(bytes) => Config with conn=null (reconnect in readObject)", "sampleInput": "serialize Config with transient Connection", "sampleOutput": "No NotSerializableException; conn=null after deserialization"},
        2: {"description": "Deep clone an object using serialization/deserialization — no need to manually copy every field.\n\n**Example:**\nPerson original = new Person(\"Alice\", new Address(\"NYC\"));\nPerson clone = deepClone(original);\nclone.getAddress().setCity(\"LA\");\noriginal.getAddress().getCity() => \"NYC\" (deep copy — independent)\n\n**Key insight:** Serialize to `ByteArrayOutputStream`, deserialize from `ByteArrayInputStream` — copies entire object graph.", "sampleInput": "deepClone(Person{Alice, Address{NYC}})", "sampleOutput": "clone independent; original unchanged"},
        3: {"description": "Implement `Externalizable` for compact, custom serialization — write/read only essential fields.\n\n**Example:**\nclass Point implements Externalizable {\n    int x, y;\n    void writeExternal(ObjectOutput out) { out.writeInt(x); out.writeInt(y); }\n    void readExternal(ObjectInput in) { x = in.readInt(); y = in.readInt(); }\n}\n// 8 bytes (2 ints) vs Serializable's ~50+ bytes\n\nnew Point(3,4) serialized size => 8 bytes", "sampleInput": "serialize/deserialize Point(3,4) with Externalizable", "sampleOutput": "x=3, y=4; serialized size=8 bytes"},
    },
    'B29-completablefuture.json': {
        1: {"description": "Fetch data from 3 independent APIs in parallel and combine the results.\n\n**Example:**\nCompletableFuture<User> userFuture = CompletableFuture.supplyAsync(() -> fetchUser(1));\nCompletableFuture<List<Order>> ordersFuture = CompletableFuture.supplyAsync(() -> fetchOrders(1));\nCompletableFuture<Profile> profileFuture = CompletableFuture.supplyAsync(() -> fetchProfile(1));\n\nCompletableFuture.allOf(userFuture, ordersFuture, profileFuture).join();\nAggregatedResult result = combine(userFuture.get(), ordersFuture.get(), profileFuture.get());\n\n**Key insight:** `allOf` waits for all; `anyOf` waits for first. Parallel fetches cut total time from 3x to 1x serial latency.", "sampleInput": "3 parallel API calls, combine results", "sampleOutput": "AggregatedResult with all 3 fields"},
        2: {"description": "Add a timeout and fallback to a `CompletableFuture`:\n\n**Example:**\nCompletableFuture.supplyAsync(() -> slowExternalAPI())\n    .orTimeout(500, TimeUnit.MILLISECONDS)  // fail after 500ms\n    .exceptionally(e -> getDefaultValue())  // return fallback on any error\n    .get()\n=> If slow API takes >500ms: returns getDefaultValue()\n=> If fast: returns actual result\n\n**Key insight:** `.orTimeout()` completes exceptionally with `TimeoutException`. `.exceptionally()` catches all exceptions.", "sampleInput": "slowAPI() >500ms with orTimeout(500ms)", "sampleOutput": "getDefaultValue() returned"},
        3: {"description": "Compare sequential vs parallel execution time for 5 independent tasks each taking 200ms:\n\n**Sequential:**\ntask1() + task2() + ... + task5() = ~1000ms\n\n**Parallel:**\nCompletableFuture.allOf(cf1, cf2, cf3, cf4, cf5).join() = ~200ms\n\nImplement `compareExecutionTime()` returning `{sequential_ms, parallel_ms}` and verify parallel is ~5x faster.\n\n**Key insight:** `supplyAsync` uses the ForkJoinPool — tasks run on separate threads concurrently.", "sampleInput": "5 tasks * 200ms each: sequential vs parallel", "sampleOutput": "{sequential:~1000ms, parallel:~200ms}"},
    },
    'B30-locks-concurrency.json': {
        1: {"description": "Implement a thread-safe counter using `ReentrantLock` explicitly (instead of `synchronized`).\n\n**Example:**\nReentrantLock lock = new ReentrantLock();\nvoid increment() {\n    lock.lock();\n    try { count++; }\n    finally { lock.unlock(); } // always unlock in finally!\n}\n10 threads * 1000 increments => count = 10000\n\n**Key insight:** Always unlock in `finally` — if an exception occurs between lock and unlock, the lock would be held forever.", "sampleInput": "10 threads * 1000 increments with ReentrantLock", "sampleOutput": "10000"},
        2: {"description": "Implement a read-write cache using `ReentrantReadWriteLock`: concurrent reads, exclusive writes.\n\n**Example:**\nReadWriteLock rwLock = new ReentrantReadWriteLock();\nget(key): rwLock.readLock().lock() // multiple threads can read simultaneously\nput(key,val): rwLock.writeLock().lock() // exclusive — all readers block\n\n100 reader threads + 1 writer: readers proceed concurrently; writer gets exclusive access\n\n**Key insight:** Read-write lock doubles throughput for read-heavy workloads vs pure `synchronized`.", "sampleInput": "100 concurrent reads, 1 write", "sampleOutput": "reads all proceed concurrently; write is exclusive"},
        3: {"description": "Implement a database connection pool using `Semaphore(maxConnections)`.\n\n**Example:**\nSemaphore semaphore = new Semaphore(3); // 3 max connections\nConnectionPool pool = new ConnectionPool(3);\npool.acquire() x3 => success\npool.acquire() => blocks until one is released\npool.release(conn) => unblocks the waiting thread\n\n**Key insight:** Semaphore permits = available connections. `acquire()` blocks when 0 permits remain; `release()` adds a permit.", "sampleInput": "pool(3): acquire x4", "sampleOutput": "4th blocks until release"},
    },
    'B31-jdbc.json': {
        1: {"description": "Demonstrate SQL injection vulnerability and fix it with `PreparedStatement`.\n\n**Vulnerable:**\n```java\nString query = \"SELECT * FROM users WHERE name = '\" + input + \"'\";\n// input = \"'; DROP TABLE users; --\" => catastrophic!\n```\n\n**Safe:**\n```java\nPreparedStatement ps = conn.prepareStatement(\"SELECT * FROM users WHERE name = ?\");\nps.setString(1, input); // parameterized, safe\n```\n\n**Key insight:** PreparedStatement separates code from data — user input can never be interpreted as SQL.", "sampleInput": "input = \"'; DROP TABLE users; --\"", "sampleOutput": "PreparedStatement: safe (treated as literal string)"},
        2: {"description": "Insert 1000 records efficiently using JDBC batch insert instead of individual inserts.\n\n**Example:**\n// Slow: 1000 round trips\nfor (User u : users) stmt.executeUpdate(insert(u));\n\n// Fast: 1 round trip\nfor (User u : users) { ps.setString(1,u.name); ps.setInt(2,u.age); ps.addBatch(); }\nps.executeBatch(); // sends all 1000 in one call\n\n**Key insight:** Each `executeUpdate()` is a network round trip. `executeBatch()` bundles all into one — 10-100x faster for bulk inserts.", "sampleInput": "batch insert 1000 users", "sampleOutput": "1 executeBatch() call vs 1000 executeUpdate() calls"},
        3: {"description": "Calculate the optimal connection pool size for a given workload:\n\n**Formula (HikariCP recommendation):**\npool_size = (cpu_cores * 2) + effective_spindle_count\n\n**Example:**\ncalculatePoolSize(cores=4, spindleCount=1) => 9\ncalculatePoolSize(cores=8, spindleCount=1) => 17\n\n**Rule of thumb:** More connections != better. Too many connections cause context switching overhead. Most services need 5-20 connections.", "sampleInput": "calculatePoolSize(cores=4, spindleCount=1)", "sampleOutput": "9"},
    },
    'B32-optional-parallel.json': {
        1: {"description": "Safely extract a city from a nullable user object chain using `Optional`:\n\n**Example:**\nUser user = getUser(1); // may return null or have null address/city\nString city = Optional.ofNullable(user)\n    .map(User::getAddress)\n    .map(Address::getCity)\n    .orElse(\"Unknown\");\n\ngetCity(null) => \"Unknown\"\ngetCity(User{address=null}) => \"Unknown\"\ngetCity(User{Address{city=null}}) => \"Unknown\"\ngetCity(User{Address{city=\"NYC\"}}) => \"NYC\"", "sampleInput": "getCity(User{address=null})", "sampleOutput": "\"Unknown\""},
        2: {"description": "Count word frequency in a large text using a parallel stream.\n\n**Example:**\nMap<String,Long> freq = Arrays.stream(bigText.split(\"\\\\s+\"))\n    .parallel()\n    .collect(Collectors.groupingByConcurrent(w -> w.toLowerCase(), Collectors.counting()));\n\nParallel vs sequential on 1M words: parallel ~3x faster on 4-core machine.\n\n**Key insight:** Use `groupingByConcurrent` (thread-safe) not `groupingBy` with parallel streams.", "sampleInput": "parallel word count on \"the cat the cat java\"", "sampleOutput": "{the=2, cat=2, java=1}"},
        3: {"description": "Identify and fix a broken parallel stream that produces non-deterministic results:\n\n**Broken:**\n```java\nList<Integer> result = new ArrayList<>();\nnumbers.parallelStream().forEach(n -> result.add(n)); // NOT thread-safe!\n```\n\n**Fix options:**\n1. `collect(toList())` instead of `forEach` + mutable list\n2. Use `CopyOnWriteArrayList` or synchronized list\n3. Use `.sequential()` for side-effect operations\n\nFixed: `numbers.parallelStream().collect(Collectors.toList())`", "sampleInput": "parallelStream().forEach(result::add) on ArrayList", "sampleOutput": "Fix: use .collect(Collectors.toList())"},
    },
}

total_updated = 0
for filename, improvements in batches.items():
    fpath = seed_dir + filename
    with open(fpath, encoding='utf-8') as fh: data = json.load(fh)
    updated = 0
    for topic in data['topics']:
        for p in topic.get('problems', []):
            o = p['displayOrder']
            if o in improvements:
                p['description'] = improvements[o]['description']
                p['sampleInput'] = improvements[o]['sampleInput']
                p['sampleOutput'] = improvements[o]['sampleOutput']
                updated += 1
    with open(fpath, 'w', encoding='utf-8') as fh: json.dump(data, fh, indent=2, ensure_ascii=False)
    print(f"{filename}: {updated} problems updated")
    total_updated += updated

print(f"\nTotal: {total_updated} problems updated across {len(batches)} files")
