import json
f = 'C:/Dev/devlearner/devlearner/learning-system/src/main/resources/seeds/B19-streams-functional.json'
with open(f, encoding='utf-8') as fh: data = json.load(fh)

improvements = {
    1: {"description": "Use `Stream.filter()` to return only even numbers from a list.\n\n**Example 1:**\nfilterEvens([1,2,3,4,5,6]) => [2,4,6]\n\n**Example 2:**\nfilterEvens([1,3,5]) => []\n\n**Key insight:** `stream.filter(n -> n % 2 == 0).collect(toList())` — filter is lazy; elements are only processed when a terminal operation runs.", "sampleInput": "[1,2,3,4,5,6]", "sampleOutput": "[2,4,6]"},
    2: {"description": "Use `Stream.map()` to convert a list of names to uppercase.\n\n**Example 1:**\ntoUpperCase([\"alice\",\"bob\",\"charlie\"]) => [\"ALICE\",\"BOB\",\"CHARLIE\"]\n\n**Example 2:**\ntoUpperCase([]) => []\n\n**Key insight:** `stream.map(String::toUpperCase)` — map transforms each element independently. Method reference `String::toUpperCase` is equivalent to `s -> s.toUpperCase()`.", "sampleInput": "[\"alice\",\"bob\",\"charlie\"]", "sampleOutput": "[\"ALICE\",\"BOB\",\"CHARLIE\"]"},
    3: {"description": "Use `Stream.reduce()` to sum a list of integers.\n\n**Example 1:**\nsum([1,2,3,4,5]) => 15\n\n**Example 2:**\nsum([]) => 0 (identity value)\n\n**Example 3:**\nsum([10,20,30]) => 60\n\n**Key insight:** `stream.reduce(0, Integer::sum)` — identity is the starting value (0 for sum). Also achievable with `mapToInt().sum()`.", "sampleInput": "[1,2,3,4,5]", "sampleOutput": "15"},
    4: {"description": "Use `Collectors.groupingBy()` to group students by grade (A/B/C/F).\n\n**Example:**\ngroupByGrade([Student(Alice,92), Student(Bob,75), Student(Charlie,88), Student(Dave,61)])\n=> {A=[Alice,Charlie], B=[Bob], D=[Dave]}\n\n**Key insight:** `stream.collect(Collectors.groupingBy(Student::getGrade))` — groups elements by a classifier function into a Map.", "sampleInput": "[Alice(92),Bob(75),Charlie(88),Dave(61)]", "sampleOutput": "{A=[Alice,Charlie], B=[Bob], D=[Dave]}"},
    5: {"description": "Use `Stream.findFirst()` to return the first element matching a predicate.\n\n**Example 1:**\nfindFirstEven([1,3,5,4,6]) => Optional[4]\n\n**Example 2:**\nfindFirstEven([1,3,5]) => Optional.empty()\n\n**Key insight:** `findFirst()` short-circuits — stops processing as soon as a match is found. Returns `Optional` to handle the empty case safely.", "sampleInput": "[1,3,5,4,6]", "sampleOutput": "Optional[4]"},
    6: {"description": "Count distinct words in a sentence using streams.\n\n**Example 1:**\ncountDistinctWords(\"the cat sat on the mat the cat\") => 5\n\n**Example 2:**\ncountDistinctWords(\"\") => 0\n\n**Key insight:** `Arrays.stream(sentence.split(\" \")).distinct().count()` — `distinct()` removes duplicates using `equals()`.", "sampleInput": "\"the cat sat on the mat the cat\"", "sampleOutput": "5"},
    7: {"description": "Use `flatMap()` to flatten a `List<List<Integer>>` into a single `List<Integer>`.\n\n**Example 1:**\nflatten([[1,2],[3,4],[5]]) => [1,2,3,4,5]\n\n**Example 2:**\nflatten([[\"a\",\"b\"],[\"c\"]]) => [\"a\",\"b\",\"c\"]\n\n**Key insight:** `stream.flatMap(Collection::stream)` — `flatMap` maps each element to a stream, then flattens all streams into one.", "sampleInput": "[[1,2],[3,4],[5]]", "sampleOutput": "[1,2,3,4,5]"},
    8: {"description": "Return the top N elements sorted by a comparator using streams.\n\n**Example:**\ntopN([Student(Alice,92), Student(Bob,75), Student(Charlie,88)], n=2, byGpa)\n=> [Alice(92), Charlie(88)]\n\n**Key insight:** `stream.sorted(comparator.reversed()).limit(n).collect(toList())` — sort descending, take first N.", "sampleInput": "[Alice(92),Bob(75),Charlie(88)], n=2", "sampleOutput": "[Alice(92),Charlie(88)]"},
    9: {"description": "Build a word frequency map from a string using `Collectors.groupingBy` + `counting`.\n\n**Example:**\nwordFrequency(\"to be or not to be\")\n=> {to=2, be=2, or=1, not=1}\n\n**Key insight:** `stream.collect(Collectors.groupingBy(w->w, Collectors.counting()))` — group by identity, count each group.", "sampleInput": "\"to be or not to be\"", "sampleOutput": "{to=2, be=2, or=1, not=1}"},
    10: {"description": "Use `Collectors.partitioningBy()` to split a list into two groups.\n\n**Example:**\npartitionAdults([Person(Alice,17), Person(Bob,25), Person(Charlie,16), Person(Dave,30)])\n=> {false=[Alice,Charlie], true=[Bob,Dave]}\n\n**Key insight:** `partitioningBy` always returns a `Map<Boolean, List<T>>` — exactly two buckets: matching and non-matching.", "sampleInput": "[Alice(17),Bob(25),Charlie(16),Dave(30)]", "sampleOutput": "{false=[Alice,Charlie], true=[Bob,Dave]}"},
    11: {"description": "Use `IntStream` to compute statistics over an int array.\n\n**Example:**\nint[] data = {4,2,8,6,10};\nIntStream.of(data).average() => OptionalDouble[6.0]\nIntStream.of(data).sum() => 30\nIntStream.of(data).max() => OptionalInt[10]\nIntStream.of(data).min() => OptionalInt[2]\n\n**Key insight:** Primitive streams (`IntStream`, `LongStream`, `DoubleStream`) avoid boxing overhead and provide math operations.", "sampleInput": "IntStream.of(4,2,8,6,10)", "sampleOutput": "sum=30, avg=6.0, max=10, min=2"},
    12: {"description": "Use `Collectors.joining()` to build a formatted string from a list.\n\n**Example 1:**\njoin([\"Alice\",\"Bob\",\"Charlie\"], \", \", \"[\", \"]\") => \"[Alice, Bob, Charlie]\"\n\n**Example 2:**\njoin([\"a\",\"b\",\"c\"], \" | \", \"\", \"\") => \"a | b | c\"\n\n**Key insight:** `Collectors.joining(delimiter, prefix, suffix)` — builds a single string from stream elements with separators.", "sampleInput": "[\"Alice\",\"Bob\",\"Charlie\"], delimiter=\", \", prefix=\"[\", suffix=\"]\"", "sampleOutput": "\"[Alice, Bob, Charlie]\""},
    13: {"description": "Compose predicates dynamically using `Predicate.and()`, `or()`, `negate()`.\n\n**Example:**\nPredicate<Integer> isEven = n -> n % 2 == 0;\nPredicate<Integer> isPositive = n -> n > 0;\nPredicate<Integer> combined = isEven.and(isPositive);\nList.of(-2,3,4,-5,6).stream().filter(combined).collect(toList()) => [4,6]\n\n**Key insight:** Predicate composition builds complex filters from simple reusable parts — no nested if/else.", "sampleInput": "isEven.and(isPositive) on [-2,3,4,-5,6]", "sampleOutput": "[4,6]"},
    14: {"description": "Use nested `Collectors.groupingBy()` to group by two levels: first by department, then by seniority.\n\n**Example:**\ngroupByDeptAndLevel([Employee(Alice,Eng,Senior), Employee(Bob,Eng,Junior), Employee(Charlie,HR,Senior)])\n=> {Engineering={Senior=[Alice], Junior=[Bob]}, HR={Senior=[Charlie]}}\n\n**Key insight:** `groupingBy(dept, groupingBy(level))` creates `Map<String, Map<String, List<Employee>>>` — multi-dimensional grouping.", "sampleInput": "[Alice(Eng,Senior), Bob(Eng,Junior), Charlie(HR,Senior)]", "sampleOutput": "{Engineering={Senior=[Alice],Junior=[Bob]}, HR={Senior=[Charlie]}}"},
    15: {"description": "Implement a custom `Collector<Integer, ?, RunningStats>` that computes count, sum, mean, and variance in one pass.\n\n**Example:**\nList.of(2,4,4,4,5,5,7,9).stream().collect(new RunningStatsCollector())\n=> RunningStats{count=8, sum=40, mean=5.0, variance=4.0}\n\n**Key insight:** Custom collectors implement `Supplier`, `Accumulator`, `Combiner`, and `Finisher` — enables arbitrary reduction logic.", "sampleInput": "[2,4,4,4,5,5,7,9].stream().collect(RunningStatsCollector)", "sampleOutput": "mean=5.0, variance=4.0"},
    16: {"description": "Generate an infinite stream with `Stream.iterate()` or `Stream.generate()` and limit it.\n\n**Example 1:**\nStream.iterate(1, n->n*2).limit(8).collect(toList()) => [1,2,4,8,16,32,64,128]\n\n**Example 2:**\nStream.generate(Math::random).limit(3).count() => 3\n\n**Key insight:** Infinite streams are lazy — nothing is computed until `limit()` or another terminal operation constrains them.", "sampleInput": "Stream.iterate(1, n->n*2).limit(8)", "sampleOutput": "[1,2,4,8,16,32,64,128]"},
    17: {"description": "Count word frequency in a large file using a parallel stream.\n\n**Example:**\nMap<String,Long> freq = Files.lines(path)\n    .parallel()\n    .flatMap(line -> Arrays.stream(line.split(\"\\\\s+\")))\n    .collect(Collectors.groupingByConcurrent(w->w, Collectors.counting()));\n\n**Key insight:** Use `groupingByConcurrent` (not `groupingBy`) with parallel streams — it's thread-safe. `parallel()` splits the stream across CPU cores.", "sampleInput": "parallel word count on multi-line text", "sampleOutput": "Map<word, count> with all words counted"},
    18: {"description": "Simulate a SQL JOIN using streams: join `orders` with `customers` on `customerId`.\n\n**Example:**\njoin(customers, orders, Customer::getId, Order::getCustomerId, (c,o) -> c.name+\":\"+o.product)\n=> [\"Alice:Book\", \"Alice:Pen\", \"Bob:Laptop\"]\n\n**Key insight:** `orders.stream().flatMap(o -> customers.stream().filter(c->c.getId()==o.getCustomerId()).map(c->combine(c,o)))` — nested stream join, O(n*m).", "sampleInput": "join customers[Alice,Bob] with orders[Book@1,Pen@1,Laptop@2]", "sampleOutput": "[\"Alice:Book\", \"Alice:Pen\", \"Bob:Laptop\"]"},
    19: {"description": "Use `peek()` to inspect stream elements without consuming them, and demonstrate short-circuit with `anyMatch()`.\n\n**Example:**\nList.of(1,3,5,4,7).stream()\n    .peek(n -> System.out.println(\"checking: \"+n))\n    .anyMatch(n -> n % 2 == 0)\n=> prints \"checking: 1\", \"checking: 3\", \"checking: 5\", \"checking: 4\"\n=> stops at 4 (short-circuit)\n=> returns true\n\n**Key insight:** `anyMatch` stops as soon as a match is found — elements after are never processed.", "sampleInput": "[1,3,5,4,7].stream().peek(print).anyMatch(isEven)", "sampleOutput": "prints 1,3,5,4 then returns true (stops at 4)"},
    20: {"description": "Build a fluent query DSL using method chaining and streams:\n\n**Example:**\nnew Query<Employee>(employees)\n    .where(e -> e.getSalary() > 50000)\n    .orderBy(Comparator.comparing(Employee::getName))\n    .limit(5)\n    .select(Employee::getName)\n    .toList()\n=> [\"Alice\", \"Charlie\", \"Eve\"] (top 5 high-earners by name)\n\n**Key insight:** Each method stores a predicate/comparator and returns `this`. `toList()` triggers the stream pipeline.", "sampleInput": "where(salary>50k).orderBy(name).limit(5).select(name)", "sampleOutput": "[\"Alice\", \"Charlie\", \"Eve\"]"},
}

updated = 0
for topic in data['topics']:
    for p in topic.get('problems', []):
        o = p['displayOrder']
        if o in improvements:
            p['description'] = improvements[o]['description']
            p['sampleInput'] = improvements[o]['sampleInput']
            p['sampleOutput'] = improvements[o]['sampleOutput']
            updated += 1
with open(f, 'w', encoding='utf-8') as fh: json.dump(data, fh, indent=2, ensure_ascii=False)
print(f"B19 updated: {updated} problems")
