import json
f = 'C:/Dev/devlearner/devlearner/learning-system/src/main/resources/seeds/B14-abstraction.json'
with open(f, encoding='utf-8') as fh: data = json.load(fh)

improvements = {
    1: {"description": "Create `abstract class Vehicle` with `String fuelType`, a constructor, and `abstract double fuelEfficiency()`. Extend with `Car(double mpg)` and `Truck(double mpg, double loadFactor)`.\n\n**Example 1:**\nnew Car(35.0).fuelEfficiency() => 35.0\n\n**Example 2:**\nnew Truck(20.0, 0.8).fuelEfficiency() => 16.0 (mpg * loadFactor)\n\n**Key insight:** Abstract classes define shared state + partial implementation. Subclasses must fill in the abstract method.", "sampleInput": "new Truck(20.0, 0.8).fuelEfficiency()", "sampleOutput": "16.0"},
    2: {"description": "Create a `Greetable` interface with `default String greet(String name)` returning `\"Hello, \" + name`. Implement `FormalGreeter` that overrides it to return `\"Good day, \" + name`.\n\n**Example 1:**\nnew FormalGreeter().greet(\"Alice\") => \"Good day, Alice\"\n\n**Example 2:**\nnew InformalGreeter().greet(\"Bob\") => \"Hello, Bob\" (uses default)\n\n**Key insight:** Default methods let interfaces evolve without breaking existing implementations.", "sampleInput": "new FormalGreeter().greet(\"Alice\")", "sampleOutput": "\"Good day, Alice\""},
    3: {"description": "Show that abstract classes cannot be instantiated directly:\n\n```java\nabstract class Shape { abstract double area(); }\nnew Shape(); // => compile error\n```\n\nAlso show anonymous class instantiation as a workaround:\n```java\nShape s = new Shape() { double area() { return 0; } }; // OK\n```\n\nImplement `demonstrateAbstract()` returning the area of the anonymous shape.", "sampleInput": "new Shape() { double area() { return 42.0; } }.area()", "sampleOutput": "42.0"},
    4: {"description": "Create interface `MathUtils` with a `static int square(int n)` method. Call it directly on the interface without an instance.\n\n**Example:**\nMathUtils.square(5) => 25\nMathUtils.square(0) => 0\n\n**Key insight:** Interface static methods belong to the interface itself, not any implementing class — they cannot be overridden or inherited by implementing classes.", "sampleInput": "MathUtils.square(5)", "sampleOutput": "25"},
    5: {"description": "Create abstract `DataValidator` with `abstract boolean validate(String input)`. Subclasses `EmailValidator` and `PhoneValidator` must implement `validate()`.\n\n**Example:**\nnew EmailValidator().validate(\"user@example.com\") => true\nnew EmailValidator().validate(\"not-an-email\") => false\nnew PhoneValidator().validate(\"+1-800-555-0100\") => true\n\n**Key insight:** Abstract methods are a contract — the compiler enforces that every concrete subclass provides an implementation.", "sampleInput": "new EmailValidator().validate(\"user@example.com\")", "sampleOutput": "true"},
    6: {"description": "Show that an abstract class constructor runs before the subclass constructor:\n\n```java\nabstract class Base { Base() { System.out.println(\"Base init\"); setup(); } abstract void setup(); }\nclass Child extends Base { String name; Child() { super(); name = \"child\"; } void setup() { System.out.println(\"setup called, name=\" + name); } }\nnew Child();\n```\nOutput: \"Base init\" -> \"setup called, name=null\" -> then Child sets name.\n\n**Key insight:** Abstract class constructors run first — don't call overridable methods from a constructor (fields not yet initialised).", "sampleInput": "new Child()", "sampleOutput": "\"Base init\"\n\"setup called, name=null\""},
    7: {"description": "Implement `Comparable<Product>` for natural ordering by price ascending:\n\n**Example:**\nList<Product> list = new ArrayList<>(List.of(new Product(\"B\",20), new Product(\"A\",10)));\nCollections.sort(list);\nlist.get(0).getName() => \"A\" (cheapest first)\n\nAlso add a `Comparator.comparing(Product::getName)` for name-order.\n\n**Key insight:** `Comparable` = natural order (one per class). `Comparator` = alternate order (many possible).", "sampleInput": "[Product(B,$20), Product(A,$10)] sorted", "sampleOutput": "[Product(A,$10), Product(B,$20)]"},
    8: {"description": "Implement **Abstract Factory**: `UIFactory` interface with `createButton()` and `createCheckbox()`. `WindowsFactory` and `MacFactory` return platform-specific widgets.\n\n**Example:**\nUIFactory f = new WindowsFactory();\nf.createButton().render() => \"Windows Button\"\nf.createCheckbox().render() => \"Windows Checkbox\"\n\nUIFactory f2 = new MacFactory();\nf2.createButton().render() => \"Mac Button\"\n\n**Key insight:** Abstract Factory ensures all products from a factory are compatible with each other.", "sampleInput": "new WindowsFactory().createButton().render()", "sampleOutput": "\"Windows Button\""},
    9: {"description": "Create a class `FlyingFish` that implements both `Flyable` and `Swimmable` interfaces:\n\n**Example:**\nFlyingFish ff = new FlyingFish();\nff.fly() => \"FlyingFish soars\"\nff.swim() => \"FlyingFish dives\"\n\nFlyable f = ff; f.fly(); // works\nSwimmable s = ff; s.swim(); // works\n\n**Key insight:** A class can implement multiple interfaces — Java's safe answer to multiple inheritance. No ambiguity since interfaces define contracts, not state.", "sampleInput": "new FlyingFish().fly()", "sampleOutput": "\"FlyingFish soars\""},
    10: {"description": "Demonstrate that abstract classes prevent wrong instantiation. `AbstractPayment` validates that `amount > 0` in its constructor; subclasses cannot bypass this.\n\n**Example:**\nnew CreditPayment(-100) => throws IllegalArgumentException(\"Amount must be positive\")\nnew CreditPayment(50).process() => \"Processing credit $50.00\"\n\n**Key insight:** Shared validation in the abstract constructor runs for every subclass — a single enforcement point.", "sampleInput": "new CreditPayment(-100)", "sampleOutput": "throws IllegalArgumentException"},
    11: {"description": "Create a `sealed interface Shape` (Java 17) permitting `Circle`, `Rectangle`, `Triangle`. Use `switch` with pattern matching for exhaustive area calculation.\n\n**Example:**\ndouble area(Shape s) {\n    return switch(s) {\n        case Circle c -> Math.PI*c.r()*c.r();\n        case Rectangle r -> r.w()*r.h();\n        case Triangle t -> 0.5*t.b()*t.h();\n    };\n}\narea(new Circle(3)) => 28.27\n\n**Key insight:** Sealed + pattern matching = exhaustive switch checked at compile time. No default needed.", "sampleInput": "area(new Circle(3))", "sampleOutput": "28.27"},
    12: {"description": "Build a layered abstraction: `UserRepository` interface -> `UserService` depends only on the interface -> `MySqlUserRepository` implements it.\n\n**Example:**\nUserService svc = new UserService(new MySqlUserRepository());\nsvc.findByEmail(\"alice@example.com\") => User{name='Alice'}\n\nSwap implementation:\nnew UserService(new InMemoryUserRepository()) — no changes to UserService\n\n**Key insight:** Depend on abstractions (interfaces), not concretions. Swapping implementations requires zero changes to higher layers.", "sampleInput": "UserService with InMemoryRepo.findByEmail(\"alice@example.com\")", "sampleOutput": "User{name='Alice'}"},
    13: {"description": "Add a `default` method to an existing interface without breaking existing implementations:\n\n```java\ninterface Formatter { String format(String s); }\n// Add later:\ndefault String formatAll(List<String> items) {\n    return items.stream().map(this::format).collect(joining(\", \"));\n}\n```\n\n**Example:**\nnew UpperFormatter().formatAll(List.of(\"a\",\"b\",\"c\")) => \"A, B, C\"\n\n**Key insight:** `default` methods allow interface evolution without breaking existing implementations — the key tool for backwards-compatible API changes.", "sampleInput": "new UpperFormatter().formatAll([\"a\",\"b\",\"c\"])", "sampleOutput": "\"A, B, C\""},
    14: {"description": "Implement `abstract class FormBuilder` with abstract `validateFields()` and `submitForm()`. `build()` calls both in order. Subclass `LoginFormBuilder` validates email+password fields.\n\n**Example:**\nnew LoginFormBuilder(\"user@example.com\", \"pass123\").build()\n=> validates OK\n=> \"Login form submitted\"\n\nnew LoginFormBuilder(\"\", \"pass\").build()\n=> throws ValidationException(\"Email required\")", "sampleInput": "new LoginFormBuilder(\"\", \"pass\").build()", "sampleOutput": "throws ValidationException(\"Email required\")"},
    15: {"description": "Create abstract `Iterator<T>` with `abstract boolean hasNext()` and `abstract T next()`. Implement `RangeIterator(int start, int end)` iterating integers from start to end-1.\n\n**Example:**\nIterator<Integer> it = new RangeIterator(1, 4);\nwhile (it.hasNext()) System.out.print(it.next() + \" \");\n=> 1 2 3\n\n**Key insight:** Abstract Iterator defines the contract; concrete class provides the data source. The consumer only uses the abstract API.", "sampleInput": "RangeIterator(1,4) iterated", "sampleOutput": "1 2 3"},
    16: {"description": "Two interfaces provide conflicting `default` methods with the same signature. The implementing class must override to resolve the **diamond problem**:\n\n```java\ninterface A { default String greet() { return \"Hello from A\"; } }\ninterface B { default String greet() { return \"Hello from B\"; } }\nclass C implements A, B {\n    public String greet() { return A.super.greet() + \" and \" + B.super.greet(); }\n}\nnew C().greet() => \"Hello from A and Hello from B\"\n```", "sampleInput": "new C().greet()", "sampleOutput": "\"Hello from A and Hello from B\""},
    17: {"description": "Create `abstract class Container<T>` with abstract `void add(T item)` and `abstract T get(int index)`. Extend with `TypedList<T>` backed by `ArrayList<T>`.\n\n**Example:**\nContainer<String> c = new TypedList<>();\nc.add(\"hello\");\nc.add(\"world\");\nc.get(0) => \"hello\"\nc.get(1) => \"world\"\n\n**Key insight:** Generic abstract classes let you define type-safe skeletons — subclasses inherit the type parameter.", "sampleInput": "Container<String>.add(\"hello\").get(0)", "sampleOutput": "\"hello\""},
    18: {"description": "Create `abstract class Animal` with concrete `breathe()` and abstract `speak()`. Then interface `Trainable` with `train()`. `Dog` extends `Animal` and implements `Trainable`.\n\n**Example:**\nDog d = new Dog();\nd.breathe() => \"breathing...\"\nd.speak() => \"Woof!\"\nd.train() => \"Dog trained\"\n\n**Key insight:** Abstract class + interface together: abstract class provides shared state/implementation; interface adds capability contracts.", "sampleInput": "new Dog().speak()", "sampleOutput": "\"Woof!\""},
    19: {"description": "Model a file system where `FileSystemNode` is abstract with `getName()` and `abstract long size()`. `File(long bytes)` and `Directory(List<FileSystemNode> children)` extend it. Directory size = sum of children.\n\n**Example:**\nDirectory root = new Directory(\"root\", List.of(\n    new File(\"a.txt\", 100),\n    new Directory(\"sub\", List.of(new File(\"b.txt\", 200)))));\nroot.size() => 300\n\n**Key insight:** Recursive structure — Directory.size() calls size() on each child, which may itself be a Directory.", "sampleInput": "root with File(100) + Dir(File(200))", "sampleOutput": "300"},
    20: {"description": "Create `abstract class QueryBuilder` with chainable abstract methods `select()`, `from()`, `where()`. Each returns `this`. `SqlQueryBuilder` and `NoSqlQueryBuilder` implement concrete versions.\n\n**Example:**\nnew SqlQueryBuilder()\n    .select(\"name,email\")\n    .from(\"users\")\n    .where(\"age > 18\")\n    .build()\n=> \"SELECT name,email FROM users WHERE age > 18\"\n\n**Key insight:** Fluent abstract builder — the chain stays typed to the subclass via covariant returns.", "sampleInput": "SqlQueryBuilder.select(\"name\").from(\"users\").where(\"age>18\").build()", "sampleOutput": "\"SELECT name FROM users WHERE age > 18\""},
}

updated = 0
for topic in data['topics']:
    for p in topic.get('problems', []):
        o = p['displayOrder']
        if o in improvements:
            p['description'] = improvements[o]['description']
            p['sampleInput'] = improvements[o]['sampleInput']
            p['sampleOutput'] = improvements[o]['sampleOutput']
            updated += 1
with open(f, 'w', encoding='utf-8') as fh: json.dump(data, fh, indent=2, ensure_ascii=False)
print(f"B14 updated: {updated} problems")
