import json, os

seed_dir = 'C:/Dev/devlearner/devlearner/learning-system/src/main/resources/seeds/'

ALL_IMPROVEMENTS = {

'D01-linked-list.json': {
    1: {"description": "Reverse a singly linked list iteratively or recursively.\n\n**Example 1:**\nInput: 1->2->3->4->5\nOutput: 5->4->3->2->1\n\n**Example 2:**\nInput: 1->2\nOutput: 2->1\n\n**Key insight:** Three pointers: prev=null, curr=head, next. Each step: save next, point curr->prev, advance prev and curr.", "sampleInput": "1->2->3->4->5", "sampleOutput": "5->4->3->2->1"},
    2: {"description": "Detect if a linked list has a cycle using Floyd's fast/slow pointer algorithm.\n\n**Example 1:**\n1->2->3->4->2 (cycle back to node 2) => true\n\n**Example 2:**\n1->2->3->null => false\n\n**Key insight:** Slow moves 1 step, fast moves 2. If they ever meet, there's a cycle. If fast reaches null, no cycle. O(n) time, O(1) space.", "sampleInput": "1->2->3->4->2 (cycle)", "sampleOutput": "true"},
    3: {"description": "Find the middle node of a linked list. If even length, return the second middle.\n\n**Example 1:**\n1->2->3->4->5 => node 3\n\n**Example 2:**\n1->2->3->4 => node 3 (second middle)\n\n**Key insight:** Slow/fast pointers — when fast reaches end, slow is at middle.", "sampleInput": "1->2->3->4->5", "sampleOutput": "node 3"},
    4: {"description": "Merge two sorted linked lists into one sorted list.\n\n**Example 1:**\nInput: 1->2->4 and 1->3->4\nOutput: 1->1->2->3->4->4\n\n**Example 2:**\nInput: [] and [0]\nOutput: 0\n\n**Key insight:** Dummy head simplifies edge cases. Compare heads, attach smaller, advance that pointer.", "sampleInput": "1->2->4 and 1->3->4", "sampleOutput": "1->1->2->3->4->4"},
    5: {"description": "Remove the nth node from the end of a linked list in one pass.\n\n**Example 1:**\nInput: 1->2->3->4->5, n=2\nOutput: 1->2->3->5\n\n**Example 2:**\nInput: [1], n=1\nOutput: []\n\n**Key insight:** Two pointers gap of n. When fast reaches end, slow.next is the node to remove.", "sampleInput": "1->2->3->4->5, n=2", "sampleOutput": "1->2->3->5"},
    6: {"description": "Check if a linked list is a palindrome in O(n) time and O(1) space.\n\n**Example 1:**\n1->2->2->1 => true\n1->2->3->2->1 => true\n1->2 => false\n\n**Key insight:** Find middle, reverse second half, compare with first half, restore.", "sampleInput": "1->2->2->1", "sampleOutput": "true"},
    7: {"description": "Add two numbers represented as reversed linked lists (each node = one digit).\n\n**Example:**\nInput: (2->4->3) + (5->6->4)\nRepresents: 342 + 465 = 807\nOutput: 7->0->8\n\n**Key insight:** Process digit by digit with carry. Create new node for each sum. Don't forget final carry node.", "sampleInput": "2->4->3 and 5->6->4", "sampleOutput": "7->0->8"},
    8: {"description": "Design an LRU Cache with O(1) `get(key)` and `put(key, value)`. Evict least recently used when over capacity.\n\n**Example:**\ncache = LRUCache(2)\nput(1,1), put(2,2), get(1) => 1\nput(3,3) // evicts key 2\nget(2) => -1\n\n**Key insight:** HashMap + doubly linked list. Map gives O(1) access; list maintains recency order.", "sampleInput": "capacity=2, put(1,1),put(2,2),get(1),put(3,3),get(2)", "sampleOutput": "-1"},
    9: {"description": "Clone a linked list where each node has `next` and a `random` pointer.\n\n**Example:**\nNode 1: next->2, random->2\nNode 2: next->null, random->2\n=> Deep copy with same structure\n\n**Key insight:** Two passes: (1) create copy nodes interleaved, (2) set random pointers, (3) separate lists.", "sampleInput": "[1,random=2]->[2,random=2]", "sampleOutput": "deep copy with same pointers"},
    10: {"description": "Flatten a multilevel doubly linked list where nodes may have a child list.\n\n**Example:**\n1 - 2 - 3 - 4 - 5 - 6\n        |   (child)\n        7 - 8 - 9 - 10\n\nOutput: 1-2-3-7-8-9-10-4-5-6\n\n**Key insight:** At each node with a child: insert child list between current and next.", "sampleInput": "1->2->3->4 with child 7->8->9 at node 3", "sampleOutput": "1->2->3->7->8->9->4"},
},

'D02-stack-queue.json': {
    1: {"description": "Return true if the bracket string is valid — every opening bracket has a matching closing bracket in the right order.\n\n**Example 1:**\nisValid(\"()[]{}\") => true\nisValid(\"([)]\") => false\nisValid(\"{[]}\") => true\n\n**Key insight:** Push opening brackets. On closing bracket, pop and check match.", "sampleInput": "\"{[]}\"", "sampleOutput": "true"},
    2: {"description": "Design a stack that supports `push`, `pop`, `top`, and `getMin` — all in O(1).\n\n**Example:**\nMinStack s;\ns.push(-2); s.push(0); s.push(-3);\ns.getMin() => -3\ns.pop();\ns.getMin() => -2\n\n**Key insight:** Maintain a parallel min-stack. Each push also pushes current minimum.", "sampleInput": "push(-2,0,-3), getMin(), pop(), getMin()", "sampleOutput": "[-3, -2]"},
    3: {"description": "Given temperatures array, return array where `result[i]` is the number of days until a warmer temperature.\n\n**Example:**\ndailyTemperatures([73,74,75,71,69,72,76,73]) => [1,1,4,2,1,1,0,0]\n\n**Key insight:** Monotonic decreasing stack of indices. When current temp > stack top's temp, pop and record distance.", "sampleInput": "[73,74,75,71,69,72,76,73]", "sampleOutput": "[1,1,4,2,1,1,0,0]"},
    4: {"description": "Implement a queue using two stacks with amortized O(1) enqueue and dequeue.\n\n**Example:**\nMyQueue q;\nq.push(1); q.push(2);\nq.peek() => 1\nq.pop() => 1\nq.empty() => false\n\n**Key insight:** Stack1 for push. Stack2 for pop (lazy transfer: dump stack1 into stack2 only when stack2 is empty).", "sampleInput": "push(1,2), peek(), pop()", "sampleOutput": "peek=1, pop=1"},
    5: {"description": "Find the largest rectangle area in a histogram.\n\n**Example 1:**\nlargestRectangle([2,1,5,6,2,3]) => 10\nlargestRectangle([2,4]) => 4\n\n**Key insight:** Monotonic increasing stack. Pop when current bar is shorter. Area = height[popped] * width (right - stack.peek() - 1).", "sampleInput": "[2,1,5,6,2,3]", "sampleOutput": "10"},
    6: {"description": "Return the max of every sliding window of size k.\n\n**Example:**\nslidingWindowMax([1,3,-1,-3,5,3,6,7], k=3) => [3,3,5,5,6,7]\n\n**Key insight:** Monotonic deque (decreasing). Remove from front if out of window; remove from back while smaller than current.", "sampleInput": "[1,3,-1,-3,5,3,6,7], k=3", "sampleOutput": "[3,3,5,5,6,7]"},
    7: {"description": "For each element in `nums1`, find the next greater element in `nums2`.\n\n**Example:**\nnums1=[4,1,2], nums2=[1,3,4,2]\nnextGreater => [-1,3,-1]\n(4: no greater in nums2; 1: 3 is next greater; 2: no greater)\n\n**Key insight:** Monotonic stack over nums2. HashMap stores {element -> next greater}.", "sampleInput": "nums1=[4,1,2], nums2=[1,3,4,2]", "sampleOutput": "[-1,3,-1]"},
    8: {"description": "Evaluate an expression in Reverse Polish Notation.\n\n**Example 1:**\nevalRPN([\"2\",\"1\",\"+\",\"3\",\"*\"]) => 9 ((2+1)*3)\neval([\"4\",\"13\",\"5\",\"/\",\"+\"]) => 6 (4+(13/5))\n\n**Key insight:** Stack — push numbers. On operator, pop two, apply, push result. Division truncates toward zero.", "sampleInput": "[\"2\",\"1\",\"+\",\"3\",\"*\"]", "sampleOutput": "9"},
    9: {"description": "Design a circular queue with `enQueue(val)`, `deQueue()`, `Front()`, `Rear()`, `isEmpty()`, `isFull()`.\n\n**Example:**\ncq = CircularQueue(3)\ncq.enQueue(1); cq.enQueue(2); cq.enQueue(3);\ncq.isFull() => true\ncq.deQueue(); cq.enQueue(4);\ncq.Rear() => 4", "sampleInput": "enQueue(1,2,3), deQueue(), enQueue(4), Rear()", "sampleOutput": "4"},
    10: {"description": "Implement a stack using only two queues.\n\n**Example:**\nMyStack s;\ns.push(1); s.push(2);\ns.top() => 2\ns.pop() => 2\ns.empty() => false\n\n**Key insight:** On push: enqueue to q2, then dump all of q1 into q2, swap q1 and q2. Top of stack is front of q1.", "sampleInput": "push(1,2), top(), pop()", "sampleOutput": "top=2, pop=2"},
},

'D03-trees.json': {
    1: {"description": "Find the maximum depth (height) of a binary tree.\n\n**Example 1:**\nTree: [3,9,20,null,null,15,7] => 3\nTree: [1,null,2] => 2\n\n**Key insight:** `1 + max(depth(left), depth(right))`. Base case: null => 0.", "sampleInput": "[3,9,20,null,null,15,7]", "sampleOutput": "3"},
    2: {"description": "Invert a binary tree (mirror it).\n\n**Example:**\nInput: [4,2,7,1,3,6,9]\nOutput: [4,7,2,9,6,3,1]\n\n**Key insight:** Swap left and right children at each node, recursively. One line: `node.left, node.right = invert(node.right), invert(node.left)`", "sampleInput": "[4,2,7,1,3,6,9]", "sampleOutput": "[4,7,2,9,6,3,1]"},
    3: {"description": "Validate if a binary tree is a valid BST: left subtree < node < right subtree at every node.\n\n**Example 1:**\n[2,1,3] => true\n[5,1,4,null,null,3,6] => false (right child 4 < root 5)\n\n**Key insight:** Pass min/max bounds down the recursion. Each node must be strictly within (min, max).", "sampleInput": "[5,1,4,null,null,3,6]", "sampleOutput": "false"},
    4: {"description": "Find the Lowest Common Ancestor of two nodes in a BST.\n\n**Example 1:**\nBST: [6,2,8,0,4,7,9], p=2, q=8 => 6\np=2, q=4 => 2\n\n**Key insight:** In BST, if both p and q < node, go left. If both > node, go right. Otherwise, current node is LCA.", "sampleInput": "BST=[6,2,8,0,4,7,9], p=2, q=8", "sampleOutput": "6"},
    5: {"description": "Return nodes of a binary tree level by level (BFS).\n\n**Example:**\nInput: [3,9,20,null,null,15,7]\nOutput: [[3],[9,20],[15,7]]\n\n**Key insight:** BFS with queue. Process each level by recording queue size at level start, then dequeue exactly that many nodes.", "sampleInput": "[3,9,20,null,null,15,7]", "sampleOutput": "[[3],[9,20],[15,7]]"},
    6: {"description": "Find the diameter of a binary tree — longest path between any two nodes (may not pass through root).\n\n**Example:**\nTree: [1,2,3,4,5] => 3 (path 4->2->1->3 or 5->2->1->3)\n\n**Key insight:** At each node, diameter through it = depth(left) + depth(right). Track global maximum.", "sampleInput": "[1,2,3,4,5]", "sampleOutput": "3"},
    7: {"description": "Serialize a binary tree to a string and deserialize it back.\n\n**Example:**\nserialize([1,2,3,null,null,4,5]) => \"1,2,null,null,3,4,null,null,5,null,null\"\ndeserialize(str) => same tree\n\n**Key insight:** Pre-order DFS with null markers. Deserialization uses a queue of tokens.", "sampleInput": "serialize then deserialize [1,2,3,null,null,4,5]", "sampleOutput": "inorder = [2,1,4,3,5]"},
    8: {"description": "Find the maximum path sum in a binary tree. A path can start and end at any node.\n\n**Example 1:**\n[1,2,3] => 6 (2->1->3)\n[-10,9,20,null,null,15,7] => 42 (15->20->7)\n\n**Key insight:** At each node, max gain going up = node.val + max(0, left_gain, right_gain). Track global max = node + left_gain + right_gain.", "sampleInput": "[-10,9,20,null,null,15,7]", "sampleOutput": "42"},
    9: {"description": "Find all root-to-leaf paths that sum to a target value.\n\n**Example:**\nTree=[5,4,8,11,null,13,4,7,2,null,null,5,1], targetSum=22\nOutput: [[5,4,11,2],[5,8,4,5]]\n\n**Key insight:** DFS with running sum. When leaf is reached and sum == target, record the path. Backtrack after returning.", "sampleInput": "[5,4,8,11,null,13,4,7,2,null,null,5,1], target=22", "sampleOutput": "[[5,4,11,2],[5,8,4,5]]"},
    10: {"description": "Return binary tree level-order traversal in zigzag order (left-to-right, then right-to-left, alternating).\n\n**Example:**\n[3,9,20,null,null,15,7] => [[3],[20,9],[15,7]]\n\n**Key insight:** BFS level-order, but every other level reverse the result list before appending.", "sampleInput": "[3,9,20,null,null,15,7]", "sampleOutput": "[[3],[20,9],[15,7]]"},
    11: {"description": "Count the total number of nodes in a complete binary tree in O(log^2 n) time.\n\n**Example:**\n[1,2,3,4,5,6] => 6\n\n**Key insight:** For a complete binary tree, compute left height and right height. If equal, left subtree is perfect (2^h - 1 nodes). Recurse into the non-perfect subtree only.", "sampleInput": "[1,2,3,4,5,6]", "sampleOutput": "6"},
    12: {"description": "Place the minimum number of cameras on tree nodes such that every node is monitored. A camera monitors its parent, itself, and its children.\n\n**Example 1:**\n[0,0,null,0,0] => 1\n[0,0,null,0,null,0,null,null,0] => 2\n\n**Key insight:** Greedy post-order DFS. Install camera at parent of unmonitored leaf — covers more nodes.", "sampleInput": "[0,0,null,0,0]", "sampleOutput": "1"},
},

'D04-heaps-priority-queues.json': {
    1: {"description": "Return the kth largest element in an unsorted array.\n\n**Example 1:**\nfindKthLargest([3,2,1,5,6,4], k=2) => 5\nfindKthLargest([3,2,3,1,2,4,5,5,6], k=4) => 4\n\n**Key insight:** Min-heap of size k. Iterate array: push, if size > k pop the minimum. Heap top = kth largest. O(n log k).", "sampleInput": "[3,2,1,5,6,4], k=2", "sampleOutput": "5"},
    2: {"description": "Return the k most frequent elements.\n\n**Example 1:**\ntopKFrequent([1,1,1,2,2,3], k=2) => [1,2]\ntopKFrequent([1], k=1) => [1]\n\n**Key insight:** Build frequency map, then use min-heap of size k keeping highest-frequency elements. O(n log k).", "sampleInput": "[1,1,1,2,2,3], k=2", "sampleOutput": "[1,2]"},
    3: {"description": "Support `addNum(int num)` and `findMedian()` from a running data stream.\n\n**Example:**\nstream.addNum(1); stream.addNum(2);\nstream.findMedian() => 1.5\nstream.addNum(3);\nstream.findMedian() => 2.0\n\n**Key insight:** Two heaps: max-heap for lower half, min-heap for upper half. Median is top of larger heap or average of both tops.", "sampleInput": "addNum(1,2,3) then findMedian()", "sampleOutput": "2.0"},
    4: {"description": "Merge k sorted linked lists into one sorted list.\n\n**Example:**\nInput: [[1,4,5],[1,3,4],[2,6]]\nOutput: 1->1->2->3->4->4->5->6\n\n**Key insight:** Min-heap of (value, listIndex, nodePointer). Poll minimum, advance that list's pointer, push next node. O(n log k).", "sampleInput": "[[1,4,5],[1,3,4],[2,6]]", "sampleOutput": "1->1->2->3->4->4->5->6"},
    5: {"description": "Given a list of tasks with cooldown n between same tasks, return minimum time to execute all.\n\n**Example 1:**\ntaskScheduler([\"A\",\"A\",\"A\",\"B\",\"B\",\"B\"], n=2) => 8 (A->B->idle->A->B->idle->A->B)\ntaskScheduler([\"A\",\"A\",\"A\",\"B\",\"B\",\"B\"], n=0) => 6\n\n**Key insight:** Max-heap by frequency. Each round: execute up to n+1 tasks, fill remaining with idle.", "sampleInput": "[A,A,A,B,B,B], n=2", "sampleOutput": "8"},
    6: {"description": "Return the k points closest to the origin (0,0).\n\n**Example 1:**\nkClosest([[1,3],[-2,2]], k=1) => [[-2,2]] (dist=sqrt(8) < sqrt(10))\nkClosest([[3,3],[5,-1],[-2,4]], k=2) => [[3,3],[-2,4]]\n\n**Key insight:** Max-heap of size k by distance. Pop when size > k. Remaining k points are closest.", "sampleInput": "[[1,3],[-2,2]], k=1", "sampleOutput": "[[-2,2]]"},
    7: {"description": "Find the nth ugly number (positive integer whose only prime factors are 2, 3, or 5).\n\n**Example:**\nnthUgly(10) => 12 (sequence: 1,2,3,4,5,6,8,9,10,12)\nnthUgly(1) => 1\n\n**Key insight:** Min-heap starting with {1}. Pop min, push min*2, min*3, min*5 (avoid duplicates with a set).", "sampleInput": "nthUgly(10)", "sampleOutput": "12"},
    8: {"description": "Rearrange string so no two adjacent characters are the same. Return empty string if impossible.\n\n**Example 1:**\nreorganize(\"aab\") => \"aba\"\nreorganize(\"aaab\") => \"\" (impossible)\n\n**Key insight:** Max-heap by frequency. Always place the most frequent character, then the second most frequent. Refill heap.", "sampleInput": "\"aab\"", "sampleOutput": "\"aba\""},
    9: {"description": "Maximize capital: given k projects with profits and capitals, start with w capital, pick the k most profitable projects you can afford.\n\n**Example:**\nfindMaxCapital(k=2, w=0, profits=[1,2,3], capital=[0,1,1])\n=> 4 (start w=0: pick profit=1 -> w=1; pick profit=3 -> w=4)\n\n**Key insight:** Min-heap of available projects by capital; max-heap of profits for affordable ones.", "sampleInput": "k=2, w=0, profits=[1,2,3], capital=[0,1,1]", "sampleOutput": "4"},
    10: {"description": "Given a list of employees' work intervals, find the free time intervals common to all employees.\n\n**Example:**\nemployees=[[[1,3],[6,7]],[[2,4]],[[2,5],[9,12]]]\nfreeTime => [[5,6],[7,9]]\n\n**Key insight:** Merge all intervals (across all employees), then find gaps between merged intervals.", "sampleInput": "[[[1,3],[6,7]],[[2,4]],[[2,5],[9,12]]]", "sampleOutput": "[[5,6],[7,9]]"},
},

'D05-graphs.json': {
    1: {"description": "Count the number of islands in a 2D grid of '1' (land) and '0' (water).\n\n**Example 1:**\ngrid = [[1,1,0],[0,1,0],[0,0,1]] => 2\n\n**Key insight:** DFS from each unvisited '1', mark all connected land as visited. Each DFS start = one island.", "sampleInput": "[[1,1,0],[0,1,0],[0,0,1]]", "sampleOutput": "2"},
    2: {"description": "Clone a connected undirected graph. Each node has a val and list of neighbors.\n\n**Example:**\nInput: Node(1) connected to Node(2), Node(2) connected to Node(1)\nOutput: Deep copy with same adjacency\n\n**Key insight:** BFS/DFS with a HashMap<original, clone> to avoid infinite loops and enable reconnecting.", "sampleInput": "Node(1)<->Node(2)", "sampleOutput": "clone with same structure"},
    3: {"description": "Detect if you can finish all courses given prerequisite pairs (detect cycle in directed graph).\n\n**Example 1:**\ncanFinish(2, [[1,0]]) => true (take 0 then 1)\ncanFinish(2, [[1,0],[0,1]]) => false (circular dependency)\n\n**Key insight:** Topological sort (Kahn's algorithm or DFS). Cycle = not all nodes processed.", "sampleInput": "numCourses=2, prerequisites=[[1,0],[0,1]]", "sampleOutput": "false"},
    4: {"description": "Find the shortest travel time from node k to all other nodes using Dijkstra's algorithm.\n\n**Example:**\ntimes=[[2,1,1],[2,3,1],[3,4,1]], n=4, k=2\n=> Answer is max of all shortest paths = 2 (all nodes reachable in ≤ 2 steps)\n\n**Key insight:** Min-heap Dijkstra: (dist, node). Relax edges when shorter path found.", "sampleInput": "times=[[2,1,1],[2,3,1],[3,4,1]], n=4, k=2", "sampleOutput": "2"},
    5: {"description": "Count the number of connected components in an undirected graph.\n\n**Example:**\nn=5, edges=[[0,1],[1,2],[3,4]] => 2 components ({0,1,2} and {3,4})\n\n**Key insight:** Union-Find or BFS/DFS. Each time we start a new BFS/DFS on an unvisited node, it's a new component.", "sampleInput": "n=5, edges=[[0,1],[1,2],[3,4]]", "sampleOutput": "2"},
    6: {"description": "Find the shortest transformation sequence from beginWord to endWord, changing one letter at a time (each word must be in wordList).\n\n**Example 1:**\nwordLadder(\"hit\",\"cog\",[\"hot\",\"dot\",\"dog\",\"lot\",\"log\",\"cog\"]) => 5\nhit->hot->dot->dog->cog\n\n**Key insight:** BFS from beginWord. At each step, try all 26 letter substitutions. Each valid word is a BFS neighbor.", "sampleInput": "beginWord=hit, endWord=cog, wordList=[hot,dot,dog,lot,log,cog]", "sampleOutput": "5"},
},

'D06-sorting-algorithms.json': {
    1: {"description": "Sort an array of integers by implementing merge sort.\n\n**Example:**\nsortArray([5,2,3,1]) => [1,2,3,5]\nsortArray([5,1,1,2,0,0]) => [0,0,1,1,2,5]\n\n**Key insight:** Divide array in half, recursively sort each half, merge sorted halves. O(n log n) time, O(n) space.", "sampleInput": "[5,2,3,1]", "sampleOutput": "[1,2,3,5]"},
    2: {"description": "Merge overlapping intervals.\n\n**Example 1:**\nmerge([[1,3],[2,6],[8,10],[15,18]]) => [[1,6],[8,10],[15,18]]\nmerge([[1,4],[4,5]]) => [[1,5]]\n\n**Key insight:** Sort by start. If current.start <= last.end, merge (extend end). Otherwise add new interval.", "sampleInput": "[[1,3],[2,6],[8,10],[15,18]]", "sampleOutput": "[[1,6],[8,10],[15,18]]"},
    3: {"description": "For each number in an array, count how many smaller numbers are to its right.\n\n**Example:**\ncountSmaller([5,2,6,1]) => [2,1,1,0]\n\n**Key insight:** Modified merge sort — during merge, count how many right-half elements go before each left-half element.", "sampleInput": "[5,2,6,1]", "sampleOutput": "[2,1,1,0]"},
    4: {"description": "Find the minimum number of conference rooms needed to schedule all meetings.\n\n**Example 1:**\nmeetingRooms([[0,30],[5,10],[15,20]]) => 2\nmeetingRooms([[7,10],[2,4]]) => 1\n\n**Key insight:** Sort by start. Min-heap of end times — if current start >= heap.peek(), reuse room; else add room.", "sampleInput": "[[0,30],[5,10],[15,20]]", "sampleOutput": "2"},
    5: {"description": "Given a list of non-negative integers, arrange them to form the largest number.\n\n**Example 1:**\nlargestNumber([10,2]) => \"210\"\nlargestNumber([3,30,34,5,9]) => \"9534330\"\n\n**Key insight:** Custom comparator: compare `a+b` vs `b+a` as strings. Sort descending by this comparator.", "sampleInput": "[3,30,34,5,9]", "sampleOutput": "\"9534330\""},
    6: {"description": "Sort an array of 0s, 1s, and 2s in-place in one pass (Dutch National Flag).\n\n**Example:**\nsortColors([2,0,2,1,1,0]) => [0,0,1,1,2,2]\n\n**Key insight:** Three pointers: low, mid, high. Swap 0s to front, 2s to back, 1s stay in middle.", "sampleInput": "[2,0,2,1,1,0]", "sampleOutput": "[0,0,1,1,2,2]"},
    7: {"description": "Sort characters in a string by their frequency (most frequent first).\n\n**Example 1:**\nfrequencySort(\"tree\") => \"eert\" or \"eetr\"\nfrequencySort(\"cccaaa\") => \"cccaaa\" or \"aaaccc\"\n\n**Key insight:** Build frequency map, sort by frequency descending, build result string.", "sampleInput": "\"tree\"", "sampleOutput": "\"eert\""},
    8: {"description": "Sort a linked list using merge sort in O(n log n) time and O(1) extra space.\n\n**Example:**\nInput: 4->2->1->3\nOutput: 1->2->3->4\n\n**Key insight:** Find middle (slow/fast pointer), split, sort each half, merge. Bottom-up merge sort achieves O(1) space.", "sampleInput": "4->2->1->3", "sampleOutput": "1->2->3->4"},
    9: {"description": "Find the kth smallest element in an n x n matrix where each row and column is sorted.\n\n**Example 1:**\nmatrix=[[1,5,9],[10,11,13],[12,13,15]], k=8 => 13\n\n**Key insight:** Min-heap initialized with first column. Pop k times, push next element in that row.", "sampleInput": "[[1,5,9],[10,11,13],[12,13,15]], k=8", "sampleOutput": "13"},
    10: {"description": "Find the maximum gap between successive elements in a sorted version of an unsorted array in O(n) time.\n\n**Example 1:**\nmaximumGap([3,6,9,1]) => 3\nmaximumGap([10]) => 0\n\n**Key insight:** Bucket sort — divide range into n-1 buckets. Maximum gap must span across at least one empty bucket.", "sampleInput": "[3,6,9,1]", "sampleOutput": "3"},
    11: {"description": "Rearrange array so that nums[0] < nums[1] > nums[2] < nums[3]... (wiggle sort with large/small alternation).\n\n**Example:**\nwiggleSort([1,5,1,1,6,4]) => [1,6,1,5,1,4]\nwiggleSort([1,3,2,2,3,1]) => [2,3,1,3,1,2]\n\n**Key insight:** Find the median (nth_element), then 3-way partition, interleave.", "sampleInput": "[1,5,1,1,6,4]", "sampleOutput": "[1,6,1,5,1,4]"},
    12: {"description": "Sort an array using pancake flipping — at each step, reverse a prefix of length k.\n\n**Example:**\npancakeSort([3,2,4,1]) => flip operations that sort to [1,2,3,4]\nOutput: list of k values for each flip\n\n**Key insight:** Find max, flip it to front, flip to its target position. Repeat for n-1, n-2... 1.", "sampleInput": "[3,2,4,1]", "sampleOutput": "[4,2,4,3] (flip lengths to sort)"},
},

'D07-dynamic-programming.json': {
    1: {"description": "Count distinct ways to climb n stairs (1 or 2 steps at a time).\n\n**Example:**\nclimbStairs(2) => 2\nclimbStairs(3) => 3\nclimbStairs(5) => 8\n\n**Key insight:** dp[i] = dp[i-1] + dp[i-2]. Base cases: dp[1]=1, dp[2]=2. Fibonacci variant.", "sampleInput": "5", "sampleOutput": "8"},
    2: {"description": "Rob houses without robbing adjacent ones — maximize total stolen amount.\n\n**Example 1:**\nrob([1,2,3,1]) => 4 (rob house 1 and 3)\nrob([2,7,9,3,1]) => 12\n\n**Key insight:** dp[i] = max(dp[i-1], dp[i-2] + nums[i]). Can optimize to O(1) space with two variables.", "sampleInput": "[2,7,9,3,1]", "sampleOutput": "12"},
    3: {"description": "Find minimum number of coins to make target amount.\n\n**Example 1:**\ncoinChange([1,5,11], 15) => 3 (5+5+5)\ncoinChange([2], 3) => -1 (impossible)\n\n**Key insight:** dp[amount] = min coins to make 'amount'. For each coin, dp[i] = min(dp[i], dp[i-coin]+1).", "sampleInput": "coins=[1,5,11], amount=15", "sampleOutput": "3"},
    4: {"description": "Find the length of the longest strictly increasing subsequence.\n\n**Example 1:**\nlis([10,9,2,5,3,7,101,18]) => 4 ([2,3,7,101])\nlis([0,1,0,3,2,3]) => 4\n\n**Key insight:** O(n log n): maintain a patience sorting array. Binary search for position of each element.", "sampleInput": "[10,9,2,5,3,7,101,18]", "sampleOutput": "4"},
    5: {"description": "Find the minimum number of edit operations (insert, delete, replace) to transform word1 to word2.\n\n**Example 1:**\neditDistance(\"horse\", \"ros\") => 3\neditDistance(\"intention\", \"execution\") => 5\n\n**Key insight:** dp[i][j] = edit distance for word1[0..i] and word2[0..j]. If chars match, dp[i][j]=dp[i-1][j-1]; else 1+min(insert,delete,replace).", "sampleInput": "\"horse\", \"ros\"", "sampleOutput": "3"},
    6: {"description": "Determine if a string can be segmented into words from a dictionary.\n\n**Example 1:**\nwordBreak(\"leetcode\", [\"leet\",\"code\"]) => true\nwordBreak(\"catsandog\", [\"cats\",\"dog\",\"sand\",\"and\",\"cat\"]) => false\n\n**Key insight:** dp[i] = true if s[0..i] can be segmented. For each j < i, if dp[j] && s[j..i] in dict, dp[i]=true.", "sampleInput": "\"leetcode\", [\"leet\",\"code\"]", "sampleOutput": "true"},
    7: {"description": "Count the number of unique paths from top-left to bottom-right of an m x n grid (only right and down moves).\n\n**Example 1:**\nuniquePaths(3,7) => 28\nuniquePaths(3,2) => 3\n\n**Key insight:** dp[i][j] = dp[i-1][j] + dp[i][j-1]. First row and column are all 1s. Or: C(m+n-2, m-1).", "sampleInput": "m=3, n=7", "sampleOutput": "28"},
    8: {"description": "Find the length of the longest common subsequence of two strings.\n\n**Example 1:**\nlcs(\"abcde\", \"ace\") => 3 (\"ace\")\nlcs(\"abc\", \"abc\") => 3\nlcs(\"abc\", \"def\") => 0\n\n**Key insight:** dp[i][j] = LCS of s1[0..i] and s2[0..j]. If chars match, dp[i][j]=dp[i-1][j-1]+1; else max(dp[i-1][j], dp[i][j-1]).", "sampleInput": "\"abcde\", \"ace\"", "sampleOutput": "3"},
    9: {"description": "Determine if an array can be partitioned into two subsets with equal sum.\n\n**Example 1:**\ncanPartition([1,5,11,5]) => true ([1,5,5] and [11])\ncanPartition([1,2,3,5]) => false\n\n**Key insight:** Target = totalSum/2. DP: dp[j] = can we make sum j. For each num, update dp from target down.", "sampleInput": "[1,5,11,5]", "sampleOutput": "true"},
    10: {"description": "Count the number of ways to decode a string of digits to letters (1->A, ..., 26->Z).\n\n**Example 1:**\ndecodeWays(\"12\") => 2 (AB or L)\ndecodeWays(\"226\") => 3 (BBF, BZ, VF)\ndecodeWays(\"06\") => 0\n\n**Key insight:** dp[i] = dp[i-1] (single digit) + dp[i-2] (two-digit if 10-26). Guard against leading zeros.", "sampleInput": "\"226\"", "sampleOutput": "3"},
    11: {"description": "You have a row of balloons with numbers. Burst all of them. Bursting balloon i gives coins = left * nums[i] * right. Maximize coins.\n\n**Example:**\nburst([3,1,5,8]) => 167\n(burst 1: 3*1*5=15; burst 5: 3*5*8=120; burst 3: 1*3*8=24; burst 8: 1*8*1=8; total=167)\n\n**Key insight:** Interval DP — dp[l][r] = max coins from bursting all balloons between l and r.", "sampleInput": "[3,1,5,8]", "sampleOutput": "167"},
},

'D08-recursion-backtracking.json': {
    1: {"description": "Return all subsets of a set of unique integers (the power set).\n\n**Example:**\nsubsets([1,2,3]) => [[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]\n\n**Key insight:** For each element, choose to include or exclude. Recursion branches at each element.", "sampleInput": "[1,2,3]", "sampleOutput": "[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]"},
    2: {"description": "Return all permutations of an array of distinct integers.\n\n**Example:**\npermute([1,2,3]) => [[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]\n\n**Key insight:** Backtrack: swap current with each remaining, recurse, swap back.", "sampleInput": "[1,2,3]", "sampleOutput": "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]"},
    3: {"description": "Find all combinations of numbers that sum to target (numbers can be reused).\n\n**Example:**\ncombinationSum([2,3,6,7], 7) => [[2,2,3],[7]]\ncombinationSum([2,3,5], 8) => [[2,2,2,2],[2,3,3],[3,5]]\n\n**Key insight:** Backtrack from each candidate. Allow reuse by not advancing the start index on recursive call.", "sampleInput": "[2,3,6,7], target=7", "sampleOutput": "[[2,2,3],[7]]"},
    4: {"description": "Count the number of valid N-Queens arrangements.\n\n**Example:**\nnQueens(4) => 2\nnQueens(8) => 92\n\n**Key insight:** Place one queen per row. Track columns, diagonals, anti-diagonals as sets. Prune invalid placements.", "sampleInput": "4", "sampleOutput": "2"},
    5: {"description": "Return all possible letter combinations from phone number digits (2-9).\n\n**Example:**\nletterCombinations(\"23\") => [\"ad\",\"ae\",\"af\",\"bd\",\"be\",\"bf\",\"cd\",\"ce\",\"cf\"]\nletterCombinations(\"\") => []\n\n**Key insight:** Backtrack over each digit's letters. Map: 2->abc, 3->def, etc.", "sampleInput": "\"23\"", "sampleOutput": "[\"ad\",\"ae\",\"af\",\"bd\",\"be\",\"bf\",\"cd\",\"ce\",\"cf\"]"},
    6: {"description": "Partition a string such that every substring is a palindrome. Return all partitions.\n\n**Example:**\npartition(\"aab\") => [[\"a\",\"a\",\"b\"],[\"aa\",\"b\"]]\npartition(\"a\") => [[\"a\"]]\n\n**Key insight:** Backtrack: try each prefix. If it's a palindrome, recurse on the suffix.", "sampleInput": "\"aab\"", "sampleOutput": "[[\"a\",\"a\",\"b\"],[\"aa\",\"b\"]]"},
    7: {"description": "Generate all combinations of n pairs of well-formed parentheses.\n\n**Example:**\ngenerateParentheses(3) => [\"((()))\",\"(()())\",\"(())()\",\"()(())\",\"()()()\"]  \ngenerateParentheses(1) => [\"()\"]\n\n**Key insight:** Track open and close counts. Add '(' if open < n; add ')' if close < open.", "sampleInput": "3", "sampleOutput": "[\"((()))\",\"(()())\",\"(())()\",\"()(())\",\"()()()\"]"},
    8: {"description": "Search for a word in a 2D grid of characters — path uses adjacent cells (up/down/left/right), each cell used at most once.\n\n**Example:**\nboard=[[A,B,C,E],[S,F,C,S],[A,D,E,E]], word=\"ABCCED\" => true\nword=\"SEE\" => true, word=\"ABCB\" => false\n\n**Key insight:** DFS with backtracking. Mark visited cells, unmark on return.", "sampleInput": "board=[[A,B,C,E],[S,F,C,S],[A,D,E,E]], word=\"ABCCED\"", "sampleOutput": "true"},
    9: {"description": "Solve a Sudoku puzzle by filling in the empty cells ('.') with digits 1-9.\n\n**Example:**\nGiven a 9x9 board with some cells filled, fill the rest such that each row, column, and 3x3 box has 1-9 each.\n\n**Key insight:** Backtrack: for each empty cell, try digits 1-9. Check row/col/box validity. Backtrack if stuck.", "sampleInput": "9x9 board with some cells filled", "sampleOutput": "fully solved valid Sudoku"},
    10: {"description": "Find a knight's tour: visit every square of an n x n chessboard exactly once using knight moves.\n\n**Example:**\nknightTour(5) => one valid tour (or detect if impossible)\n\n**Key insight:** Backtrack with Warnsdorff's heuristic: at each step, choose the move with fewest onward moves (reduces dead ends).", "sampleInput": "n=5", "sampleOutput": "valid 25-step tour"},
},

'D09-trie-advanced-trees.json': {
    1: {"description": "Implement a Trie with `insert(word)`, `search(word)`, and `startsWith(prefix)`.\n\n**Example:**\ntrie.insert(\"apple\"); trie.search(\"apple\") => true; trie.search(\"app\") => false; trie.startsWith(\"app\") => true\n\n**Key insight:** Each node has a char map to children and an `isEnd` flag. Search and prefix differ only in whether isEnd matters.", "sampleInput": "insert(\"apple\"), search(\"app\"), startsWith(\"app\")", "sampleOutput": "search=false, startsWith=true"},
    2: {"description": "Given a 2D board and a list of words, find all words that exist in the board (adjacent cells, no reuse).\n\n**Example:**\nboard=[[o,a,a,n],[e,t,a,e],[i,h,k,r],[i,f,l,v]], words=[\"oath\",\"pea\",\"eat\",\"rain\"]\n=> [\"eat\",\"oath\"]\n\n**Key insight:** Build Trie from words, then DFS from each cell. Prune branches not in Trie.", "sampleInput": "board=4x4, words=[oath,pea,eat,rain]", "sampleOutput": "[\"eat\",\"oath\"]"},
    3: {"description": "Support point update and range sum query on an array using a Fenwick Tree (BIT).\n\n**Example:**\nnums=[1,3,5,7,9,11]\nsumRange(0,2) => 9 (1+3+5)\nupdate(1, 2) // nums[1] += 2 => nums=[1,5,5,7,9,11]\nsumRange(0,2) => 11\n\n**Key insight:** BIT stores partial sums. Update in O(log n) via index += index & (-index). Query via prefix sum.", "sampleInput": "[1,3,5,7,9,11], sumRange(0,2), update(1,2), sumRange(0,2)", "sampleOutput": "[9, 11]"},
    4: {"description": "Implement a trie supporting `addWord(word)` and `search(word)` where '.' matches any letter.\n\n**Example:**\nwd.addWord(\"bad\"); wd.addWord(\"dad\"); wd.addWord(\"mad\");\nwd.search(\"pad\") => false\nwd.search(\".ad\") => true\nwd.search(\"b..\") => true\n\n**Key insight:** On '.', recurse into all children. Regular characters follow normal Trie traversal.", "sampleInput": "addWord(bad,dad,mad), search(\".ad\")", "sampleOutput": "true"},
    5: {"description": "Find the maximum XOR of any two numbers in an array using a Binary Trie.\n\n**Example:**\nfindMaximumXOR([3,10,5,25,2,8]) => 28 (5 XOR 25 = 28)\n\n**Key insight:** Build a Trie of binary representations. For each number, greedily choose the opposite bit at each level to maximize XOR.", "sampleInput": "[3,10,5,25,2,8]", "sampleOutput": "28"},
    6: {"description": "Replace each word in a sentence with the shortest root from a dictionary that is a prefix of that word.\n\n**Example:**\nreplaceWords([\"cat\",\"bat\",\"rat\"], \"the cattle was rattled by the battery\")\n=> \"the cat was rat by the bat\"\n\n**Key insight:** Build Trie from roots. For each word, search Trie for the shortest matching prefix.", "sampleInput": "roots=[cat,bat,rat], sentence=\"the cattle was rattled by the battery\"", "sampleOutput": "\"the cat was rat by the bat\""},
    7: {"description": "Return the longest word in a dictionary that can be built character by character (each prefix must also exist in the dictionary).\n\n**Example:**\nlongestWord([\"w\",\"wo\",\"wor\",\"worl\",\"world\"]) => \"world\"\nlongestWord([\"a\",\"banana\",\"app\",\"appl\",\"ap\",\"apply\",\"apple\"]) => \"apple\"\n\n**Key insight:** Build Trie, BFS/DFS checking that each node's word was built step by step.", "sampleInput": "[\"w\",\"wo\",\"wor\",\"worl\",\"world\"]", "sampleOutput": "\"world\""},
    8: {"description": "Insert `(key, val)` pairs into a Trie-based map and sum all values whose keys have a given prefix.\n\n**Example:**\nmapSum.insert(\"apple\", 3); mapSum.insert(\"app\", 2);\nmapSum.sum(\"ap\") => 5 (apple:3 + app:2)\nmapSum.sum(\"b\") => 0\n\n**Key insight:** Each Trie node stores a value. `sum(prefix)` = DFS summing all values below the prefix node.", "sampleInput": "insert(apple,3), insert(app,2), sum(\"ap\")", "sampleOutput": "5"},
    9: {"description": "Design an autocomplete system: given historical sentences with frequencies, return top 3 matching sentences as user types.\n\n**Example:**\nsystem = AutocompleteSystem([\"i love you\",\"island\",\"iroman\"],[5,3,2])\nsystem.input('i') => [\"i love you\",\"island\",\"iroman\"]\nsystem.input(' ') => [\"i love you\"]\nsystem.input('#') => [] (saves new sentence)\n\n**Key insight:** Trie with frequency map at each node. On '#', save the typed sentence.", "sampleInput": "input('i') then input(' ')", "sampleOutput": "[\"i love you\", \"island\", \"iroman\"] then [\"i love you\"]"},
    10: {"description": "Answer range minimum queries on a static array using a Segment Tree.\n\n**Example:**\nnums=[1,3,5,7,9,11]\nqueryMin(0,5) => 1\nqueryMin(1,3) => 3\nupdate(2, 0) // nums[2]=0\nqueryMin(0,5) => 0\n\n**Key insight:** Segment tree stores min for each range. Build O(n), query and update O(log n).", "sampleInput": "[1,3,5,7,9,11], queryMin(1,3), update(2,0), queryMin(0,5)", "sampleOutput": "[3, 0]"},
    11: {"description": "Find all index pairs [i,j] in a text string that match any string from a list of words.\n\n**Example:**\nindexPairs(\"thestoryofleetcodeandme\", [\"story\",\"fleet\",\"leetcode\"])\n=> [[3,7],[10,17],[10,14]]\n\n**Key insight:** Build Trie from words. Scan text starting at each index, following Trie until no match or word end.", "sampleInput": "text=\"thestoryofleetcodeandme\", words=[\"story\",\"fleet\",\"leetcode\"]", "sampleOutput": "[[3,7],[10,17],[10,14]]"},
    12: {"description": "Count the number of range sums S(i,j) = nums[i]+...+nums[j] that lie in [lower, upper].\n\n**Example:**\ncountRangeSum([-2,5,-1], lower=-2, upper=2) => 3\n(subarrays: [-2], [-1], [-2,5,-1]=2)\n\n**Key insight:** Prefix sums + merge sort. Count pairs (i,j) where prefix[j] - prefix[i] is in range.", "sampleInput": "[-2,5,-1], lower=-2, upper=2", "sampleOutput": "3"},
},

'D10-complexity-analysis.json': {
    1: {"description": "Determine the Big-O complexity of these code snippets:\n\n```java\n// Snippet 1:\nfor(int i=0;i<n;i++) for(int j=i;j<n;j++) sum++;\n// Snippet 2:\nint i=1; while(i<n) i*=2;\n// Snippet 3:\nfor(int i=0;i<n;i++) binarySearch(arr, target);\n```\n\n**Answers:** O(n^2), O(log n), O(n log n)\n\nImplement `analyze(String code)` returning the complexity.", "sampleInput": "nested loop i,j=i..n", "sampleOutput": "O(n^2)"},
    2: {"description": "Compare two implementations of Two Sum: O(n^2) brute force vs O(n) HashMap.\n\n**Example:**\ntwoSumBrute([2,7,11,15], 9) => [0,1] — O(n^2): check all pairs\ntwoSumHash([2,7,11,15], 9) => [0,1] — O(n): HashMap lookup\n\nBenchmark both for n=10000:\nbrute: ~100ms, hash: ~1ms\n\nReturn both results and execution times.", "sampleInput": "[2,7,11,15], target=9", "sampleOutput": "both return [0,1]; hash is ~100x faster"},
    3: {"description": "Count the number of operations in each algorithm and predict which is faster for n=1000:\n\n1. `bubbleSort(arr)` — O(n^2) worst case\n2. `mergeSort(arr)` — O(n log n)\n3. `binarySearch(sorted, target)` — O(log n)\n\n**Example:**\ncountOps(\"bubbleSort\", 1000) => ~500000\ncountOps(\"mergeSort\", 1000) => ~10000\ncountOps(\"binarySearch\", 1000) => ~10\n\nReturn `{name: estimated_ops}`", "sampleInput": "n=1000 for bubbleSort, mergeSort, binarySearch", "sampleOutput": "{bubble:~500000, merge:~10000, binary:~10}"},
},

'D11-array-patterns.json': {
    1: {"description": "Find the maximum average of a subarray of length exactly k.\n\n**Example:**\nmaxAverage([1,12,-5,-6,50,3], k=4) => 12.75 (subarray [12,-5,-6,50] = 51/4)\n\n**Key insight:** Sliding window of fixed size k. Slide by subtracting outgoing + adding incoming element.", "sampleInput": "[1,12,-5,-6,50,3], k=4", "sampleOutput": "12.75"},
    2: {"description": "Find the total number of contiguous subarrays that sum to exactly k.\n\n**Example 1:**\nsubarraySum([1,1,1], k=2) => 2\nsubarraySum([1,2,3], k=3) => 2 ([3] and [1,2])\n\n**Key insight:** Prefix sum + HashMap. `prefixMap[sum]` = count of times this prefix sum appeared. If `prefix-k` exists, those subarrays sum to k.", "sampleInput": "[1,1,1], k=2", "sampleOutput": "2"},
    3: {"description": "Find two lines that together with the x-axis form a container holding the most water.\n\n**Example 1:**\nmaxWater([1,8,6,2,5,4,8,3,7]) => 49 (lines at index 1 and 8: min(8,7) * 7 = 49)\nmaxWater([1,1]) => 1\n\n**Key insight:** Two pointers from both ends. Move the shorter line inward — the taller line can only decrease width, so never helps.", "sampleInput": "[1,8,6,2,5,4,8,3,7]", "sampleOutput": "49"},
},

'D12-string-algorithms.json': {
    1: {"description": "Find the length of the longest substring without repeating characters.\n\n**Example 1:**\nlengthOfLongest(\"abcabcbb\") => 3 (\"abc\")\nlengthOfLongest(\"bbbbb\") => 1\nlengthOfLongest(\"pwwkew\") => 3 (\"wke\")\n\n**Key insight:** Sliding window + HashMap storing last index. Expand right; shrink left when duplicate found.", "sampleInput": "\"abcabcbb\"", "sampleOutput": "3"},
    2: {"description": "Check if two strings are anagrams (same characters, same frequencies).\n\n**Example 1:**\nisAnagram(\"anagram\", \"nagaram\") => true\nisAnagram(\"rat\", \"car\") => false\n\n**Key insight:** Sort both and compare, or use a frequency count array of 26 letters (increment for s, decrement for t).", "sampleInput": "\"anagram\", \"nagaram\"", "sampleOutput": "true"},
    3: {"description": "Group an array of strings by their anagram class.\n\n**Example:**\ngroupAnagrams([\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"])\n=> [[\"eat\",\"tea\",\"ate\"],[\"tan\",\"nat\"],[\"bat\"]]\n\n**Key insight:** Sorted string as HashMap key. All anagrams share the same sorted form.", "sampleInput": "[\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]", "sampleOutput": "[[\"eat\",\"tea\",\"ate\"],[\"tan\",\"nat\"],[\"bat\"]]"},
},

'D13-bit-manipulation.json': {
    1: {"description": "Count the number of '1' bits in a 32-bit unsigned integer (Hamming weight).\n\n**Example 1:**\nhammingWeight(11) => 3 (1011 has three 1s)\nhammingWeight(128) => 1 (10000000)\nhammingWeight(2147483645) => 30\n\n**Key insight:** `n & (n-1)` clears the lowest set bit. Count how many times until n=0.", "sampleInput": "11 (binary: 00001011)", "sampleOutput": "3"},
    2: {"description": "Find the single number in an array where every element appears twice except one.\n\n**Example 1:**\nsingleNumber([2,2,1]) => 1\nsingleNumber([4,1,2,1,2]) => 4\n\n**Key insight:** XOR all elements. Pairs cancel out (a^a=0). The unique number is what remains.", "sampleInput": "[4,1,2,1,2]", "sampleOutput": "4"},
    3: {"description": "Generate all subsets of [0, n-1] using bitmask enumeration.\n\n**Example:**\nsubsets(3) using bitmask:\nmask 000 => {}\nmask 001 => {0}\nmask 010 => {1}\nmask 011 => {0,1}\nmask 100 => {2}\n...\nmask 111 => {0,1,2}\n\n**Key insight:** 2^n masks from 0 to 2^n-1. For each mask, bit j set means element j is in the subset.", "sampleInput": "n=3", "sampleOutput": "8 subsets: [{},{0},{1},{0,1},{2},{0,2},{1,2},{0,1,2}]"},
},

'D14-greedy.json': {
    1: {"description": "Assign cookies to children: each child has a greed factor, each cookie a size. Assign one cookie per child, only if size >= greed. Maximize number of content children.\n\n**Example 1:**\nassignCookies([1,2,3], [1,1]) => 1\nassignCookies([1,2], [1,2,3]) => 2\n\n**Key insight:** Sort both. Use two pointers — give the smallest sufficient cookie to each child.", "sampleInput": "greed=[1,2,3], cookies=[1,1]", "sampleOutput": "1"},
    2: {"description": "Given jump lengths at each position, determine if you can reach the last index.\n\n**Example 1:**\ncanJump([2,3,1,1,4]) => true\ncanJump([3,2,1,0,4]) => false\n\n**Key insight:** Track `maxReach`. If current index > maxReach at any point, return false. Update maxReach = max(maxReach, i + nums[i]).", "sampleInput": "[3,2,1,0,4]", "sampleOutput": "false"},
    3: {"description": "Remove the minimum number of intervals so the remaining intervals are non-overlapping.\n\n**Example 1:**\neraseOverlapIntervals([[1,2],[2,3],[3,4],[1,3]]) => 1 (remove [1,3])\neraseOverlapIntervals([[1,2],[1,2],[1,2]]) => 2\n\n**Key insight:** Sort by end time. Keep intervals with earliest end. If overlap, remove the one with later end (greedy: keep earliest end = most room for future).", "sampleInput": "[[1,2],[2,3],[3,4],[1,3]]", "sampleOutput": "1"},
},

}

total_updated = 0
for filename, improvements in ALL_IMPROVEMENTS.items():
    fpath = seed_dir + filename
    if not os.path.exists(fpath):
        print(f"SKIP {filename} (not found)")
        continue
    with open(fpath, encoding='utf-8') as fh: data = json.load(fh)
    updated = 0
    for topic in data['topics']:
        for p in topic.get('problems', []):
            o = p.get('displayOrder') or p.get('order')
            if o in improvements:
                p['description'] = improvements[o]['description']
                p['sampleInput'] = improvements[o]['sampleInput']
                p['sampleOutput'] = improvements[o]['sampleOutput']
                updated += 1
    with open(fpath, 'w', encoding='utf-8') as fh: json.dump(data, fh, indent=2, ensure_ascii=False)
    print(f"{filename}: {updated} updated")
    total_updated += updated

print(f"\nTotal: {total_updated}")
