import json
f = 'C:/Dev/devlearner/devlearner/learning-system/src/main/resources/seeds/B15-encapsulation.json'
with open(f, encoding='utf-8') as fh: data = json.load(fh)

improvements = {
    1: {"description": "The following `BankAccount` exposes its balance directly — fix it:\n\n```java\nclass BankAccount { public double balance; } // broken\n```\n\nRefactor: make `balance` private, add `deposit(double)` and `withdraw(double)` with validation.\n\n**Example:**\nBankAccount a = new BankAccount(100);\na.deposit(50); a.getBalance() => 150.0\na.withdraw(200) => throws InsufficientFundsException\na.withdraw(-10) => throws IllegalArgumentException", "sampleInput": "deposit(50) then withdraw(200)", "sampleOutput": "getBalance()=150.0 then throws InsufficientFundsException"},
    2: {"description": "Identify the correct access modifier for each member:\n\n- `private`: internal implementation detail — never visible outside the class\n- `package-private` (no modifier): visible within the same package\n- `protected`: visible to subclasses and same package\n- `public`: visible everywhere\n\n**Example:**\nImplement `AccessDemo` with one field of each level and a `describeAccess()` method returning their names.\n\n**Output:** [\"private\", \"package\", \"protected\", \"public\"]", "sampleInput": "describeAccess()", "sampleOutput": "[\"private\", \"package-private\", \"protected\", \"public\"]"},
    3: {"description": "Design `Temperature(double value, String unit)` with validation: value must be above absolute zero (-273.15°C). Setters must re-validate; unit must be \"C\", \"F\", or \"K\".\n\n**Example 1:**\nnew Temperature(100, \"C\").getValue() => 100.0\nnew Temperature(100, \"C\").toFahrenheit() => 212.0\n\n**Example 2:**\nnew Temperature(-300, \"C\") => throws IllegalArgumentException(\"Below absolute zero\")\nnew Temperature(100, \"X\") => throws IllegalArgumentException(\"Invalid unit\")", "sampleInput": "new Temperature(-300, \"C\")", "sampleOutput": "throws IllegalArgumentException(\"Below absolute zero\")"},
    4: {"description": "Implement a thread-safe `Counter` using `synchronized` methods or `AtomicInteger`. Multiple threads incrementing concurrently must produce the correct total.\n\n**Example:**\nCounter c = new Counter();\n10 threads each increment 1000 times\nc.getValue() => 10000 (no lost updates)\n\n**Key insight:** Without synchronization, increments race — threads read stale values. `synchronized` or `AtomicInteger` ensures atomicity.", "sampleInput": "10 threads * 1000 increments", "sampleOutput": "10000"},
    5: {"description": "Implement an encapsulated `Stack<T>` — internal array or list is private; only `push()`, `pop()`, `peek()`, `isEmpty()`, `size()` are public.\n\n**Example:**\nStack<Integer> s = new Stack<>();\ns.push(1); s.push(2); s.push(3);\ns.peek() => 3\ns.pop() => 3\ns.size() => 2\ns.pop(); s.pop(); s.pop() => throws EmptyStackException", "sampleInput": "push(1,2,3), peek(), pop()", "sampleOutput": "peek=3, pop=3, size=2"},
    6: {"description": "Create `ProductCatalog` holding `List<Product>`. The getter must return a **defensive copy** to prevent callers from mutating the internal list.\n\n**Example:**\nList<Product> external = catalog.getProducts();\nexternal.add(new Product(\"hack\", 0));\ncatalog.getProducts().size() === original size (unchanged)\n\n**Key insight:** `return new ArrayList<>(internalList)` — callers get their own copy; modifying it doesn't affect the catalog.", "sampleInput": "getProducts() then add to returned list", "sampleOutput": "catalog.size() unchanged"},
    7: {"description": "Show that `String` is immutable — methods return new strings, they never modify the original:\n\n```java\nString s = \"hello\";\nString upper = s.toUpperCase();\nSystem.out.println(s);     // \"hello\" (unchanged)\nSystem.out.println(upper); // \"HELLO\"\n```\n\nBuild a chain: `trim().toUpperCase().replace(\"O\",\"0\")` on `\"  hello world  \"`\n=> \"HELL0 W0RLD\"", "sampleInput": "\"  hello world  \".trim().toUpperCase().replace(\"O\",\"0\")", "sampleOutput": "\"HELL0 W0RLD\""},
    8: {"description": "Create `ConfigManager` that accepts all settings in the constructor. After construction, nothing can be changed — add a `freeze()` mechanism or make all fields final.\n\n**Example:**\nConfigManager cfg = new ConfigManager(\"localhost\", 8080, \"/api\");\ncfg.getHost() => \"localhost\"\ncfg.setHost(\"other\") => throws UnsupportedOperationException(\"Config is immutable\")\n\n**Key insight:** Read-only configuration prevents accidental runtime changes — a common source of bugs in long-running services.", "sampleInput": "cfg.setHost(\"other\") after construction", "sampleOutput": "throws UnsupportedOperationException"},
    9: {"description": "Create a `PersonRecord` (Java 16+ record or POJO) with `firstName`, `lastName`, `age`. Add a custom `fullName()` accessor returning `firstName + \" \" + lastName`.\n\n**Example:**\nnew PersonRecord(\"John\", \"Doe\", 30).fullName() => \"John Doe\"\nnew PersonRecord(\"John\", \"Doe\", 30).getAge() => 30\nnew PersonRecord(\"John\", \"Doe\", -1) => throws IllegalArgumentException (age < 0)\n\n**Key insight:** Records auto-generate `equals`, `hashCode`, `toString`, and accessors — but you can still add custom methods.", "sampleInput": "new PersonRecord(\"John\", \"Doe\", 30).fullName()", "sampleOutput": "\"John Doe\""},
    10: {"description": "Implement `PriorityQueue<Task>` where tasks have priority 1-10. Internal heap is private. Public API: `enqueue(Task)`, `dequeue()` (highest priority first), `peek()`, `size()`.\n\n**Example:**\nqueue.enqueue(new Task(\"low\", 1));\nqueue.enqueue(new Task(\"high\", 10));\nqueue.enqueue(new Task(\"mid\", 5));\nqueue.dequeue().getName() => \"high\"\nqueue.dequeue().getName() => \"mid\"", "sampleInput": "enqueue low(1), high(10), mid(5), then dequeue twice", "sampleOutput": "[\"high\", \"mid\"]"},
    11: {"description": "Create `UserRegistration` with private fields `username`, `email`, `hashedPassword`. Validate all in the constructor: username 3-20 chars, email contains '@', password 8+ chars.\n\n**Example 1:**\nnew UserRegistration(\"alice\", \"alice@example.com\", \"secret99\").getUsername() => \"alice\"\n\n**Example 2:**\nnew UserRegistration(\"ab\", \"alice@example.com\", \"secret99\") => throws IllegalArgumentException(\"Username must be 3-20 chars\")", "sampleInput": "new UserRegistration(\"ab\", \"alice@example.com\", \"secret99\")", "sampleOutput": "throws IllegalArgumentException(\"Username must be 3-20 chars\")"},
    12: {"description": "Create `EventHistory` where events can only be **appended**, never removed or modified. Internal list is private; `addEvent(String)` appends; `getEvents()` returns unmodifiable view.\n\n**Example:**\nEventHistory h = new EventHistory();\nh.addEvent(\"user_login\");\nh.addEvent(\"order_placed\");\nh.getEvents() => [\"user_login\", \"order_placed\"]\nh.getEvents().add(\"hack\") => throws UnsupportedOperationException\n\n**Key insight:** `Collections.unmodifiableList()` exposes a read-only view without copying.", "sampleInput": "getEvents().add(\"hack\")", "sampleOutput": "throws UnsupportedOperationException"},
    13: {"description": "Demonstrate nested class access levels:\n- `private static class` — only accessible within the outer class\n- `static class` (package-private) — accessible within the package\n- `public static class` — accessible everywhere\n\n**Example:**\nOuter.PublicNested n = new Outer.PublicNested(); // OK\nnew Outer.PrivateNested(); // compile error from outside Outer\n\nImplement `Outer` with all three nested class levels and a factory method for each.", "sampleInput": "new Outer.PublicNested()", "sampleOutput": "OK; new Outer.PrivateNested() => compile error"},
    14: {"description": "Build a `UserBuilder` with validation groups: `BASIC` (name+email), `FULL` (adds phone+address). `build(ValidationGroup)` validates the required fields for that group.\n\n**Example:**\nnew UserBuilder().name(\"Alice\").email(\"a@b.com\").build(BASIC) => OK\nnew UserBuilder().name(\"Alice\").email(\"a@b.com\").build(FULL) => throws ValidationException(\"Phone required for FULL\")\nnew UserBuilder().name(\"\").build(BASIC) => throws ValidationException(\"Name required\")", "sampleInput": ".name(\"Alice\").email(\"a@b.com\").build(FULL)", "sampleOutput": "throws ValidationException(\"Phone required for FULL\")"},
    15: {"description": "Create a `BankAccount` domain model with rich encapsulation: private balance, transaction history (append-only), and business rules enforced inside the class.\n\n**Example:**\nBankAccount a = new BankAccount(\"Alice\", 1000);\na.deposit(500);\na.withdraw(200);\na.getBalance() => 1300.0\na.getTransactionCount() => 2\na.withdraw(2000) => throws InsufficientFundsException\na.getBalance() => 1300.0 (unchanged after failed withdraw)", "sampleInput": "deposit(500), withdraw(200), withdraw(2000)", "sampleOutput": "balance=1300.0 after 2 ok; throws on 3rd"},
    16: {"description": "Demonstrate that Java reflection can bypass encapsulation, and explain why this is a security concern:\n\n```java\nclass Secret { private String password = \"abc123\"; }\nField f = Secret.class.getDeclaredField(\"password\");\nf.setAccessible(true);\nf.get(new Secret()) // => \"abc123\"\n```\n\nImplement `reflectiveRead(Object obj, String fieldName)` and explain how `SecurityManager` (legacy) or module system (Java 9+) can restrict it.", "sampleInput": "reflectiveRead(new Secret(), \"password\")", "sampleOutput": "\"abc123\" (encapsulation bypassed)"},
    17: {"description": "Implement thread-safe Singleton with **double-checked locking**:\n\n```java\nclass Config {\n    private static volatile Config instance;\n    static Config getInstance() {\n        if (instance == null) {\n            synchronized(Config.class) {\n                if (instance == null) instance = new Config();\n            }\n        }\n        return instance;\n    }\n}\n```\n\n**Example:**\nConfig.getInstance() == Config.getInstance() => true (same reference)\n\n**Key insight:** `volatile` prevents instruction reordering; double-check avoids locking overhead after initialization.", "sampleInput": "Config.getInstance() called from 2 threads", "sampleOutput": "same instance (== true)"},
    18: {"description": "Implement `Graph` where edges are encapsulated — only valid edges (no self-loops, no duplicate edges) can be added via `addEdge(int from, int to)`.\n\n**Example:**\nGraph g = new Graph(4);\ng.addEdge(0, 1); g.addEdge(1, 2);\ng.addEdge(0, 0) => throws IllegalArgumentException(\"Self-loops not allowed\")\ng.addEdge(0, 1) => throws IllegalArgumentException(\"Duplicate edge\")\ng.edgeCount() => 2", "sampleInput": "addEdge(0,0)", "sampleOutput": "throws IllegalArgumentException(\"Self-loops not allowed\")"},
    19: {"description": "Create a multi-step `OrderBuilder` with staged validation:\n1. `addItem()` — validates price > 0 and qty > 0\n2. `setShipping()` — validates address non-blank\n3. `build()` — validates at least one item exists\n\n**Example 1:**\nnew OrderBuilder().addItem(\"book\",10,1).setShipping(\"123 Main\").build() => Order{items=1}\n\n**Example 2:**\nnew OrderBuilder().setShipping(\"123 Main\").build() => throws IllegalStateException(\"No items\")", "sampleInput": "new OrderBuilder().setShipping(\"123 Main\").build()", "sampleOutput": "throws IllegalStateException(\"No items\")"},
    20: {"description": "Implement `EncapsulationAudit` that inspects a class at runtime (via reflection) and reports all fields that are not `private` — a simple encapsulation checker.\n\n**Example:**\nclass Broken { public int x; protected String y; private double z; }\nEncapsulationAudit.check(Broken.class)\n=> [\"x (public)\", \"y (protected)\"] // only non-private fields\n\n**Key insight:** Use `getDeclaredFields()` and check `Modifier.isPrivate(field.getModifiers())`.", "sampleInput": "EncapsulationAudit.check(Broken.class)", "sampleOutput": "[\"x (public)\", \"y (protected)\"]"},
}

updated = 0
for topic in data['topics']:
    for p in topic.get('problems', []):
        o = p['displayOrder']
        if o in improvements:
            p['description'] = improvements[o]['description']
            p['sampleInput'] = improvements[o]['sampleInput']
            p['sampleOutput'] = improvements[o]['sampleOutput']
            updated += 1
with open(f, 'w', encoding='utf-8') as fh: json.dump(data, fh, indent=2, ensure_ascii=False)
print(f"B15 updated: {updated} problems")
