import json
f = 'C:/Dev/devlearner/devlearner/learning-system/src/main/resources/seeds/B13-polymorphism.json'
with open(f, encoding='utf-8') as fh: data = json.load(fh)

improvements = {
    1: {"description": "Create `Shape` with abstract `area()`. Implement `Circle(double r)` and `Rectangle(double w, double h)`. Store both in a `List<Shape>` and print each area.\n\n**Example:**\nList<Shape> shapes = List.of(new Circle(5), new Rectangle(3,4));\nshapes.forEach(s -> System.out.println(s.area()));\n=> 78.54\n=> 12.0\n\n**Key insight:** The list holds `Shape` references; JVM dispatches `area()` to the correct subtype at runtime.", "sampleInput": "List<Shape>{Circle(5), Rectangle(3,4)}", "sampleOutput": "[78.54, 12.0]"},
    2: {"description": "Predict which overloaded method is called — overloading is resolved at **compile time** based on declared type:\n\n```java\nvoid print(Object o)  { System.out.println(\"Object\"); }\nvoid print(String s)  { System.out.println(\"String\"); }\nObject o = \"hello\";\nprint(o);       // => Object (declared type is Object)\nprint(\"hello\"); // => String\n```", "sampleInput": "Object o = \"hello\"; print(o);", "sampleOutput": "\"Object\""},
    3: {"description": "Create a `SoundSystem` that accepts any `AudioDevice` (interface). `Speaker` and `Headphones` implement `AudioDevice`. `SoundSystem.play()` calls `device.output()`.\n\n**Example:**\nnew SoundSystem(new Speaker()).play() => \"Playing through speaker\"\nnew SoundSystem(new Headphones()).play() => \"Playing through headphones\"\n\n**Key insight:** `SoundSystem` depends on the interface, not the concrete class — you can swap implementations without changing `SoundSystem`.", "sampleInput": "new SoundSystem(new Speaker()).play()", "sampleOutput": "\"Playing through speaker\""},
    4: {"description": "Create a `Calculator` with overloaded `add()` methods: `add(int,int)`, `add(double,double)`, `add(int,int,int)`.\n\n**Example 1:**\nadd(2, 3) => 5\nadd(2.5, 3.5) => 6.0\nadd(1, 2, 3) => 6\n\n**Key insight:** Overloading = same name, different parameter types/counts. Resolved at compile time. Overriding = same signature in subclass, resolved at runtime.", "sampleInput": "add(2.5, 3.5)", "sampleOutput": "6.0"},
    5: {"description": "Create a `List<Object>` containing a `String`, `Integer`, `Double`, and a custom `Person`. Print each using `toString()` — every object has it via `Object`.\n\n**Example:**\nList.of(\"hello\", 42, 3.14, new Person(\"Alice\"))\n.forEach(System.out::println)\n=> hello\n=> 42\n=> 3.14\n=> Person{name='Alice'}\n\n**Key insight:** `Object.toString()` is inherited by all classes — polymorphism works even through the root `Object` type.", "sampleInput": "List.of(\"hello\", 42, 3.14, new Person(\"Alice\"))", "sampleOutput": "hello / 42 / 3.14 / Person{name='Alice'}"},
    6: {"description": "Implement the **Strategy pattern**: `Sorter` accepts a `SortStrategy`. Swap between `BubbleSort`, `QuickSort`, and `MergeSort` at runtime.\n\n**Example:**\nSorter s = new Sorter(new QuickSort());\ns.sort(new int[]{5,2,8,1}) => [1,2,5,8]\ns.setStrategy(new BubbleSort());\ns.sort(new int[]{3,1,2}) => [1,2,3]\n\n**Key insight:** Strategy encapsulates algorithms behind a common interface — clients switch behaviour without `if/else` chains.", "sampleInput": "new Sorter(new QuickSort()).sort([5,2,8,1])", "sampleOutput": "[1,2,5,8]"},
    7: {"description": "Predict which `sum()` overload is called with varargs:\n\n```java\nvoid sum(int... nums)       { print(\"varargs int\"); }\nvoid sum(int a, int b)      { print(\"two ints\"); }\nsum(1, 2);    // => two ints (exact match wins)\nsum(1, 2, 3); // => varargs int\nsum();        // => varargs int\n```\n\n**Key insight:** Exact-match overloads take priority over varargs.", "sampleInput": "sum(1, 2)", "sampleOutput": "\"two ints\""},
    8: {"description": "Implement a **polymorphic factory method**: `ShapeFactory.create(String type)` returns a `Shape` without the caller knowing the concrete class.\n\n**Example:**\nShapeFactory.create(\"circle\") instanceof Circle => true\nShapeFactory.create(\"rect\") instanceof Rectangle => true\nShapeFactory.create(\"unknown\") => throws IllegalArgumentException\n\n**Key insight:** Factory method hides the `new` keyword — callers depend only on the `Shape` interface.", "sampleInput": "ShapeFactory.create(\"circle\")", "sampleOutput": "instanceof Circle => true"},
    9: {"description": "Predict the output — overloading is compile-time, overriding is runtime:\n\n```java\nclass A { void test(Object o) { print(\"A-Object\"); } }\nclass B extends A { void test(Object o) { print(\"B-Object\"); } // overrides\n                    void test(String s) { print(\"B-String\"); } // overloads }\nA obj = new B();\nobj.test(\"hi\");      // => B-Object (override wins; declared type A has only test(Object))\nB b = new B();\nb.test(\"hi\");        // => B-String (overload matches String)\n```", "sampleInput": "A obj = new B(); obj.test(\"hi\");", "sampleOutput": "\"B-Object\""},
    10: {"description": "Demonstrate covariant return in a polymorphic chain:\n\n```java\nclass Builder { Builder set(String k, String v) { ...; return this; } }\nclass AdvancedBuilder extends Builder {\n    AdvancedBuilder set(String k, String v) { ...; return this; } // covariant\n    AdvancedBuilder setFlag(boolean b) { ...; return this; }\n}\nnew AdvancedBuilder().set(\"k\",\"v\").setFlag(true).build(); // no cast needed\n```\n\n**Key insight:** Covariant return lets fluent APIs stay typed through inheritance — no `(AdvancedBuilder)` cast needed.", "sampleInput": "new AdvancedBuilder().set(\"k\",\"v\").setFlag(true)", "sampleOutput": "AdvancedBuilder (no cast needed)"},
    11: {"description": "Implement the **Observer pattern**: `EventBus` holds a list of `EventListener` implementations. `publish(Event)` notifies all listeners polymorphically.\n\n**Example:**\nEventBus bus = new EventBus();\nbus.subscribe(new EmailListener());\nbus.subscribe(new LogListener());\nbus.publish(new UserCreatedEvent(\"Alice\"));\n=> \"Email sent: Alice created\"\n=> \"LOG: Alice created\"", "sampleInput": "bus.publish(new UserCreatedEvent(\"Alice\"))", "sampleOutput": "\"Email sent: Alice created\" / \"LOG: Alice created\""},
    12: {"description": "Create a `CommandQueue` holding `Command` objects (interface with `execute()`). Enqueue `PrintCommand`, `SaveCommand`, `DeleteCommand` and run all.\n\n**Example:**\nqueue.enqueue(new PrintCommand(\"hello\"));\nqueue.enqueue(new SaveCommand(\"file.txt\"));\nqueue.runAll();\n=> \"Printing: hello\"\n=> \"Saving: file.txt\"\n\n**Key insight:** The queue operates on the `Command` interface — any command can be added without changing queue logic.", "sampleInput": "queue with Print+Save commands", "sampleOutput": "\"Printing: hello\" / \"Saving: file.txt\""},
    13: {"description": "Implement a `PolymorphicSorter` that accepts a `Comparator<Person>` at runtime. Sort the same list three ways: by name, by age, by name-then-age.\n\n**Example:**\nList<Person> people = List.of(new Person(\"Bob\",30), new Person(\"Alice\",25));\nsort(people, Comparator.comparing(Person::getName));\n=> [Alice(25), Bob(30)]\nsort(people, Comparator.comparingInt(Person::getAge));\n=> [Alice(25), Bob(30)]", "sampleInput": "sort by name: [Bob(30), Alice(25)]", "sampleOutput": "[Alice(25), Bob(30)]"},
    14: {"description": "Implement `equals()` using **double dispatch** to avoid cross-type equality bugs:\n\n```java\nclass A { boolean equals(Object o) {\n    if (!(o instanceof A)) return false;\n    return ((A)o).equalsA(this);\n} boolean equalsA(A other) { return true; } }\n```\nThis ensures `a.equals(b)` and `b.equals(a)` are always symmetric.\n\n**Example:**\nnew A().equals(new B()) and new B().equals(new A()) => both false (if B doesn't override equalsA)", "sampleInput": "new A().equals(new B())", "sampleOutput": "false (symmetric)"},
    15: {"description": "Implement the **Decorator pattern**: `TextFormatter` interface with `format(String)`. `UpperCaseDecorator`, `TrimDecorator`, and `BracketDecorator` wrap each other.\n\n**Example:**\nTextFormatter f = new BracketDecorator(new UpperCaseDecorator(new TrimDecorator(s -> s)));\nf.format(\"  hello  \") => \"[HELLO]\"\n\n**Key insight:** Each decorator wraps another `TextFormatter` and calls `inner.format()` — behaviour stacks without subclassing.", "sampleInput": "BracketDecorator(UpperCaseDecorator(TrimDecorator)).format(\"  hello  \")", "sampleOutput": "\"[HELLO]\""},
    16: {"description": "Implement `getTypeName(Object o)` that returns the type name **without using `instanceof`**, using `getClass().getSimpleName()` or a visitor.\n\n**Example:**\ngetTypeName(new Circle()) => \"Circle\"\ngetTypeName(new Rectangle()) => \"Rectangle\"\ngetTypeName(\"text\") => \"String\"\n\n**Key insight:** `o.getClass().getSimpleName()` works polymorphically for any object. Visitor gives more control for domain types.", "sampleInput": "getTypeName(new Circle())", "sampleOutput": "\"Circle\""},
    17: {"description": "Create a `Pipeline<T>` with chainable `pipe(Function<T,T>)` steps. Each step transforms the value; `execute(T input)` runs them all.\n\n**Example:**\nnew Pipeline<String>()\n    .pipe(String::trim)\n    .pipe(String::toUpperCase)\n    .pipe(s -> s + \"!\")\n    .execute(\"  hello  \")\n=> \"HELLO!\"\n\n**Key insight:** Each stage is a polymorphic `Function<T,T>` — the pipeline doesn't know or care what each step does.", "sampleInput": "trim -> toUpperCase -> append(!) on \"  hello  \"", "sampleOutput": "\"HELLO!\""},
    18: {"description": "Calling an overloaded method with `null` is ambiguous when multiple signatures match:\n\n```java\nvoid handle(String s) { print(\"String\"); }\nvoid handle(Integer i) { print(\"Integer\"); }\nhandle(null); // => compile error: ambiguous\n```\n\nFix: cast the null — `handle((String) null)` resolves to `String` overload.\n\n**Example:**\nhandle((String) null) => \"String\"\nhandle((Integer) null) => \"Integer\"", "sampleInput": "handle((String) null)", "sampleOutput": "\"String\""},
    19: {"description": "Demonstrate the **Open/Closed Principle** via polymorphism: a `ReportGenerator` generates reports for any `ReportFormatter` without modification when new formats are added.\n\n**Example:**\nnew ReportGenerator(new PdfFormatter()).generate(data) => \"PDF report: ...\"\nnew ReportGenerator(new CsvFormatter()).generate(data) => \"CSV report: ...\"\nAdding `ExcelFormatter` requires NO changes to `ReportGenerator`.\n\n**Key insight:** Depend on abstractions — the class is closed for modification but open for extension via new implementations.", "sampleInput": "new ReportGenerator(new CsvFormatter()).generate(data)", "sampleOutput": "\"CSV report: ...\""},
    20: {"description": "Implement a recursive tree printer using polymorphism. `TreeNode` can be a `LeafNode(String value)` or `BranchNode(List<TreeNode> children)`. `print(int indent)` renders the tree with indentation.\n\n**Example:**\nBranchNode root = new BranchNode(List.of(\n    new LeafNode(\"A\"),\n    new BranchNode(List.of(new LeafNode(\"B\"), new LeafNode(\"C\")))));\nroot.print(0);\n=> \"Branch\"\n=> \"  A\"\n=> \"  Branch\"\n=> \"    B\"\n=> \"    C\"", "sampleInput": "BranchNode with LeafNode(A) and BranchNode(B,C)", "sampleOutput": "Branch / A / Branch / B / C (indented)"},
}

updated = 0
for topic in data['topics']:
    for p in topic.get('problems', []):
        o = p['displayOrder']
        if o in improvements:
            p['description'] = improvements[o]['description']
            p['sampleInput'] = improvements[o]['sampleInput']
            p['sampleOutput'] = improvements[o]['sampleOutput']
            updated += 1
with open(f, 'w', encoding='utf-8') as fh: json.dump(data, fh, indent=2, ensure_ascii=False)
print(f"B13 updated: {updated} problems")
