import json
f = 'C:/Dev/devlearner/devlearner/learning-system/src/main/resources/seeds/B01-jvm-architecture.json'
with open(f, encoding='utf-8') as fh: data = json.load(fh)

improvements = {
    1: {"description": "Predict which variables live on the stack vs heap, then verify with a short program:\n\n```java\nvoid demo() {\n    int x = 5;                  // stack primitive\n    String s = \"hello\";         // stack ref; string in heap (pool)\n    int[] arr = new int[3];     // stack ref; array in heap\n    Object o = new Object();    // stack ref; object in heap\n}\n```\n\nImplement `classifyMemory()` returning a `Map<String, String>` mapping variable name to \"stack\" or \"heap\".", "sampleInput": "classifyMemory()", "sampleOutput": "{x:stack, s:heap, arr:heap, o:heap}"},
    2: {"description": "Traverse the ClassLoader delegation chain for a given class: App ClassLoader -> Platform ClassLoader -> Bootstrap ClassLoader.\n\n**Example:**\nString.class.getClassLoader() => null (Bootstrap — native, not a Java object)\nArrayList.class.getClassLoader() => PlatformClassLoader\nMyApp.class.getClassLoader() => AppClassLoader\n\nImplement `printClassLoaderChain(Class<?> cls)` that prints each loader in the chain.", "sampleInput": "printClassLoaderChain(String.class)", "sampleOutput": "null (Bootstrap ClassLoader)"},
    3: {"description": "Count how many objects become GC-eligible after each statement:\n\n```java\nString a = new String(\"x\"); // 1 object\na = new String(\"y\");        // 1 now GC-eligible (\"x\" object)\na = null;                   // 1 now GC-eligible (\"y\" object)\n```\n\nImplement `countGcEligible(String[] steps)` returning the count after each step.", "sampleInput": "steps: create, reassign, null", "sampleOutput": "[0, 1, 2]"},
    4: {"description": "Detect the current JVM version and print major features available.\n\n**Example:**\nSystem.getProperty(\"java.version\") => \"21.0.1\"\nSystem.getProperty(\"java.vm.name\") => \"Java HotSpot(TM) 64-Bit Server VM\"\nRuntime.version().feature() => 21\n\nImplement `getJvmInfo()` returning Map with: version, vmName, vendor, maxHeapMB.", "sampleInput": "getJvmInfo()", "sampleOutput": "{version:\"21.0.1\", vmName:\"...\", maxHeapMB:256}"},
    5: {"description": "Demonstrate `==` (reference equality) vs `.equals()` (value equality) for objects:\n\n**Example:**\nString a = new String(\"hello\");\nString b = new String(\"hello\");\na == b => false (different objects)\na.equals(b) => true (same content)\n\nString c = \"hello\"; String d = \"hello\";\nc == d => true (same interned constant)\n\nImplement `compareStrings()` showing all four cases.", "sampleInput": "new String(\"hello\") == new String(\"hello\")", "sampleOutput": "false"},
    6: {"description": "Demonstrate `StackOverflowError` by finding the max safe recursion depth:\n\n```java\nstatic int depth = 0;\nstatic void recurse() { depth++; recurse(); }\ntry { recurse(); } catch (StackOverflowError e) { /* depth is max */ }\n```\n\nImplement `findStackLimit()` returning the approximate max depth.\n\n**Key insight:** Each frame takes ~100-200 bytes. Default stack is 512KB-1MB. Typical limit: 5000-20000 frames.", "sampleInput": "findStackLimit()", "sampleOutput": "~8000 (JVM-dependent)"},
    7: {"description": "Demonstrate the order of static initializers when classes are loaded:\n\n```java\nclass A { static { System.out.println(\"A loaded\"); } }\nclass B extends A { static { System.out.println(\"B loaded\"); } }\nnew B();\n```\nOutput: \"A loaded\" then \"B loaded\"\n\nImplement `demonstrateClassInit()` returning `String[]` of the initialization order.", "sampleInput": "new B() where B extends A", "sampleOutput": "[\"A loaded\", \"B loaded\"]"},
    8: {"description": "Demonstrate that `WeakReference` objects are collected by GC while `StrongReference` objects are not:\n\n**Example:**\nObject strong = new Object();\nWeakReference<Object> weak = new WeakReference<>(new Object());\nSystem.gc();\nweak.get() => null (collected)\nstrong != null => true (not collected)\n\nImplement `demonstrateWeakRef()` returning whether the weak ref was collected.", "sampleInput": "WeakReference after System.gc()", "sampleOutput": "weak.get() = null"},
    9: {"description": "Measure heap usage before and after allocating a large array using `Runtime.getRuntime()`:\n\n```java\nlong before = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();\nbyte[] arr = new byte[1024 * 1024 * 10]; // 10MB\nlong after = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();\nSystem.out.println(\"Delta: \" + (after - before) / 1024 / 1024 + \"MB\");\n```\n\nImplement `measureHeapDelta(int sizeMB)` returning the actual heap delta in bytes.", "sampleInput": "measureHeapDelta(10)", "sampleOutput": "~10MB delta"},
    10: {"description": "Implement a custom `ClassLoader` that loads a class from a `byte[]` instead of the filesystem:\n\n**Example:**\nbyte[] classBytes = compileClass(\"Hello\");\nCustomClassLoader loader = new CustomClassLoader();\nClass<?> cls = loader.defineClassFromBytes(\"Hello\", classBytes);\ncls.getDeclaredMethod(\"greet\").invoke(cls.newInstance()) => \"Hello from custom loader!\"", "sampleInput": "defineClassFromBytes(\"Hello\", bytes)", "sampleOutput": "\"Hello from custom loader!\""},
    11: {"description": "Simulate Metaspace exhaustion by generating thousands of dynamic classes with `ByteBuddy` or `javax.tools`:\n\n**Example:**\nfor (int i = 0; i < 100000; i++) generateClass(\"Dyn\" + i);\n=> eventually: java.lang.OutOfMemoryError: Metaspace\n\nImplement `simulateMetaspaceOOM(int classCount)` that catches OOM and reports how many classes were loaded.\n\n**Key insight:** Each class definition consumes Metaspace. `-XX:MaxMetaspaceSize=64m` to reproduce faster.", "sampleInput": "generateClass x 100000", "sampleOutput": "OOM after ~N classes (Metaspace full)"},
    12: {"description": "Demonstrate `ThreadLocal<T>` where each thread gets its own copy of a value:\n\n**Example:**\nThreadLocal<String> local = new ThreadLocal<>();\nThread1: local.set(\"T1-data\"); local.get() => \"T1-data\"\nThread2: local.set(\"T2-data\"); local.get() => \"T2-data\"\n// T1 still sees \"T1-data\" — no interference\n\nImplement `threadLocalDemo()` showing isolation between 3 threads.", "sampleInput": "3 threads each set their own ThreadLocal value", "sampleOutput": "each thread reads its own value"},
    13: {"description": "Register a JVM shutdown hook that runs cleanup code when the JVM exits:\n\n**Example:**\nRuntime.getRuntime().addShutdownHook(new Thread(() -> {\n    System.out.println(\"Shutdown: closing resources\");\n    closeConnections();\n}));\nSystem.exit(0);\n=> \"Shutdown: closing resources\" (printed before JVM exits)\n\nImplement `registerShutdownHook(Runnable cleanup)` and verify it runs on exit.", "sampleInput": "registerShutdownHook(() -> print(\"bye\")) then System.exit(0)", "sampleOutput": "\"bye\" printed before exit"},
    14: {"description": "Parse JVM flags from the command line arguments into a `Map<String, String>`:\n\n**Example:**\nInput: \"-Xmx512m -Xms256m -XX:+UseG1GC -Dapp.env=prod\"\nOutput: {Xmx:\"512m\", Xms:\"256m\", \"XX:+UseG1GC\":\"true\", \"app.env\":\"prod\"}\n\nImplement `parseJvmFlags(String[] args)` returning the map.", "sampleInput": "[\"-Xmx512m\", \"-Xms256m\", \"-XX:+UseG1GC\", \"-Dapp.env=prod\"]", "sampleOutput": "{Xmx:512m, Xms:256m, UseG1GC:true, app.env:prod}"},
    15: {"description": "Demonstrate class initialization deadlock: two classes with static initializers that reference each other can cause a deadlock during loading.\n\n```java\nclass A { static B b = new B(); }\nclass B { static A a = new A(); }\n```\n\nExplain why this deadlocks and how to fix it (lazy initialization pattern).\n\nImplement `detectCircularInit()` that identifies classes with mutual static dependencies.", "sampleInput": "class A -> B, class B -> A in static init", "sampleOutput": "deadlock detected (circular dependency)"},
    16: {"description": "Implement a GC-safe Singleton using `WeakReference` so it can be garbage collected when not in use, then recreated on next access:\n\n**Example:**\nWeakSingleton s1 = WeakSingleton.getInstance(); // creates\nSystem.gc();\nWeakSingleton s2 = WeakSingleton.getInstance(); // may recreate\ns1 == s2 => false if GC collected s1\n\n**Key insight:** Contrast with regular Singleton — here memory is released when no strong references exist.", "sampleInput": "getInstance() -> gc() -> getInstance()", "sampleOutput": "may return different instance after GC"},
    17: {"description": "Simulate a memory leak via a static collection that grows without bound. Then fix it.\n\n**Leak:**\n```java\nstatic Map<String, byte[]> cache = new HashMap<>();\nvoid handle(String id) { cache.put(id, new byte[1024*1024]); } // never removed\n```\n\n**Fix:** Use `WeakHashMap`, `SoftReference`, or explicit `cache.remove(id)`.\n\nImplement both versions and measure heap growth over 100 calls.", "sampleInput": "100 calls to handle() with HashMap", "sampleOutput": "heap grows 100MB; WeakHashMap: GC reclaims"},
    18: {"description": "Simulate JVM heap dump analysis: record all live objects by type and size, then report the top 5 largest types.\n\n**Example:**\nHeapDump dump = HeapDump.take();\ndump.getTopByMemory(5)\n=> [(byte[], 50MB), (char[], 20MB), (String, 15MB), ...]\n\nImplement using reflection and `Runtime.totalMemory() - freeMemory()` to estimate per-type usage.", "sampleInput": "HeapDump.take().getTopByMemory(5)", "sampleOutput": "[(byte[],50MB),(String,15MB),(int[],10MB),...]"},
    19: {"description": "Benchmark JVM tiered compilation: run the same method 10,000 times and measure throughput improvement as JIT kicks in.\n\n**Example:**\nRun computePrime(10000) in a loop:\n- Iterations 1-100: ~5ms each (interpreted)\n- Iterations 1000-2000: ~0.5ms (C1 JIT)\n- Iterations 5000+: ~0.05ms (C2 optimized)\n\nImplement `tieredBenchmark(Runnable task, int warmup, int measure)` returning ops/sec.", "sampleInput": "tieredBenchmark(prime check, warmup=5000, measure=1000)", "sampleOutput": "throughput increases 10-100x after warmup"},
    20: {"description": "Build a minimal JVM emulator that executes simple bytecode instructions: `ICONST`, `ILOAD`, `ISTORE`, `IADD`, `ISUB`, `IMUL`, `IRETURN`.\n\n**Example:**\n// Bytecode for: int x=2; int y=3; return x+y;\nbytecode = [ICONST_2, ISTORE_0, ICONST_3, ISTORE_1, ILOAD_0, ILOAD_1, IADD, IRETURN]\nnew MiniJVM().execute(bytecode) => 5\n\n**Key insight:** JVM is a stack machine — ILOAD pushes to operand stack; IADD pops two, pushes result.", "sampleInput": "[ICONST_2, ISTORE_0, ICONST_3, ISTORE_1, ILOAD_0, ILOAD_1, IADD, IRETURN]", "sampleOutput": "5"},
}

updated = 0
for topic in data['topics']:
    for p in topic.get('problems', []):
        o = p['displayOrder']
        if o in improvements:
            p['description'] = improvements[o]['description']
            p['sampleInput'] = improvements[o]['sampleInput']
            p['sampleOutput'] = improvements[o]['sampleOutput']
            updated += 1
with open(f, 'w', encoding='utf-8') as fh: json.dump(data, fh, indent=2, ensure_ascii=False)
print(f"B01 updated: {updated} problems")
