import json
f = 'C:/Dev/devlearner/devlearner/learning-system/src/main/resources/seeds/B17-collections.json'
with open(f, encoding='utf-8') as fh: data = json.load(fh)

improvements = {
    1: {"description": "Given an array of strings, return a `Map<String,Long>` of each string's frequency.\n\n**Example:**\nfrequencyMap([\"apple\",\"banana\",\"apple\",\"cherry\",\"banana\",\"apple\"])\n=> {apple=3, banana=2, cherry=1}\n\n**Key insight:** `map.merge(word, 1L, Long::sum)` or `getOrDefault` pattern. Use `LinkedHashMap` to preserve insertion order.", "sampleInput": "[\"apple\",\"banana\",\"apple\",\"cherry\",\"banana\",\"apple\"]", "sampleOutput": "{apple=3, banana=2, cherry=1}"},
    2: {"description": "Remove duplicates from a list while preserving the original insertion order.\n\n**Example 1:**\nremoveDuplicates([3,1,4,1,5,9,2,6,5]) => [3,1,4,5,9,2,6]\n\n**Example 2:**\nremoveDuplicates([\"a\",\"b\",\"a\",\"c\",\"b\"]) => [\"a\",\"b\",\"c\"]\n\n**Key insight:** Use `LinkedHashSet` — preserves insertion order while eliminating duplicates. Then convert back to list.", "sampleInput": "[3,1,4,1,5,9,2,6,5]", "sampleOutput": "[3,1,4,5,9,2,6]"},
    3: {"description": "Group an array of strings into anagram groups using `HashMap<String, List<String>>`.\n\n**Example:**\ngroupAnagrams([\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"])\n=> [[\"bat\"],[\"nat\",\"tan\"],[\"ate\",\"eat\",\"tea\"]]\n\n**Key insight:** Sort each string to get its canonical form as the map key — all anagrams share the same sorted key.", "sampleInput": "[\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]", "sampleOutput": "[[\"bat\"],[\"nat\",\"tan\"],[\"ate\",\"eat\",\"tea\"]]"},
    4: {"description": "Find all numbers that appear **more than once** in the array.\n\n**Example 1:**\nfindDuplicates([4,3,2,7,8,2,3,1]) => [2,3]\n\n**Example 2:**\nfindDuplicates([1,1,2]) => [1]\n\n**Key insight:** Two passes — first build frequency map, then collect keys with count > 1. Or use a `Set` to detect second occurrence.", "sampleInput": "[4,3,2,7,8,2,3,1]", "sampleOutput": "[2,3]"},
    5: {"description": "Implement a `PriorityQueue`-backed task scheduler. Tasks have name and priority (1=highest). `addTask(name, priority)` enqueues; `runNext()` dequeues and returns the highest-priority task.\n\n**Example:**\nscheduler.addTask(\"low\", 5);\nscheduler.addTask(\"high\", 1);\nscheduler.addTask(\"mid\", 3);\nscheduler.runNext() => \"high\"\nscheduler.runNext() => \"mid\"", "sampleInput": "add low(5),high(1),mid(3) then runNext twice", "sampleOutput": "[\"high\", \"mid\"]"},
    6: {"description": "Given an array and a target, return the indices of the two numbers that sum to target using a `HashMap`.\n\n**Example 1:**\ntwoSum([2,7,11,15], 9) => [0,1]\ntwoSum([3,2,4], 6) => [1,2]\ntwoSum([3,3], 6) => [0,1]\n\n**Key insight:** Store `{value -> index}` while scanning. For each element check if `target - element` exists in the map — O(n) time.", "sampleInput": "twoSum([2,7,11,15], 9)", "sampleOutput": "[0,1]"},
    7: {"description": "Return the `k` most frequent elements in an array.\n\n**Example 1:**\ntopKFrequent([1,1,1,2,2,3], k=2) => [1,2]\n\n**Example 2:**\ntopKFrequent([1], k=1) => [1]\n\n**Key insight:** Build frequency map, then use a min-heap of size k — O(n log k). Or bucket sort for O(n).", "sampleInput": "topKFrequent([1,1,1,2,2,3], k=2)", "sampleOutput": "[1,2]"},
    8: {"description": "Return the **maximum** in every sliding window of size `k` using a `Deque<Integer>` (monotonic decreasing queue).\n\n**Example:**\nslidingWindowMax([1,3,-1,-3,5,3,6,7], k=3)\n=> [3,3,5,5,6,7]\n\n**Key insight:** Deque stores indices; front always holds the max index. Remove from front if out of window; remove from back while smaller than current element.", "sampleInput": "[1,3,-1,-3,5,3,6,7], k=3", "sampleOutput": "[3,3,5,5,6,7]"},
    9: {"description": "Count word frequencies and return them in **alphabetical order** using a `TreeMap`.\n\n**Example:**\nwordFrequency(\"the cat sat on the mat the cat\")\n=> {cat=2, mat=1, on=1, sat=1, the=3}\n\n**Key insight:** `TreeMap` keeps keys sorted by natural order automatically — no explicit sorting step needed.", "sampleInput": "\"the cat sat on the mat the cat\"", "sampleOutput": "{cat=2, mat=1, on=1, sat=1, the=3}"},
    10: {"description": "Implement BFS using a `Queue<Integer>`. Return nodes in BFS order.\n\n**Example:**\nGraph: {0:[1,2], 1:[3,4], 2:[5]}\nbfs(0) => [0,1,2,3,4,5]\n\n**Key insight:** `LinkedList` as `Queue` — offer to back, poll from front. Mark visited before enqueuing to avoid cycles.", "sampleInput": "bfs(0) on {0:[1,2],1:[3,4],2:[5]}", "sampleOutput": "[0,1,2,3,4,5]"},
    11: {"description": "Group employees by department using `Map<String, List<Employee>>`.\n\n**Example:**\nList<Employee> employees = [\n  Employee(\"Alice\", \"Engineering\"),\n  Employee(\"Bob\", \"Marketing\"),\n  Employee(\"Charlie\", \"Engineering\")\n]\ngroupByDept(employees)\n=> {Engineering=[Alice,Charlie], Marketing=[Bob]}\n\n**Key insight:** `map.computeIfAbsent(dept, k -> new ArrayList<>()).add(emp)` is cleaner than getOrDefault.", "sampleInput": "group Alice(Eng), Bob(Mkt), Charlie(Eng)", "sampleOutput": "{Engineering=[Alice,Charlie], Marketing=[Bob]}"},
    12: {"description": "Merge overlapping intervals using a `TreeMap` keyed by start time.\n\n**Example:**\nmergeIntervals([[1,3],[2,6],[8,10],[15,18]])\n=> [[1,6],[8,10],[15,18]]\n\nmergeIntervals([[1,4],[4,5]])\n=> [[1,5]]\n\n**Key insight:** Sort by start (TreeMap does this), then merge: if current start <= last end, extend the last interval's end.", "sampleInput": "[[1,3],[2,6],[8,10],[15,18]]", "sampleOutput": "[[1,6],[8,10],[15,18]]"},
    13: {"description": "Implement `LRUCache(int capacity)` with `get(int key)` and `put(int key, int value)`. When full, evict the least recently used.\n\n**Example:**\ncache = LRUCache(2)\ncache.put(1,1); cache.put(2,2);\ncache.get(1) => 1\ncache.put(3,3); // evicts key 2\ncache.get(2) => -1\ncache.get(3) => 3\n\n**Key insight:** `LinkedHashMap(capacity, 0.75f, true)` with `removeEldestEntry` override — O(1) for both get and put.", "sampleInput": "capacity=2, put(1,1),put(2,2),get(1),put(3,3),get(2)", "sampleOutput": "-1"},
    14: {"description": "Implement a consistent hashing ring using `TreeMap<Integer, String>`. Nodes are placed at hashed positions; a key maps to the first node clockwise.\n\n**Example:**\nring.addNode(\"ServerA\");\nring.addNode(\"ServerB\");\nring.addNode(\"ServerC\");\nring.getNode(\"user_123\") => \"ServerB\" (closest clockwise node)\n\n**Key insight:** `treeMap.ceilingKey(hash)` finds the next clockwise node; wrap around with `firstKey()` if none.", "sampleInput": "getNode(\"user_123\") on 3-node ring", "sampleOutput": "\"ServerB\" (or nearest node)"},
    15: {"description": "Support `addNum(int)` and `findMedian()` in O(log n) / O(1) using two heaps: max-heap for the lower half, min-heap for the upper half.\n\n**Example:**\nstream.addNum(1); stream.addNum(2);\nstream.findMedian() => 1.5\nstream.addNum(3);\nstream.findMedian() => 2.0\n\n**Key insight:** Keep heaps balanced (sizes differ by at most 1). Median is the top of the larger heap or average of both tops.", "sampleInput": "addNum(1,2,3) then findMedian()", "sampleOutput": "2.0"},
    16: {"description": "Implement `LFUCache(int capacity)` — evicts the **least frequently used** key (ties broken by LRU).\n\n**Example:**\nlfu = LFUCache(2)\nlfu.put(1,1); lfu.put(2,2);\nlfu.get(1) => 1 (freq[1]=2)\nlfu.put(3,3); // evicts key 2 (freq=1, LRU)\nlfu.get(2) => -1\nlfu.get(3) => 3\n\n**Key insight:** Maintain `Map<key,freq>`, `Map<freq, LinkedHashSet<key>>`, and min-frequency pointer.", "sampleInput": "put(1,1),put(2,2),get(1),put(3,3),get(2)", "sampleOutput": "-1"},
    17: {"description": "Design a time-based key-value store: `set(key, value, timestamp)` stores a value at a time; `get(key, timestamp)` returns the value with the largest timestamp <= given timestamp.\n\n**Example:**\nstore.set(\"foo\", \"bar\", 1);\nstore.set(\"foo\", \"bar2\", 4);\nstore.get(\"foo\", 4) => \"bar2\"\nstore.get(\"foo\", 3) => \"bar\"\nstore.get(\"foo\", 0) => \"\"\n\n**Key insight:** `Map<String, TreeMap<Integer,String>>` — `floorKey(timestamp)` finds the right entry.", "sampleInput": "set(foo,bar,1), set(foo,bar2,4), get(foo,3)", "sampleOutput": "\"bar\""},
    18: {"description": "Design a simplified Twitter feed: `postTweet(userId, tweetId)`, `getNewsFeed(userId)` returns 10 most recent tweets from the user and their followees, `follow(followerId, followeeId)`, `unfollow()`.\n\n**Example:**\npostTweet(1, 5); follow(1, 2); postTweet(2, 6);\ngetNewsFeed(1) => [6, 5]\nunfollow(1, 2);\ngetNewsFeed(1) => [5]\n\n**Key insight:** Per-user tweet lists + a heap merge across followees for the top-10.", "sampleInput": "postTweet(1,5), follow(1,2), postTweet(2,6), getNewsFeed(1)", "sampleOutput": "[6,5]"},
    19: {"description": "Serialize a BST to a string and deserialize it back. Use pre-order traversal with null markers.\n\n**Example:**\nBST: [4,2,6,1,3,5,7]\nserialize(root) => \"4,2,1,null,null,3,null,null,6,5,null,null,7,null,null\"\ndeserialize(\"4,2,1,...\") => same BST structure\ndeserialize(serialize(root)).inOrder() => [1,2,3,4,5,6,7]\n\n**Key insight:** Pre-order makes reconstruction unambiguous — root first, then left, then right.", "sampleInput": "serialize then deserialize BST [4,2,6,1,3,5,7]", "sampleOutput": "inOrder = [1,2,3,4,5,6,7]"},
    20: {"description": "Design a search autocomplete system that returns the top 3 hot sentences matching a prefix as the user types character by character.\n\n**Example:**\nsystem = AutocompleteSystem([\"i love you\",\"island\",\"iroman\"], [5,3,2])\nsystem.input('i') => [\"i love you\", \"island\", \"iroman\"]\nsystem.input(' ') => [\"i love you\"]\nsystem.input('#') => [] (stores the new sentence)\n\n**Key insight:** `Trie` + frequency map, or `HashMap<prefix, sorted sentences>`. '#' terminates input and records the typed sentence.", "sampleInput": "input('i') on sentences: [i love you(5), island(3), iroman(2)]", "sampleOutput": "[\"i love you\", \"island\", \"iroman\"]"},
}

updated = 0
for topic in data['topics']:
    for p in topic.get('problems', []):
        o = p['displayOrder']
        if o in improvements:
            p['description'] = improvements[o]['description']
            p['sampleInput'] = improvements[o]['sampleInput']
            p['sampleOutput'] = improvements[o]['sampleOutput']
            updated += 1
with open(f, 'w', encoding='utf-8') as fh: json.dump(data, fh, indent=2, ensure_ascii=False)
print(f"B17 updated: {updated} problems")
