#  Server
server.port=8080

# MySQL Database
spring.datasource.url=jdbc:mysql://root:GkseQZhPApJFTVrnVYpsIIfjFrrmVdcP@interchange.proxy.rlwy.net:38463/devlearn?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=GkseQZhPApJFTVrnVYpsIIfjFrrmVdcP
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#interchange.proxy.rlwy.net:38463
#  JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

#  JSON
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.default-property-inclusion=non_null

#  File Upload (for future use)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Logging
logging.level.com.learnsystem=INFO
logging.level.org.springframework.web=WARN

#  JWT
# CHANGE THIS to a long random secret in production!
app.jwt.secret=IF36iwGEqpQLlYBk4aPbAinWqkA+0gFq3vZJ3zATMli62aM5eZWpZyvHXmqOY9mjm+iX3zz6929Yf6r8pzD3QQ==

app.jwt.expiration-ms=86400000
# 24 hours in milliseconds (86400000)

# Google OAuth2
# 1. Go to https://console.cloud.google.com
# 2. Create project  APIs & Services  Credentials  OAuth2 Client ID
# 3. Add redirect URI: http://localhost:8080/login/oauth2/code/google
# 4. Paste your Client ID and Secret below:
spring.security.oauth2.client.registration.google.client-id=298245800996-ukpnr787ramioo10ldhjeajhe2tfc6o3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# Frontend URL (for OAuth2 redirect)
app.frontend-url=http://localhost:8080

# Mail (for email verification  optional)
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=your@gmail.com
# spring.mail.password=your-app-password
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

# Jackson ? fix LocalDateTime serialization
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

